// Code generated by cmd/pvegen. DO NOT EDIT.

// Package remotes exposes typed bindings for the PVE /remotes endpoint family.
package remotes

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
)

var _ = strings.TrimPrefix
var _ = json.RawMessage(nil)
var _ = url.PathEscape
var _ = sort.Ints
var _ = strconv.Itoa

// Service exposes typed operations on the /remotes endpoint family.
type Service interface {
	// ListRemotes GET /remotes
	// Directory index.
	ListRemotes(ctx context.Context) error
	// ListMetricCollectionStatus GET /remotes/metric-collection/status
	// Read metric collection status.
	ListMetricCollectionStatus(ctx context.Context) (*ListMetricCollectionStatusResponse, error)
	// CreateMetricCollectionTrigger POST /remotes/metric-collection/trigger
	// Trigger metric collection for a provided remote or for all remotes if no remote is passed.
	CreateMetricCollectionTrigger(ctx context.Context, params *CreateMetricCollectionTriggerParams) error
	// ListRemote GET /remotes/remote
	// List all the remotes this instance is managing.
	ListRemote(ctx context.Context) (*ListRemoteResponse, error)
	// CreateRemote POST /remotes/remote
	// Add a new remote to manage.  If `create-token` is specified, a new API token is generated on the target remote with the given name and used instead of the existing authentication details in the entry.
	CreateRemote(ctx context.Context, params *CreateRemoteParams) error
	// DeleteRemote DELETE /remotes/remote/{id}
	// Remove a remote that this instance is managing.
	DeleteRemote(ctx context.Context, id string, params *DeleteRemoteParams) error
	// GetRemote GET /remotes/remote/{id}
	// Directory index.
	GetRemote(ctx context.Context, id string) error
	// UpdateRemote PUT /remotes/remote/{id}
	// Update an existing managed remote.
	UpdateRemote(ctx context.Context, id string, params *UpdateRemoteParams) error
	// ListRemoteConfig GET /remotes/remote/{id}/config
	// Get the Remote Configuration
	ListRemoteConfig(ctx context.Context, id string) (*ListRemoteConfigResponse, error)
	// CreateRemoteProbeCertificate POST /remotes/remote/{id}/probe-certificate
	// Re-probe a configured node's TLS certificate without using the pinned fingerprint.  Lets clients detect a rotated certificate (the live connection only fails with an ambiguous connect error) and decide whether to update the stored fingerprint. This never changes the stored pin; updating it goes through `update_remote` after explicit user confirmation.
	CreateRemoteProbeCertificate(ctx context.Context, id string, params *CreateRemoteProbeCertificateParams) error
	// ListRemoteRrddata GET /remotes/remote/{id}/rrddata
	// Read metric collection RRD data.
	ListRemoteRrddata(ctx context.Context, id string, params *ListRemoteRrddataParams) (*ListRemoteRrddataResponse, error)
	// ListRemoteVersion GET /remotes/remote/{id}/version
	// Query the remote's version.  FIXME: Should we add an option to explicitly query the entire cluster to get a full version overview?
	ListRemoteVersion(ctx context.Context, id string) (*ListRemoteVersionResponse, error)
	// ListTasks GET /remotes/tasks
	// Directory index.
	ListTasks(ctx context.Context) error
	// ListTasksList GET /remotes/tasks/list
	// Get the list of tasks for all remotes.
	ListTasksList(ctx context.Context, params *ListTasksListParams) (*ListTasksListResponse, error)
	// CreateTasksRefresh POST /remotes/tasks/refresh
	// Refresh remote tasks cache.  If `remotes` is provided, tasks will only be fetched from the provided remotes. `Resource.Modify` permissions on `/resource/{remote}` are needed for every remote provided this way.  If `remotes` is not provided, then all remotes for which the user has appropriate permissions are considered.
	CreateTasksRefresh(ctx context.Context, params *CreateTasksRefreshParams) (*CreateTasksRefreshResponse, error)
	// ListTasksStatistics GET /remotes/tasks/statistics
	// Get task statistics for the specified filters.
	ListTasksStatistics(ctx context.Context, params *ListTasksStatisticsParams) (*ListTasksStatisticsResponse, error)
	// ListUpdates GET /remotes/updates
	// Directory index.
	ListUpdates(ctx context.Context) error
	// CreateUpdatesRefresh POST /remotes/updates/refresh
	// Refresh the update summary of all remotes.
	CreateUpdatesRefresh(ctx context.Context) (*CreateUpdatesRefreshResponse, error)
	// ListUpdatesSummary GET /remotes/updates/summary
	// Return available update summary for managed remote nodes.
	ListUpdatesSummary(ctx context.Context) (*ListUpdatesSummaryResponse, error)
}

// New constructs a Service backed by the given pkg/client.Client.
// The client owns authentication, TLS, retries, and logging; this
// service only translates between typed Go shapes and the raw client.
func New(c client.Client) Service {
	if c == nil {
		panic("remotes: New called with nil client")
	}
	return &service{c: c}
}

type service struct {
	c client.Client
}

// ListRemotes implements Service.ListRemotes. GET /remotes.
func (s *service) ListRemotes(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("remotes.ListRemotes: ctx must not be nil")
	}
	path := "/remotes"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("remotes.ListRemotes: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("remotes.ListRemotes: nil response from client")
	}
	_ = resp
	return nil
}

// ListMetricCollectionStatusResponse mirrors the shape returned by GET /remotes/metric-collection/status.
type ListMetricCollectionStatusResponse []json.RawMessage

// ListMetricCollectionStatus implements Service.ListMetricCollectionStatus. GET /remotes/metric-collection/status.
func (s *service) ListMetricCollectionStatus(ctx context.Context) (*ListMetricCollectionStatusResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("remotes.ListMetricCollectionStatus: ctx must not be nil")
	}
	path := "/remotes/metric-collection/status"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListMetricCollectionStatus: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("remotes.ListMetricCollectionStatus: nil response from client")
	}
	if resp.Data == nil {
		out := ListMetricCollectionStatusResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListMetricCollectionStatus: re-marshal data: %w", err)
	}
	out := &ListMetricCollectionStatusResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListMetricCollectionStatus: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateMetricCollectionTriggerParams is the request payload for CreateMetricCollectionTrigger.
type CreateMetricCollectionTriggerParams struct {
	// Remote Remote ID.
	Remote *string `json:"remote,omitempty"`
}

// CreateMetricCollectionTrigger implements Service.CreateMetricCollectionTrigger. POST /remotes/metric-collection/trigger.
func (s *service) CreateMetricCollectionTrigger(ctx context.Context, params *CreateMetricCollectionTriggerParams) error {
	if ctx == nil {
		return fmt.Errorf("remotes.CreateMetricCollectionTrigger: ctx must not be nil")
	}
	path := "/remotes/metric-collection/trigger"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("remotes.CreateMetricCollectionTrigger: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("remotes.CreateMetricCollectionTrigger: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("remotes.CreateMetricCollectionTrigger: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("remotes.CreateMetricCollectionTrigger: nil response from client")
	}
	_ = resp
	return nil
}

// ListRemoteResponse mirrors the shape returned by GET /remotes/remote.
type ListRemoteResponse []json.RawMessage

// ListRemote implements Service.ListRemote. GET /remotes/remote.
func (s *service) ListRemote(ctx context.Context) (*ListRemoteResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("remotes.ListRemote: ctx must not be nil")
	}
	path := "/remotes/remote"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListRemote: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("remotes.ListRemote: nil response from client")
	}
	if resp.Data == nil {
		out := ListRemoteResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListRemote: re-marshal data: %w", err)
	}
	out := &ListRemoteResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListRemote: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateRemoteParams is the request payload for CreateRemote.
type CreateRemoteParams struct {
	// Authid Authentication ID
	Authid string `json:"authid"`
	// CreateToken If given, create this token on the remote and use it.
	CreateToken *string `json:"create-token,omitempty"`
	// Id Remote ID.
	Id string `json:"id"`
	// Nodes A list of cluster node addresses.
	Nodes []string `json:"nodes"`
	// Token The access token's secret.
	Token string `json:"token"`
	// Type The type of a remote entry.
	Type string `json:"type"`
	// WebUrl Configuration for the Web UI URL link generation.
	WebUrl *string `json:"web-url,omitempty"`
}

// CreateRemote implements Service.CreateRemote. POST /remotes/remote.
func (s *service) CreateRemote(ctx context.Context, params *CreateRemoteParams) error {
	if ctx == nil {
		return fmt.Errorf("remotes.CreateRemote: ctx must not be nil")
	}
	path := "/remotes/remote"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("remotes.CreateRemote: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("remotes.CreateRemote: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("remotes.CreateRemote: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("remotes.CreateRemote: nil response from client")
	}
	_ = resp
	return nil
}

// DeleteRemoteParams is the request payload for DeleteRemote.
type DeleteRemoteParams struct {
	// DeleteToken If true, deletes the API token on the remote.
	DeleteToken *bool `json:"delete-token,omitempty"`
}

// DeleteRemote implements Service.DeleteRemote. DELETE /remotes/remote/{id}.
func (s *service) DeleteRemote(ctx context.Context, id string, params *DeleteRemoteParams) error {
	if ctx == nil {
		return fmt.Errorf("remotes.DeleteRemote: ctx must not be nil")
	}
	path := fmt.Sprintf("/remotes/remote/%s", url.PathEscape(id))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("remotes.DeleteRemote: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("remotes.DeleteRemote: decode params: %w", err)
		}
	}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("remotes.DeleteRemote: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("remotes.DeleteRemote: nil response from client")
	}
	_ = resp
	return nil
}

// GetRemote implements Service.GetRemote. GET /remotes/remote/{id}.
func (s *service) GetRemote(ctx context.Context, id string) error {
	if ctx == nil {
		return fmt.Errorf("remotes.GetRemote: ctx must not be nil")
	}
	path := fmt.Sprintf("/remotes/remote/%s", url.PathEscape(id))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("remotes.GetRemote: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("remotes.GetRemote: nil response from client")
	}
	_ = resp
	return nil
}

// UpdateRemoteParams is the request payload for UpdateRemote.
type UpdateRemoteParams struct {
	// Authid Authentication ID
	Authid *string `json:"authid,omitempty"`
	// Delete List of properties to delete.
	Delete []string `json:"delete,omitempty"`
	// Digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
	Digest *string `json:"digest,omitempty"`
	// Nodes A list of cluster node addresses.
	Nodes []string `json:"nodes,omitempty"`
	// Token The access token's secret.
	Token *string `json:"token,omitempty"`
	// WebUrl Configuration for the Web UI URL link generation.
	WebUrl *string `json:"web-url,omitempty"`
}

// UpdateRemote implements Service.UpdateRemote. PUT /remotes/remote/{id}.
func (s *service) UpdateRemote(ctx context.Context, id string, params *UpdateRemoteParams) error {
	if ctx == nil {
		return fmt.Errorf("remotes.UpdateRemote: ctx must not be nil")
	}
	path := fmt.Sprintf("/remotes/remote/%s", url.PathEscape(id))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("remotes.UpdateRemote: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("remotes.UpdateRemote: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("remotes.UpdateRemote: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("remotes.UpdateRemote: nil response from client")
	}
	_ = resp
	return nil
}

// ListRemoteConfigResponse mirrors the shape returned by GET /remotes/remote/{id}/config.
type ListRemoteConfigResponse struct {
	// Authid Authentication ID
	Authid string `json:"authid"`
	// Id Remote ID.
	Id string `json:"id"`
	// Nodes A list of cluster node addresses.
	Nodes []string `json:"nodes"`
	// Token The access token's secret.
	Token string `json:"token"`
	// Type The type of a remote entry.
	Type string `json:"type"`
	// WebUrl Configuration for the Web UI URL link generation.
	WebUrl *string `json:"web-url,omitempty"`
}

// ListRemoteConfig implements Service.ListRemoteConfig. GET /remotes/remote/{id}/config.
func (s *service) ListRemoteConfig(ctx context.Context, id string) (*ListRemoteConfigResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("remotes.ListRemoteConfig: ctx must not be nil")
	}
	path := fmt.Sprintf("/remotes/remote/%s/config", url.PathEscape(id))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListRemoteConfig: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("remotes.ListRemoteConfig: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("remotes.ListRemoteConfig: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListRemoteConfig: re-marshal data: %w", err)
	}
	out := &ListRemoteConfigResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListRemoteConfig: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateRemoteProbeCertificateParams is the request payload for CreateRemoteProbeCertificate.
type CreateRemoteProbeCertificateParams struct {
	// Node Hostname of the configured node to probe.
	Node string `json:"node"`
}

// CreateRemoteProbeCertificate implements Service.CreateRemoteProbeCertificate. POST /remotes/remote/{id}/probe-certificate.
func (s *service) CreateRemoteProbeCertificate(ctx context.Context, id string, params *CreateRemoteProbeCertificateParams) error {
	if ctx == nil {
		return fmt.Errorf("remotes.CreateRemoteProbeCertificate: ctx must not be nil")
	}
	path := fmt.Sprintf("/remotes/remote/%s/probe-certificate", url.PathEscape(id))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("remotes.CreateRemoteProbeCertificate: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("remotes.CreateRemoteProbeCertificate: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("remotes.CreateRemoteProbeCertificate: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("remotes.CreateRemoteProbeCertificate: nil response from client")
	}
	_ = resp
	return nil
}

// ListRemoteRrddataParams is the request payload for ListRemoteRrddata.
type ListRemoteRrddataParams struct {
	// Cf RRD consolidation mode
	Cf string `json:"cf"`
	// Timeframe RRD time frame
	Timeframe string `json:"timeframe"`
}

// ListRemoteRrddataResponse mirrors the shape returned by GET /remotes/remote/{id}/rrddata.
type ListRemoteRrddataResponse []json.RawMessage

// ListRemoteRrddata implements Service.ListRemoteRrddata. GET /remotes/remote/{id}/rrddata.
func (s *service) ListRemoteRrddata(ctx context.Context, id string, params *ListRemoteRrddataParams) (*ListRemoteRrddataResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("remotes.ListRemoteRrddata: ctx must not be nil")
	}
	path := fmt.Sprintf("/remotes/remote/%s/rrddata", url.PathEscape(id))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("remotes.ListRemoteRrddata: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("remotes.ListRemoteRrddata: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListRemoteRrddata: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("remotes.ListRemoteRrddata: nil response from client")
	}
	if resp.Data == nil {
		out := ListRemoteRrddataResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListRemoteRrddata: re-marshal data: %w", err)
	}
	out := &ListRemoteRrddataResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListRemoteRrddata: unmarshal data: %w", err)
	}
	return out, nil
}

// ListRemoteVersionResponse mirrors the shape returned by GET /remotes/remote/{id}/version.
type ListRemoteVersionResponse struct {
	// Console The default console viewer to use.
	Console *string `json:"console,omitempty"`
	// Release The current Proxmox VE point release in `x.y` format.
	Release string `json:"release"`
	// Repoid The short git revision from which this version was build.
	Repoid string `json:"repoid"`
	// Version The full pve-manager package version of this node.
	Version string `json:"version"`
}

// ListRemoteVersion implements Service.ListRemoteVersion. GET /remotes/remote/{id}/version.
func (s *service) ListRemoteVersion(ctx context.Context, id string) (*ListRemoteVersionResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("remotes.ListRemoteVersion: ctx must not be nil")
	}
	path := fmt.Sprintf("/remotes/remote/%s/version", url.PathEscape(id))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListRemoteVersion: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("remotes.ListRemoteVersion: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("remotes.ListRemoteVersion: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListRemoteVersion: re-marshal data: %w", err)
	}
	out := &ListRemoteVersionResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListRemoteVersion: unmarshal data: %w", err)
	}
	return out, nil
}

// ListTasks implements Service.ListTasks. GET /remotes/tasks.
func (s *service) ListTasks(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("remotes.ListTasks: ctx must not be nil")
	}
	path := "/remotes/tasks"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("remotes.ListTasks: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("remotes.ListTasks: nil response from client")
	}
	_ = resp
	return nil
}

// ListTasksListParams is the request payload for ListTasksList.
type ListTasksListParams struct {
	// Errors Only list erroneous tasks.
	Errors *bool `json:"errors,omitempty"`
	// Limit Only list this amount of tasks. (0 means no limit)
	Limit *int64 `json:"limit,omitempty"`
	// Remote Remote ID.
	Remote *string `json:"remote,omitempty"`
	// Running Only list running tasks.
	Running *bool `json:"running,omitempty"`
	// Since Only list tasks since this UNIX epoch.
	Since *int64 `json:"since,omitempty"`
	// Start List tasks beginning from this offset.
	Start *int64 `json:"start,omitempty"`
	// Statusfilter Only list tasks which have any one of the listed status.
	Statusfilter []string `json:"statusfilter,omitempty"`
	// Typefilter Only list tasks whose type contains this.
	Typefilter *string `json:"typefilter,omitempty"`
	// Until Only list tasks until this UNIX epoch.
	Until *int64 `json:"until,omitempty"`
	// Userfilter Only list tasks from this user.
	Userfilter *string `json:"userfilter,omitempty"`
	// View View name.
	View *string `json:"view,omitempty"`
}

// ListTasksListResponse mirrors the shape returned by GET /remotes/tasks/list.
type ListTasksListResponse []json.RawMessage

// ListTasksList implements Service.ListTasksList. GET /remotes/tasks/list.
func (s *service) ListTasksList(ctx context.Context, params *ListTasksListParams) (*ListTasksListResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("remotes.ListTasksList: ctx must not be nil")
	}
	path := "/remotes/tasks/list"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("remotes.ListTasksList: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("remotes.ListTasksList: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListTasksList: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("remotes.ListTasksList: nil response from client")
	}
	if resp.Data == nil {
		out := ListTasksListResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListTasksList: re-marshal data: %w", err)
	}
	out := &ListTasksListResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListTasksList: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateTasksRefreshParams is the request payload for CreateTasksRefresh.
type CreateTasksRefreshParams struct {
	// Remotes Optional list of tasks to fetch tasks from.
	Remotes []string `json:"remotes,omitempty"`
}

// CreateTasksRefreshResponse is the raw JSON returned by POST /remotes/tasks/refresh.
type CreateTasksRefreshResponse = json.RawMessage

// CreateTasksRefresh implements Service.CreateTasksRefresh. POST /remotes/tasks/refresh.
func (s *service) CreateTasksRefresh(ctx context.Context, params *CreateTasksRefreshParams) (*CreateTasksRefreshResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("remotes.CreateTasksRefresh: ctx must not be nil")
	}
	path := "/remotes/tasks/refresh"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("remotes.CreateTasksRefresh: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("remotes.CreateTasksRefresh: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("remotes.CreateTasksRefresh: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("remotes.CreateTasksRefresh: nil response from client")
	}
	if resp.Data == nil {
		out := CreateTasksRefreshResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("remotes.CreateTasksRefresh: re-marshal data: %w", err)
	}
	out := &CreateTasksRefreshResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("remotes.CreateTasksRefresh: unmarshal data: %w", err)
	}
	return out, nil
}

// ListTasksStatisticsParams is the request payload for ListTasksStatistics.
type ListTasksStatisticsParams struct {
	// Errors Only list erroneous tasks.
	Errors *bool `json:"errors,omitempty"`
	// Limit Only list this amount of tasks. (0 means no limit)
	Limit *int64 `json:"limit,omitempty"`
	// Remote Remote ID.
	Remote *string `json:"remote,omitempty"`
	// Running Only list running tasks.
	Running *bool `json:"running,omitempty"`
	// Since Only list tasks since this UNIX epoch.
	Since *int64 `json:"since,omitempty"`
	// Start List tasks beginning from this offset.
	Start *int64 `json:"start,omitempty"`
	// Statusfilter Only list tasks which have any one of the listed status.
	Statusfilter []string `json:"statusfilter,omitempty"`
	// Typefilter Only list tasks whose type contains this.
	Typefilter *string `json:"typefilter,omitempty"`
	// Until Only list tasks until this UNIX epoch.
	Until *int64 `json:"until,omitempty"`
	// Userfilter Only list tasks from this user.
	Userfilter *string `json:"userfilter,omitempty"`
	// View View name.
	View *string `json:"view,omitempty"`
}

// ListTasksStatisticsResponse mirrors the shape returned by GET /remotes/tasks/statistics.
type ListTasksStatisticsResponse struct {
	// ByRemote A map of remotes to status counts
	ByRemote json.RawMessage `json:"by-remote"`
	// ByType A map of worker-types to status counts
	ByType json.RawMessage `json:"by-type"`
}

// ListTasksStatistics implements Service.ListTasksStatistics. GET /remotes/tasks/statistics.
func (s *service) ListTasksStatistics(ctx context.Context, params *ListTasksStatisticsParams) (*ListTasksStatisticsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("remotes.ListTasksStatistics: ctx must not be nil")
	}
	path := "/remotes/tasks/statistics"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("remotes.ListTasksStatistics: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("remotes.ListTasksStatistics: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListTasksStatistics: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("remotes.ListTasksStatistics: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("remotes.ListTasksStatistics: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListTasksStatistics: re-marshal data: %w", err)
	}
	out := &ListTasksStatisticsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListTasksStatistics: unmarshal data: %w", err)
	}
	return out, nil
}

// ListUpdates implements Service.ListUpdates. GET /remotes/updates.
func (s *service) ListUpdates(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("remotes.ListUpdates: ctx must not be nil")
	}
	path := "/remotes/updates"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("remotes.ListUpdates: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("remotes.ListUpdates: nil response from client")
	}
	_ = resp
	return nil
}

// CreateUpdatesRefreshResponse is the raw JSON returned by POST /remotes/updates/refresh.
type CreateUpdatesRefreshResponse = json.RawMessage

// CreateUpdatesRefresh implements Service.CreateUpdatesRefresh. POST /remotes/updates/refresh.
func (s *service) CreateUpdatesRefresh(ctx context.Context) (*CreateUpdatesRefreshResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("remotes.CreateUpdatesRefresh: ctx must not be nil")
	}
	path := "/remotes/updates/refresh"
	var body map[string]interface{}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("remotes.CreateUpdatesRefresh: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("remotes.CreateUpdatesRefresh: nil response from client")
	}
	if resp.Data == nil {
		out := CreateUpdatesRefreshResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("remotes.CreateUpdatesRefresh: re-marshal data: %w", err)
	}
	out := &CreateUpdatesRefreshResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("remotes.CreateUpdatesRefresh: unmarshal data: %w", err)
	}
	return out, nil
}

// ListUpdatesSummaryResponse mirrors the shape returned by GET /remotes/updates/summary.
type ListUpdatesSummaryResponse struct {
	// Remotes Map of per-remote update summaries
	Remotes json.RawMessage `json:"remotes"`
}

// ListUpdatesSummary implements Service.ListUpdatesSummary. GET /remotes/updates/summary.
func (s *service) ListUpdatesSummary(ctx context.Context) (*ListUpdatesSummaryResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("remotes.ListUpdatesSummary: ctx must not be nil")
	}
	path := "/remotes/updates/summary"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListUpdatesSummary: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("remotes.ListUpdatesSummary: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("remotes.ListUpdatesSummary: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListUpdatesSummary: re-marshal data: %w", err)
	}
	out := &ListUpdatesSummaryResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("remotes.ListUpdatesSummary: unmarshal data: %w", err)
	}
	return out, nil
}
