// Code generated by cmd/pvegen. DO NOT EDIT.

package remotes_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"sync"
	"testing"

	pveclient "github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/pdm/remotes"
)

var _ = json.RawMessage(nil)

func smokeOptsFromServerURL(u string) pveclient.Options {
	parsed, err := url.Parse(u)
	if err != nil {
		panic("test setup: invalid server URL: " + err.Error())
	}

	host := parsed.Hostname()

	port := 0
	if p := parsed.Port(); p != "" {
		port, _ = strconv.Atoi(p)
	}

	return pveclient.Options{
		Host:     host,
		Port:     port,
		Protocol: "http",
		APIToken: "user@pam!tok=sec",
	}
}

// recordedRequest captures what the mock server observed for the most
// recently dispatched request.
type recordedRequest struct {
	method string
	path   string
	query  url.Values
	form   url.Values
}

// testHarness runs a single httptest.Server shared by every subtest in this
// file. Subtests are never run in parallel (each sets the desired response
// immediately before invoking the method under test, then reads back the
// recorded request), so the mutex below only guards against the harness
// goroutine and the test goroutine overlapping on a single in-flight
// request, never against concurrent subtests.
type testHarness struct {
	mu       sync.Mutex
	last     recordedRequest
	nextCode int
	nextBody string
}

// newTestHarness starts the mock server and returns it alongside the harness
// used to configure responses and inspect recorded requests.
func newTestHarness() (*httptest.Server, *testHarness) {
	h := &testHarness{nextCode: http.StatusOK}

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		h.mu.Lock()
		defer h.mu.Unlock()

		_ = r.ParseForm()
		h.last = recordedRequest{
			method: r.Method,
			path:   r.URL.Path,
			query:  r.URL.Query(),
			form:   r.PostForm,
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(h.nextCode)
		_, _ = w.Write([]byte(h.nextBody))
	}))

	return srv, h
}

// set configures the status code and body the next request will receive.
func (h *testHarness) set(code int, body string) {
	h.mu.Lock()
	defer h.mu.Unlock()

	h.nextCode = code
	h.nextBody = body
}

// snapshot returns a copy of the most recently recorded request.
func (h *testHarness) snapshot() recordedRequest {
	h.mu.Lock()
	defer h.mu.Unlock()

	return h.last
}

// assertRequestLine fails the test when the recorded method or resolved
// path does not exactly match what the endpoint's spec entry declares.
func assertRequestLine(t *testing.T, got recordedRequest, wantMethod, wantPath string) {
	t.Helper()

	if got.method != wantMethod {
		t.Errorf("method = %q, want %q", got.method, wantMethod)
	}

	if got.path != wantPath {
		t.Errorf("path = %q, want %q", got.path, wantPath)
	}
}

// assertParamValue fails the test when the wire-encoded value of key does
// not exactly equal want.
func assertParamValue(t *testing.T, values url.Values, key, want string) {
	t.Helper()

	if got := values.Get(key); got != want {
		t.Errorf("param %q = %q, want %q", key, got, want)
	}
}

// assertParamPresent fails the test when key is absent from values. Used for
// required parameters whose wire encoding is not a simple comparable string
// (e.g. json.RawMessage-typed fields).
func assertParamPresent(t *testing.T, values url.Values, key string) {
	t.Helper()

	if _, ok := values[key]; !ok {
		t.Errorf("param %q missing from request", key)
	}
}

func TestGenerated_Remotes_Methods(t *testing.T) {
	srv, harness := newTestHarness()
	defer srv.Close()

	c, err := pveclient.NewClient(smokeOptsFromServerURL(srv.URL))
	if err != nil {
		t.Fatalf("NewClient: %v", err)
	}

	svc := remotes.New(c)
	ctx := context.Background()

	t.Run("ListRemotes", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListRemotes(ctx)
		if err != nil {
			t.Fatalf("ListRemotes: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/remotes")

		var nilCtx context.Context
		if err := svc.ListRemotes(nilCtx); err == nil {
			t.Errorf("ListRemotes: expected error for nil context, got nil")
		}
	})
	t.Run("ListMetricCollectionStatus", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListMetricCollectionStatus(ctx)
		if err != nil {
			t.Fatalf("ListMetricCollectionStatus: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListMetricCollectionStatus: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/remotes/metric-collection/status")

		var nilCtx context.Context
		if _, err := svc.ListMetricCollectionStatus(nilCtx); err == nil {
			t.Errorf("ListMetricCollectionStatus: expected error for nil context, got nil")
		}
	})
	t.Run("CreateMetricCollectionTrigger", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateMetricCollectionTrigger(ctx, &remotes.CreateMetricCollectionTriggerParams{})
		if err != nil {
			t.Fatalf("CreateMetricCollectionTrigger: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/remotes/metric-collection/trigger")

		var nilCtx context.Context
		if err := svc.CreateMetricCollectionTrigger(nilCtx, &remotes.CreateMetricCollectionTriggerParams{}); err == nil {
			t.Errorf("CreateMetricCollectionTrigger: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemote", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemote(ctx)
		if err != nil {
			t.Fatalf("ListRemote: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemote: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/remotes/remote")

		var nilCtx context.Context
		if _, err := svc.ListRemote(nilCtx); err == nil {
			t.Errorf("ListRemote: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemote", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateRemote(ctx, &remotes.CreateRemoteParams{Authid: "sample-authid", Id: "sample-id", Nodes: []string{"sample-nodes"}, Token: "sample-token", Type: "sample-type"})
		if err != nil {
			t.Fatalf("CreateRemote: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/remotes/remote")
		assertParamValue(t, got.form, "authid", "sample-authid")
		assertParamValue(t, got.form, "id", "sample-id")
		assertParamValue(t, got.form, "nodes", "sample-nodes")
		assertParamValue(t, got.form, "token", "sample-token")
		assertParamValue(t, got.form, "type", "sample-type")

		var nilCtx context.Context
		if err := svc.CreateRemote(nilCtx, &remotes.CreateRemoteParams{Authid: "sample-authid", Id: "sample-id", Nodes: []string{"sample-nodes"}, Token: "sample-token", Type: "sample-type"}); err == nil {
			t.Errorf("CreateRemote: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteRemote", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.DeleteRemote(ctx, "sample-id", &remotes.DeleteRemoteParams{})
		if err != nil {
			t.Fatalf("DeleteRemote: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/remotes/remote/sample-id")

		var nilCtx context.Context
		if err := svc.DeleteRemote(nilCtx, "sample-id", &remotes.DeleteRemoteParams{}); err == nil {
			t.Errorf("DeleteRemote: expected error for nil context, got nil")
		}
	})
	t.Run("GetRemote", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.GetRemote(ctx, "sample-id")
		if err != nil {
			t.Fatalf("GetRemote: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/remotes/remote/sample-id")

		var nilCtx context.Context
		if err := svc.GetRemote(nilCtx, "sample-id"); err == nil {
			t.Errorf("GetRemote: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateRemote", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateRemote(ctx, "sample-id", &remotes.UpdateRemoteParams{})
		if err != nil {
			t.Fatalf("UpdateRemote: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/remotes/remote/sample-id")

		var nilCtx context.Context
		if err := svc.UpdateRemote(nilCtx, "sample-id", &remotes.UpdateRemoteParams{}); err == nil {
			t.Errorf("UpdateRemote: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemoteConfig", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemoteConfig(ctx, "sample-id")
		if err != nil {
			t.Fatalf("ListRemoteConfig: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemoteConfig: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/remotes/remote/sample-id/config")

		var nilCtx context.Context
		if _, err := svc.ListRemoteConfig(nilCtx, "sample-id"); err == nil {
			t.Errorf("ListRemoteConfig: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRemoteProbeCertificate", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateRemoteProbeCertificate(ctx, "sample-id", &remotes.CreateRemoteProbeCertificateParams{Node: "sample-node"})
		if err != nil {
			t.Fatalf("CreateRemoteProbeCertificate: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/remotes/remote/sample-id/probe-certificate")
		assertParamValue(t, got.form, "node", "sample-node")

		var nilCtx context.Context
		if err := svc.CreateRemoteProbeCertificate(nilCtx, "sample-id", &remotes.CreateRemoteProbeCertificateParams{Node: "sample-node"}); err == nil {
			t.Errorf("CreateRemoteProbeCertificate: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemoteRrddata", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRemoteRrddata(ctx, "sample-id", &remotes.ListRemoteRrddataParams{Cf: "sample-cf", Timeframe: "sample-timeframe"})
		if err != nil {
			t.Fatalf("ListRemoteRrddata: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemoteRrddata: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/remotes/remote/sample-id/rrddata")
		assertParamValue(t, got.query, "cf", "sample-cf")
		assertParamValue(t, got.query, "timeframe", "sample-timeframe")

		var nilCtx context.Context
		if _, err := svc.ListRemoteRrddata(nilCtx, "sample-id", &remotes.ListRemoteRrddataParams{Cf: "sample-cf", Timeframe: "sample-timeframe"}); err == nil {
			t.Errorf("ListRemoteRrddata: expected error for nil context, got nil")
		}
	})
	t.Run("ListRemoteVersion", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListRemoteVersion(ctx, "sample-id")
		if err != nil {
			t.Fatalf("ListRemoteVersion: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRemoteVersion: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/remotes/remote/sample-id/version")

		var nilCtx context.Context
		if _, err := svc.ListRemoteVersion(nilCtx, "sample-id"); err == nil {
			t.Errorf("ListRemoteVersion: expected error for nil context, got nil")
		}
	})
	t.Run("ListTasks", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListTasks(ctx)
		if err != nil {
			t.Fatalf("ListTasks: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/remotes/tasks")

		var nilCtx context.Context
		if err := svc.ListTasks(nilCtx); err == nil {
			t.Errorf("ListTasks: expected error for nil context, got nil")
		}
	})
	t.Run("ListTasksList", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListTasksList(ctx, &remotes.ListTasksListParams{})
		if err != nil {
			t.Fatalf("ListTasksList: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListTasksList: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/remotes/tasks/list")

		var nilCtx context.Context
		if _, err := svc.ListTasksList(nilCtx, &remotes.ListTasksListParams{}); err == nil {
			t.Errorf("ListTasksList: expected error for nil context, got nil")
		}
	})
	t.Run("CreateTasksRefresh", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateTasksRefresh(ctx, &remotes.CreateTasksRefreshParams{})
		if err != nil {
			t.Fatalf("CreateTasksRefresh: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateTasksRefresh: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/remotes/tasks/refresh")

		var nilCtx context.Context
		if _, err := svc.CreateTasksRefresh(nilCtx, &remotes.CreateTasksRefreshParams{}); err == nil {
			t.Errorf("CreateTasksRefresh: expected error for nil context, got nil")
		}
	})
	t.Run("ListTasksStatistics", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListTasksStatistics(ctx, &remotes.ListTasksStatisticsParams{})
		if err != nil {
			t.Fatalf("ListTasksStatistics: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListTasksStatistics: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/remotes/tasks/statistics")

		var nilCtx context.Context
		if _, err := svc.ListTasksStatistics(nilCtx, &remotes.ListTasksStatisticsParams{}); err == nil {
			t.Errorf("ListTasksStatistics: expected error for nil context, got nil")
		}
	})
	t.Run("ListUpdates", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListUpdates(ctx)
		if err != nil {
			t.Fatalf("ListUpdates: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/remotes/updates")

		var nilCtx context.Context
		if err := svc.ListUpdates(nilCtx); err == nil {
			t.Errorf("ListUpdates: expected error for nil context, got nil")
		}
	})
	t.Run("CreateUpdatesRefresh", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateUpdatesRefresh(ctx)
		if err != nil {
			t.Fatalf("CreateUpdatesRefresh: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateUpdatesRefresh: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/remotes/updates/refresh")

		var nilCtx context.Context
		if _, err := svc.CreateUpdatesRefresh(nilCtx); err == nil {
			t.Errorf("CreateUpdatesRefresh: expected error for nil context, got nil")
		}
	})
	t.Run("ListUpdatesSummary", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListUpdatesSummary(ctx)
		if err != nil {
			t.Fatalf("ListUpdatesSummary: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListUpdatesSummary: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/remotes/updates/summary")

		var nilCtx context.Context
		if _, err := svc.ListUpdatesSummary(nilCtx); err == nil {
			t.Errorf("ListUpdatesSummary: expected error for nil context, got nil")
		}
	})
	t.Run("ErrorPath_GET", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.ListRemotes(ctx)
		if err == nil {
			t.Fatalf("ListRemotes: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_POST", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.CreateMetricCollectionTrigger(ctx, &remotes.CreateMetricCollectionTriggerParams{})
		if err == nil {
			t.Fatalf("CreateMetricCollectionTrigger: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_DELETE", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.DeleteRemote(ctx, "sample-id", &remotes.DeleteRemoteParams{})
		if err == nil {
			t.Fatalf("DeleteRemote: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_PUT", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.UpdateRemote(ctx, "sample-id", &remotes.UpdateRemoteParams{})
		if err == nil {
			t.Fatalf("UpdateRemote: expected error on 500 response, got nil")
		}
	})
}
