// Code generated by cmd/pvegen. DO NOT EDIT.

// Package status exposes typed bindings for the PVE /status endpoint family.
package status

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
)

var _ = strings.TrimPrefix
var _ = json.RawMessage(nil)
var _ = url.PathEscape
var _ = sort.Ints
var _ = strconv.Itoa

// Service exposes typed operations on the /status endpoint family.
type Service interface {
	// ListStatus GET /status
	// Directory index.
	ListStatus(ctx context.Context) error
	// ListDatastoreUsage GET /status/datastore-usage
	// List Datastore usages and estimates
	ListDatastoreUsage(ctx context.Context) (*ListDatastoreUsageResponse, error)
	// ListMetrics GET /status/metrics
	// Return backup server metrics.
	ListMetrics(ctx context.Context, params *ListMetricsParams) error
}

// New constructs a Service backed by the given pkg/client.Client.
// The client owns authentication, TLS, retries, and logging; this
// service only translates between typed Go shapes and the raw client.
func New(c client.Client) Service {
	if c == nil {
		panic("status: New called with nil client")
	}
	return &service{c: c}
}

type service struct {
	c client.Client
}

// ListStatus implements Service.ListStatus. GET /status.
func (s *service) ListStatus(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("status.ListStatus: ctx must not be nil")
	}
	path := "/status"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("status.ListStatus: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("status.ListStatus: nil response from client")
	}
	_ = resp
	return nil
}

// ListDatastoreUsageResponse mirrors the shape returned by GET /status/datastore-usage.
type ListDatastoreUsageResponse []json.RawMessage

// ListDatastoreUsage implements Service.ListDatastoreUsage. GET /status/datastore-usage.
func (s *service) ListDatastoreUsage(ctx context.Context) (*ListDatastoreUsageResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("status.ListDatastoreUsage: ctx must not be nil")
	}
	path := "/status/datastore-usage"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("status.ListDatastoreUsage: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("status.ListDatastoreUsage: nil response from client")
	}
	if resp.Data == nil {
		out := ListDatastoreUsageResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("status.ListDatastoreUsage: re-marshal data: %w", err)
	}
	out := &ListDatastoreUsageResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("status.ListDatastoreUsage: unmarshal data: %w", err)
	}
	return out, nil
}

// ListMetricsParams is the request payload for ListMetrics.
type ListMetricsParams struct {
	// History Include historic values (last 30 minutes)
	History *bool `json:"history,omitempty"`
	// StartTime Only return values with a timestamp > start-time. Only has an effect if 'history' is also set
	StartTime *int64 `json:"start-time,omitempty"`
}

// ListMetrics implements Service.ListMetrics. GET /status/metrics.
func (s *service) ListMetrics(ctx context.Context, params *ListMetricsParams) error {
	if ctx == nil {
		return fmt.Errorf("status.ListMetrics: ctx must not be nil")
	}
	path := "/status/metrics"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("status.ListMetrics: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("status.ListMetrics: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("status.ListMetrics: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("status.ListMetrics: nil response from client")
	}
	_ = resp
	return nil
}
