// Code generated by cmd/pvegen. DO NOT EDIT.

// Package pull exposes typed bindings for the PVE /pull endpoint family.
package pull

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
)

var _ = strings.TrimPrefix
var _ = json.RawMessage(nil)
var _ = url.PathEscape
var _ = sort.Ints
var _ = strconv.Itoa

// Service exposes typed operations on the /pull endpoint family.
type Service interface {
	// Pull POST /pull
	// Sync store from other repository
	Pull(ctx context.Context, params *PullParams) error
}

// New constructs a Service backed by the given pkg/client.Client.
// The client owns authentication, TLS, retries, and logging; this
// service only translates between typed Go shapes and the raw client.
func New(c client.Client) Service {
	if c == nil {
		panic("pull: New called with nil client")
	}
	return &service{c: c}
}

type service struct {
	c client.Client
}

// PullParams is the request payload for Pull.
type PullParams struct {
	// BurstIn Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
	BurstIn *string `json:"burst-in,omitempty"`
	// BurstOut Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
	BurstOut *string `json:"burst-out,omitempty"`
	// DecryptionKeys List of decryption keys.
	DecryptionKeys []string `json:"decryption-keys,omitempty"`
	// EncryptedOnly Only synchronize encrypted backup snapshots, exclude others.
	EncryptedOnly *bool `json:"encrypted-only,omitempty"`
	// GroupFilter List of group filters.
	GroupFilter []string `json:"group-filter,omitempty"`
	// MaxDepth How many levels of namespaces should be operated on (0 == no recursion, empty == automatic full recursion, namespace depths reduce maximum allowed value)
	MaxDepth *int64 `json:"max-depth,omitempty"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
	// RateIn Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
	RateIn *string `json:"rate-in,omitempty"`
	// RateOut Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).
	RateOut *string `json:"rate-out,omitempty"`
	// Remote Remote ID.
	Remote *string `json:"remote,omitempty"`
	// RemoteNs Namespace.
	RemoteNs *string `json:"remote-ns,omitempty"`
	// RemoteStore Datastore name.
	RemoteStore string `json:"remote-store"`
	// RemoveVanished Delete vanished backups. This removes the local copy if the remote backup was deleted.
	RemoveVanished *bool `json:"remove-vanished,omitempty"`
	// ResyncCorrupt If the verification failed for a local snapshot, try to pull it again.
	ResyncCorrupt *bool `json:"resync-corrupt,omitempty"`
	// Store Datastore name.
	Store string `json:"store"`
	// TransferLast Limit transfer to last N snapshots (per group), skipping others
	TransferLast *int64 `json:"transfer-last,omitempty"`
	// VerifiedOnly Only synchronize verified backup snapshots, exclude others.
	VerifiedOnly *bool `json:"verified-only,omitempty"`
	// WorkerThreads The number of worker threads to process groups in parallel.
	WorkerThreads *int64 `json:"worker-threads,omitempty"`
}

// Pull implements Service.Pull. POST /pull.
func (s *service) Pull(ctx context.Context, params *PullParams) error {
	if ctx == nil {
		return fmt.Errorf("pull.Pull: ctx must not be nil")
	}
	path := "/pull"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("pull.Pull: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("pull.Pull: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("pull.Pull: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("pull.Pull: nil response from client")
	}
	_ = resp
	return nil
}
