// Code generated by cmd/pvegen. DO NOT EDIT.

package ceph_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"sync"
	"testing"

	pveclient "github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/pdm/ceph"
)

var _ = json.RawMessage(nil)

func smokeOptsFromServerURL(u string) pveclient.Options {
	parsed, err := url.Parse(u)
	if err != nil {
		panic("test setup: invalid server URL: " + err.Error())
	}

	host := parsed.Hostname()

	port := 0
	if p := parsed.Port(); p != "" {
		port, _ = strconv.Atoi(p)
	}

	return pveclient.Options{
		Host:     host,
		Port:     port,
		Protocol: "http",
		APIToken: "user@pam!tok=sec",
	}
}

// recordedRequest captures what the mock server observed for the most
// recently dispatched request.
type recordedRequest struct {
	method string
	path   string
	query  url.Values
	form   url.Values
}

// testHarness runs a single httptest.Server shared by every subtest in this
// file. Subtests are never run in parallel (each sets the desired response
// immediately before invoking the method under test, then reads back the
// recorded request), so the mutex below only guards against the harness
// goroutine and the test goroutine overlapping on a single in-flight
// request, never against concurrent subtests.
type testHarness struct {
	mu       sync.Mutex
	last     recordedRequest
	nextCode int
	nextBody string
}

// newTestHarness starts the mock server and returns it alongside the harness
// used to configure responses and inspect recorded requests.
func newTestHarness() (*httptest.Server, *testHarness) {
	h := &testHarness{nextCode: http.StatusOK}

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		h.mu.Lock()
		defer h.mu.Unlock()

		_ = r.ParseForm()
		h.last = recordedRequest{
			method: r.Method,
			path:   r.URL.Path,
			query:  r.URL.Query(),
			form:   r.PostForm,
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(h.nextCode)
		_, _ = w.Write([]byte(h.nextBody))
	}))

	return srv, h
}

// set configures the status code and body the next request will receive.
func (h *testHarness) set(code int, body string) {
	h.mu.Lock()
	defer h.mu.Unlock()

	h.nextCode = code
	h.nextBody = body
}

// snapshot returns a copy of the most recently recorded request.
func (h *testHarness) snapshot() recordedRequest {
	h.mu.Lock()
	defer h.mu.Unlock()

	return h.last
}

// assertRequestLine fails the test when the recorded method or resolved
// path does not exactly match what the endpoint's spec entry declares.
func assertRequestLine(t *testing.T, got recordedRequest, wantMethod, wantPath string) {
	t.Helper()

	if got.method != wantMethod {
		t.Errorf("method = %q, want %q", got.method, wantMethod)
	}

	if got.path != wantPath {
		t.Errorf("path = %q, want %q", got.path, wantPath)
	}
}

// assertParamValue fails the test when the wire-encoded value of key does
// not exactly equal want.
func assertParamValue(t *testing.T, values url.Values, key, want string) {
	t.Helper()

	if got := values.Get(key); got != want {
		t.Errorf("param %q = %q, want %q", key, got, want)
	}
}

// assertParamPresent fails the test when key is absent from values. Used for
// required parameters whose wire encoding is not a simple comparable string
// (e.g. json.RawMessage-typed fields).
func assertParamPresent(t *testing.T, values url.Values, key string) {
	t.Helper()

	if _, ok := values[key]; !ok {
		t.Errorf("param %q missing from request", key)
	}
}

func TestGenerated_Ceph_Methods(t *testing.T) {
	srv, harness := newTestHarness()
	defer srv.Close()

	c, err := pveclient.NewClient(smokeOptsFromServerURL(srv.URL))
	if err != nil {
		t.Fatalf("NewClient: %v", err)
	}

	svc := ceph.New(c)
	ctx := context.Background()

	t.Run("ListCeph", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListCeph(ctx)
		if err != nil {
			t.Fatalf("ListCeph: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/ceph")

		var nilCtx context.Context
		if err := svc.ListCeph(nilCtx); err == nil {
			t.Errorf("ListCeph: expected error for nil context, got nil")
		}
	})
	t.Run("ListClusters", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListClusters(ctx)
		if err != nil {
			t.Fatalf("ListClusters: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListClusters: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/ceph/clusters")

		var nilCtx context.Context
		if _, err := svc.ListClusters(nilCtx); err == nil {
			t.Errorf("ListClusters: expected error for nil context, got nil")
		}
	})
	t.Run("GetClusters", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.GetClusters(ctx, "sample-cluster")
		if err != nil {
			t.Fatalf("GetClusters: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/ceph/clusters/sample-cluster")

		var nilCtx context.Context
		if err := svc.GetClusters(nilCtx, "sample-cluster"); err == nil {
			t.Errorf("GetClusters: expected error for nil context, got nil")
		}
	})
	t.Run("ListClustersFlags", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListClustersFlags(ctx, "sample-cluster")
		if err != nil {
			t.Fatalf("ListClustersFlags: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListClustersFlags: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/ceph/clusters/sample-cluster/flags")

		var nilCtx context.Context
		if _, err := svc.ListClustersFlags(nilCtx, "sample-cluster"); err == nil {
			t.Errorf("ListClustersFlags: expected error for nil context, got nil")
		}
	})
	t.Run("ListClustersFs", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListClustersFs(ctx, "sample-cluster")
		if err != nil {
			t.Fatalf("ListClustersFs: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListClustersFs: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/ceph/clusters/sample-cluster/fs")

		var nilCtx context.Context
		if _, err := svc.ListClustersFs(nilCtx, "sample-cluster"); err == nil {
			t.Errorf("ListClustersFs: expected error for nil context, got nil")
		}
	})
	t.Run("ListClustersMds", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListClustersMds(ctx, "sample-cluster")
		if err != nil {
			t.Fatalf("ListClustersMds: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListClustersMds: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/ceph/clusters/sample-cluster/mds")

		var nilCtx context.Context
		if _, err := svc.ListClustersMds(nilCtx, "sample-cluster"); err == nil {
			t.Errorf("ListClustersMds: expected error for nil context, got nil")
		}
	})
	t.Run("ListClustersMgr", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListClustersMgr(ctx, "sample-cluster")
		if err != nil {
			t.Fatalf("ListClustersMgr: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListClustersMgr: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/ceph/clusters/sample-cluster/mgr")

		var nilCtx context.Context
		if _, err := svc.ListClustersMgr(nilCtx, "sample-cluster"); err == nil {
			t.Errorf("ListClustersMgr: expected error for nil context, got nil")
		}
	})
	t.Run("ListClustersMon", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListClustersMon(ctx, "sample-cluster")
		if err != nil {
			t.Fatalf("ListClustersMon: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListClustersMon: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/ceph/clusters/sample-cluster/mon")

		var nilCtx context.Context
		if _, err := svc.ListClustersMon(nilCtx, "sample-cluster"); err == nil {
			t.Errorf("ListClustersMon: expected error for nil context, got nil")
		}
	})
	t.Run("ListClustersOsdTree", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListClustersOsdTree(ctx, "sample-cluster")
		if err != nil {
			t.Fatalf("ListClustersOsdTree: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListClustersOsdTree: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/ceph/clusters/sample-cluster/osd-tree")

		var nilCtx context.Context
		if _, err := svc.ListClustersOsdTree(nilCtx, "sample-cluster"); err == nil {
			t.Errorf("ListClustersOsdTree: expected error for nil context, got nil")
		}
	})
	t.Run("ListClustersPools", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListClustersPools(ctx, "sample-cluster")
		if err != nil {
			t.Fatalf("ListClustersPools: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListClustersPools: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/ceph/clusters/sample-cluster/pools")

		var nilCtx context.Context
		if _, err := svc.ListClustersPools(nilCtx, "sample-cluster"); err == nil {
			t.Errorf("ListClustersPools: expected error for nil context, got nil")
		}
	})
	t.Run("ListClustersStatus", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListClustersStatus(ctx, "sample-cluster", &ceph.ListClustersStatusParams{})
		if err != nil {
			t.Fatalf("ListClustersStatus: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListClustersStatus: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/ceph/clusters/sample-cluster/status")

		var nilCtx context.Context
		if _, err := svc.ListClustersStatus(nilCtx, "sample-cluster", &ceph.ListClustersStatusParams{}); err == nil {
			t.Errorf("ListClustersStatus: expected error for nil context, got nil")
		}
	})
	t.Run("ListClustersSummary", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListClustersSummary(ctx, "sample-cluster", &ceph.ListClustersSummaryParams{})
		if err != nil {
			t.Fatalf("ListClustersSummary: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListClustersSummary: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/ceph/clusters/sample-cluster/summary")

		var nilCtx context.Context
		if _, err := svc.ListClustersSummary(nilCtx, "sample-cluster", &ceph.ListClustersSummaryParams{}); err == nil {
			t.Errorf("ListClustersSummary: expected error for nil context, got nil")
		}
	})
	t.Run("ErrorPath_GET", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.ListCeph(ctx)
		if err == nil {
			t.Fatalf("ListCeph: expected error on 500 response, got nil")
		}
	})
}
