// Code generated by cmd/pvegen. DO NOT EDIT.

// Package ceph exposes typed bindings for the PVE /ceph endpoint family.
package ceph

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
)

var _ = strings.TrimPrefix
var _ = json.RawMessage(nil)
var _ = url.PathEscape
var _ = sort.Ints
var _ = strconv.Itoa

// Service exposes typed operations on the /ceph endpoint family.
type Service interface {
	// ListCeph GET /ceph
	// Directory index.
	ListCeph(ctx context.Context) error
	// ListClusters GET /ceph/clusters
	// List registered Ceph clusters, filtered to those the caller can audit.
	ListClusters(ctx context.Context) (*ListClustersResponse, error)
	// GetClusters GET /ceph/clusters/{cluster}
	// Directory index.
	GetClusters(ctx context.Context, cluster string) error
	// ListClustersFlags GET /ceph/clusters/{cluster}/flags
	// Cluster-wide Ceph flags.
	ListClustersFlags(ctx context.Context, cluster string) (*ListClustersFlagsResponse, error)
	// ListClustersFs GET /ceph/clusters/{cluster}/fs
	// List the cluster's CephFS file systems.
	ListClustersFs(ctx context.Context, cluster string) (*ListClustersFsResponse, error)
	// ListClustersMds GET /ceph/clusters/{cluster}/mds
	// List the cluster's Ceph metadata servers (MDS).
	ListClustersMds(ctx context.Context, cluster string) (*ListClustersMdsResponse, error)
	// ListClustersMgr GET /ceph/clusters/{cluster}/mgr
	// List the cluster's Ceph managers.
	ListClustersMgr(ctx context.Context, cluster string) (*ListClustersMgrResponse, error)
	// ListClustersMon GET /ceph/clusters/{cluster}/mon
	// List the cluster's Ceph monitors.
	ListClustersMon(ctx context.Context, cluster string) (*ListClustersMonResponse, error)
	// ListClustersOsdTree GET /ceph/clusters/{cluster}/osd-tree
	// The cluster's OSD (CRUSH) tree.
	ListClustersOsdTree(ctx context.Context, cluster string) (*ListClustersOsdTreeResponse, error)
	// ListClustersPools GET /ceph/clusters/{cluster}/pools
	// List the cluster's Ceph pools.
	ListClustersPools(ctx context.Context, cluster string) (*ListClustersPoolsResponse, error)
	// ListClustersStatus GET /ceph/clusters/{cluster}/status
	// Cluster-wide Ceph status (the raw `ceph status` object), served from the cache within `max-age` seconds or fetched fresh and cached.
	ListClustersStatus(ctx context.Context, cluster string, params *ListClustersStatusParams) (*ListClustersStatusResponse, error)
	// ListClustersSummary GET /ceph/clusters/{cluster}/summary
	// Typed, summarized Ceph cluster status (health, capacity, OSD/MON/MGR/PG counts) for the dashboard. Most fields come from the cached `ceph status` (so the UI binds typed fields instead of parsing a raw blob); the fullest-pool and version fields are enriched from a live, best-effort member read (see [`enrich_summary`]).
	ListClustersSummary(ctx context.Context, cluster string, params *ListClustersSummaryParams) (*ListClustersSummaryResponse, error)
}

// New constructs a Service backed by the given pkg/client.Client.
// The client owns authentication, TLS, retries, and logging; this
// service only translates between typed Go shapes and the raw client.
func New(c client.Client) Service {
	if c == nil {
		panic("ceph: New called with nil client")
	}
	return &service{c: c}
}

type service struct {
	c client.Client
}

// ListCeph implements Service.ListCeph. GET /ceph.
func (s *service) ListCeph(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("ceph.ListCeph: ctx must not be nil")
	}
	path := "/ceph"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("ceph.ListCeph: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("ceph.ListCeph: nil response from client")
	}
	_ = resp
	return nil
}

// ListClustersResponse mirrors the shape returned by GET /ceph/clusters.
type ListClustersResponse []json.RawMessage

// ListClusters implements Service.ListClusters. GET /ceph/clusters.
func (s *service) ListClusters(ctx context.Context) (*ListClustersResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("ceph.ListClusters: ctx must not be nil")
	}
	path := "/ceph/clusters"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClusters: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("ceph.ListClusters: nil response from client")
	}
	if resp.Data == nil {
		out := ListClustersResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClusters: re-marshal data: %w", err)
	}
	out := &ListClustersResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClusters: unmarshal data: %w", err)
	}
	return out, nil
}

// GetClusters implements Service.GetClusters. GET /ceph/clusters/{cluster}.
func (s *service) GetClusters(ctx context.Context, cluster string) error {
	if ctx == nil {
		return fmt.Errorf("ceph.GetClusters: ctx must not be nil")
	}
	path := fmt.Sprintf("/ceph/clusters/%s", url.PathEscape(cluster))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("ceph.GetClusters: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("ceph.GetClusters: nil response from client")
	}
	_ = resp
	return nil
}

// ListClustersFlagsResponse mirrors the shape returned by GET /ceph/clusters/{cluster}/flags.
type ListClustersFlagsResponse []json.RawMessage

// ListClustersFlags implements Service.ListClustersFlags. GET /ceph/clusters/{cluster}/flags.
func (s *service) ListClustersFlags(ctx context.Context, cluster string) (*ListClustersFlagsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("ceph.ListClustersFlags: ctx must not be nil")
	}
	path := fmt.Sprintf("/ceph/clusters/%s/flags", url.PathEscape(cluster))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersFlags: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("ceph.ListClustersFlags: nil response from client")
	}
	if resp.Data == nil {
		out := ListClustersFlagsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersFlags: re-marshal data: %w", err)
	}
	out := &ListClustersFlagsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersFlags: unmarshal data: %w", err)
	}
	return out, nil
}

// ListClustersFsResponse mirrors the shape returned by GET /ceph/clusters/{cluster}/fs.
type ListClustersFsResponse []json.RawMessage

// ListClustersFs implements Service.ListClustersFs. GET /ceph/clusters/{cluster}/fs.
func (s *service) ListClustersFs(ctx context.Context, cluster string) (*ListClustersFsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("ceph.ListClustersFs: ctx must not be nil")
	}
	path := fmt.Sprintf("/ceph/clusters/%s/fs", url.PathEscape(cluster))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersFs: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("ceph.ListClustersFs: nil response from client")
	}
	if resp.Data == nil {
		out := ListClustersFsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersFs: re-marshal data: %w", err)
	}
	out := &ListClustersFsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersFs: unmarshal data: %w", err)
	}
	return out, nil
}

// ListClustersMdsResponse mirrors the shape returned by GET /ceph/clusters/{cluster}/mds.
type ListClustersMdsResponse []json.RawMessage

// ListClustersMds implements Service.ListClustersMds. GET /ceph/clusters/{cluster}/mds.
func (s *service) ListClustersMds(ctx context.Context, cluster string) (*ListClustersMdsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("ceph.ListClustersMds: ctx must not be nil")
	}
	path := fmt.Sprintf("/ceph/clusters/%s/mds", url.PathEscape(cluster))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersMds: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("ceph.ListClustersMds: nil response from client")
	}
	if resp.Data == nil {
		out := ListClustersMdsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersMds: re-marshal data: %w", err)
	}
	out := &ListClustersMdsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersMds: unmarshal data: %w", err)
	}
	return out, nil
}

// ListClustersMgrResponse mirrors the shape returned by GET /ceph/clusters/{cluster}/mgr.
type ListClustersMgrResponse []json.RawMessage

// ListClustersMgr implements Service.ListClustersMgr. GET /ceph/clusters/{cluster}/mgr.
func (s *service) ListClustersMgr(ctx context.Context, cluster string) (*ListClustersMgrResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("ceph.ListClustersMgr: ctx must not be nil")
	}
	path := fmt.Sprintf("/ceph/clusters/%s/mgr", url.PathEscape(cluster))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersMgr: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("ceph.ListClustersMgr: nil response from client")
	}
	if resp.Data == nil {
		out := ListClustersMgrResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersMgr: re-marshal data: %w", err)
	}
	out := &ListClustersMgrResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersMgr: unmarshal data: %w", err)
	}
	return out, nil
}

// ListClustersMonResponse mirrors the shape returned by GET /ceph/clusters/{cluster}/mon.
type ListClustersMonResponse []json.RawMessage

// ListClustersMon implements Service.ListClustersMon. GET /ceph/clusters/{cluster}/mon.
func (s *service) ListClustersMon(ctx context.Context, cluster string) (*ListClustersMonResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("ceph.ListClustersMon: ctx must not be nil")
	}
	path := fmt.Sprintf("/ceph/clusters/%s/mon", url.PathEscape(cluster))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersMon: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("ceph.ListClustersMon: nil response from client")
	}
	if resp.Data == nil {
		out := ListClustersMonResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersMon: re-marshal data: %w", err)
	}
	out := &ListClustersMonResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersMon: unmarshal data: %w", err)
	}
	return out, nil
}

// ListClustersOsdTreeResponse is the raw JSON returned by GET /ceph/clusters/{cluster}/osd-tree.
type ListClustersOsdTreeResponse = json.RawMessage

// ListClustersOsdTree implements Service.ListClustersOsdTree. GET /ceph/clusters/{cluster}/osd-tree.
func (s *service) ListClustersOsdTree(ctx context.Context, cluster string) (*ListClustersOsdTreeResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("ceph.ListClustersOsdTree: ctx must not be nil")
	}
	path := fmt.Sprintf("/ceph/clusters/%s/osd-tree", url.PathEscape(cluster))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersOsdTree: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("ceph.ListClustersOsdTree: nil response from client")
	}
	if resp.Data == nil {
		out := ListClustersOsdTreeResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersOsdTree: re-marshal data: %w", err)
	}
	out := &ListClustersOsdTreeResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersOsdTree: unmarshal data: %w", err)
	}
	return out, nil
}

// ListClustersPoolsResponse mirrors the shape returned by GET /ceph/clusters/{cluster}/pools.
type ListClustersPoolsResponse []json.RawMessage

// ListClustersPools implements Service.ListClustersPools. GET /ceph/clusters/{cluster}/pools.
func (s *service) ListClustersPools(ctx context.Context, cluster string) (*ListClustersPoolsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("ceph.ListClustersPools: ctx must not be nil")
	}
	path := fmt.Sprintf("/ceph/clusters/%s/pools", url.PathEscape(cluster))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersPools: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("ceph.ListClustersPools: nil response from client")
	}
	if resp.Data == nil {
		out := ListClustersPoolsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersPools: re-marshal data: %w", err)
	}
	out := &ListClustersPoolsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersPools: unmarshal data: %w", err)
	}
	return out, nil
}

// ListClustersStatusParams is the request payload for ListClustersStatus.
type ListClustersStatusParams struct {
	// MaxAge Serve a cached status if it is younger than this many seconds.
	MaxAge *int64 `json:"max-age,omitempty"`
}

// ListClustersStatusResponse is the raw JSON returned by GET /ceph/clusters/{cluster}/status.
type ListClustersStatusResponse = json.RawMessage

// ListClustersStatus implements Service.ListClustersStatus. GET /ceph/clusters/{cluster}/status.
func (s *service) ListClustersStatus(ctx context.Context, cluster string, params *ListClustersStatusParams) (*ListClustersStatusResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("ceph.ListClustersStatus: ctx must not be nil")
	}
	path := fmt.Sprintf("/ceph/clusters/%s/status", url.PathEscape(cluster))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("ceph.ListClustersStatus: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("ceph.ListClustersStatus: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersStatus: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("ceph.ListClustersStatus: nil response from client")
	}
	if resp.Data == nil {
		out := ListClustersStatusResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersStatus: re-marshal data: %w", err)
	}
	out := &ListClustersStatusResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersStatus: unmarshal data: %w", err)
	}
	return out, nil
}

// ListClustersSummaryParams is the request payload for ListClustersSummary.
type ListClustersSummaryParams struct {
	// MaxAge Serve a cached status if it is younger than this many seconds.
	MaxAge *int64 `json:"max-age,omitempty"`
}

// ListClustersSummaryResponse mirrors the shape returned by GET /ceph/clusters/{cluster}/summary.
type ListClustersSummaryResponse struct {
	// BytesAvail Available capacity in bytes.
	BytesAvail client.PVEInt `json:"bytes-avail"`
	// BytesTotal Total raw capacity in bytes.
	BytesTotal client.PVEInt `json:"bytes-total"`
	// BytesUsed Used capacity in bytes.
	BytesUsed client.PVEInt `json:"bytes-used"`
	// Checks Active health checks.
	Checks []json.RawMessage `json:"checks,omitempty"`
	// ClientReadBytesSec Client read throughput (bytes/s), when reported.
	ClientReadBytesSec *client.PVEInt `json:"client-read-bytes-sec,omitempty"`
	// ClientReadOpsSec Client read ops/s, when reported.
	ClientReadOpsSec *client.PVEInt `json:"client-read-ops-sec,omitempty"`
	// ClientWriteBytesSec Client write throughput (bytes/s), when reported.
	ClientWriteBytesSec *client.PVEInt `json:"client-write-bytes-sec,omitempty"`
	// ClientWriteOpsSec Client write ops/s, when reported.
	ClientWriteOpsSec *client.PVEInt `json:"client-write-ops-sec,omitempty"`
	// DegradedRatio Fraction of objects degraded, when degraded.
	DegradedRatio *client.PVEFloat `json:"degraded-ratio,omitempty"`
	// Fsid Cluster fsid.
	Fsid string `json:"fsid"`
	// FullestPool Name of the most-utilized pool, to surface a near-full pool that the cluster-wide capacity figure would otherwise hide.
	FullestPool *string `json:"fullest-pool,omitempty"`
	// FullestPoolUsed Used percentage (0-100) of [`Self::fullest_pool`].
	FullestPoolUsed *client.PVEFloat `json:"fullest-pool-used,omitempty"`
	// Health Overall health (`HEALTH_OK` / `HEALTH_WARN` / `HEALTH_ERR`).
	Health string `json:"health"`
	// Members The cluster's registered members (the PVE remotes / nodes backing it). From the PDM registry, not the live status; surfaces cross-remote membership on the overview. Filled by the summary endpoint.
	Members []json.RawMessage `json:"members,omitempty"`
	// MgrActive Active manager, if any.
	MgrActive *string `json:"mgr-active,omitempty"`
	// MgrStandbys Standby managers.
	MgrStandbys []string `json:"mgr-standbys,omitempty"`
	// MisplacedRatio Fraction of objects misplaced, when rebalancing.
	MisplacedRatio *client.PVEFloat `json:"misplaced-ratio,omitempty"`
	// MonsInQuorum Monitors currently in quorum.
	MonsInQuorum client.PVEInt `json:"mons-in-quorum"`
	// MonsTotal Total monitors.
	MonsTotal client.PVEInt `json:"mons-total"`
	// NumPgs Total number of placement groups.
	NumPgs client.PVEInt `json:"num-pgs"`
	// NumPools Number of pools.
	NumPools client.PVEInt `json:"num-pools"`
	// OsdsIn OSDs currently in.
	OsdsIn client.PVEInt `json:"osds-in"`
	// OsdsTotal Total OSDs known to the cluster.
	OsdsTotal client.PVEInt `json:"osds-total"`
	// OsdsUp OSDs currently up.
	OsdsUp client.PVEInt `json:"osds-up"`
	// PgsByState PG counts grouped by state.
	PgsByState []json.RawMessage `json:"pgs-by-state,omitempty"`
	// RecoveryBytesSec Recovery throughput (bytes/s), when a recovery is active.
	RecoveryBytesSec *client.PVEInt `json:"recovery-bytes-sec,omitempty"`
	// Version Representative Ceph version of the cluster (from the monitors).
	Version *string `json:"version,omitempty"`
	// VersionMixed Whether the monitors report more than one distinct Ceph version (a mid-upgrade / version-skew signal).
	VersionMixed *client.PVEBool `json:"version-mixed,omitempty"`
}

// ListClustersSummary implements Service.ListClustersSummary. GET /ceph/clusters/{cluster}/summary.
func (s *service) ListClustersSummary(ctx context.Context, cluster string, params *ListClustersSummaryParams) (*ListClustersSummaryResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("ceph.ListClustersSummary: ctx must not be nil")
	}
	path := fmt.Sprintf("/ceph/clusters/%s/summary", url.PathEscape(cluster))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("ceph.ListClustersSummary: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("ceph.ListClustersSummary: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersSummary: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("ceph.ListClustersSummary: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("ceph.ListClustersSummary: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersSummary: re-marshal data: %w", err)
	}
	out := &ListClustersSummaryResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("ceph.ListClustersSummary: unmarshal data: %w", err)
	}
	return out, nil
}
