// Code generated by cmd/pvegen. DO NOT EDIT.

// Package resources exposes typed bindings for the PVE /resources endpoint family.
package resources

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
)

var _ = strings.TrimPrefix
var _ = json.RawMessage(nil)
var _ = url.PathEscape
var _ = sort.Ints
var _ = strconv.Itoa

// Service exposes typed operations on the /resources endpoint family.
type Service interface {
	// ListResources GET /resources
	// Directory index.
	ListResources(ctx context.Context) error
	// ListList GET /resources/list
	// List all resources from remote nodes.
	ListList(ctx context.Context, params *ListListParams) (*ListListResponse, error)
	// ListLocationInfo GET /resources/location-info
	// Get the location info of the selected view (or all remotes)
	ListLocationInfo(ctx context.Context, params *ListLocationInfoParams) error
	// ListStatus GET /resources/status
	// Return the amount of configured/seen resources by type
	ListStatus(ctx context.Context, params *ListStatusParams) (*ListStatusResponse, error)
	// ListSubscription GET /resources/subscription
	// Returns the subscription status of the remotes
	ListSubscription(ctx context.Context, params *ListSubscriptionParams) (*ListSubscriptionResponse, error)
	// ListTopEntities GET /resources/top-entities
	// Returns the top X entities regarding the chosen type
	ListTopEntities(ctx context.Context, params *ListTopEntitiesParams) (*ListTopEntitiesResponse, error)
}

// New constructs a Service backed by the given pkg/client.Client.
// The client owns authentication, TLS, retries, and logging; this
// service only translates between typed Go shapes and the raw client.
func New(c client.Client) Service {
	if c == nil {
		panic("resources: New called with nil client")
	}
	return &service{c: c}
}

type service struct {
	c client.Client
}

// ListResources implements Service.ListResources. GET /resources.
func (s *service) ListResources(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("resources.ListResources: ctx must not be nil")
	}
	path := "/resources"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("resources.ListResources: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("resources.ListResources: nil response from client")
	}
	_ = resp
	return nil
}

// ListListParams is the request payload for ListList.
type ListListParams struct {
	// MaxAge Maximum age (in seconds) of cached remote resources.
	MaxAge *int64 `json:"max-age,omitempty"`
	// ResourceType Type of a PDM resource.
	ResourceType *string `json:"resource-type,omitempty"`
	// Search Search term to filter for, uses special syntax e.g. <TODO>
	Search *string `json:"search,omitempty"`
	// View View name.
	View *string `json:"view,omitempty"`
}

// ListListResponse mirrors the shape returned by GET /resources/list.
type ListListResponse []json.RawMessage

// ListList implements Service.ListList. GET /resources/list.
func (s *service) ListList(ctx context.Context, params *ListListParams) (*ListListResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("resources.ListList: ctx must not be nil")
	}
	path := "/resources/list"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("resources.ListList: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("resources.ListList: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("resources.ListList: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("resources.ListList: nil response from client")
	}
	if resp.Data == nil {
		out := ListListResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("resources.ListList: re-marshal data: %w", err)
	}
	out := &ListListResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("resources.ListList: unmarshal data: %w", err)
	}
	return out, nil
}

// ListLocationInfoParams is the request payload for ListLocationInfo.
type ListLocationInfoParams struct {
	// MaxAge Maximum age (in seconds) of cached remote resources. If remote is not reachable or returns an error for the location, the last value from the cache will be returned in any case
	MaxAge *int64 `json:"max-age,omitempty"`
	// View View name.
	View *string `json:"view,omitempty"`
}

// ListLocationInfo implements Service.ListLocationInfo. GET /resources/location-info.
func (s *service) ListLocationInfo(ctx context.Context, params *ListLocationInfoParams) error {
	if ctx == nil {
		return fmt.Errorf("resources.ListLocationInfo: ctx must not be nil")
	}
	path := "/resources/location-info"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("resources.ListLocationInfo: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("resources.ListLocationInfo: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("resources.ListLocationInfo: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("resources.ListLocationInfo: nil response from client")
	}
	_ = resp
	return nil
}

// ListStatusParams is the request payload for ListStatus.
type ListStatusParams struct {
	// MaxAge Maximum age (in seconds) of cached remote resources.
	MaxAge *int64 `json:"max-age,omitempty"`
	// View View name.
	View *string `json:"view,omitempty"`
}

// ListStatusResponse mirrors the shape returned by GET /resources/status.
type ListStatusResponse struct {
	// Error Any error that occurred when querying remote resources
	Error *string `json:"error,omitempty"`
	// Remote Remote ID.
	Remote string `json:"remote"`
	// Resources Array of resources found at this remote.
	Resources []json.RawMessage `json:"resources"`
}

// ListStatus implements Service.ListStatus. GET /resources/status.
func (s *service) ListStatus(ctx context.Context, params *ListStatusParams) (*ListStatusResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("resources.ListStatus: ctx must not be nil")
	}
	path := "/resources/status"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("resources.ListStatus: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("resources.ListStatus: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("resources.ListStatus: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("resources.ListStatus: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("resources.ListStatus: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("resources.ListStatus: re-marshal data: %w", err)
	}
	out := &ListStatusResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("resources.ListStatus: unmarshal data: %w", err)
	}
	return out, nil
}

// ListSubscriptionParams is the request payload for ListSubscription.
type ListSubscriptionParams struct {
	// MaxAge Maximum age (in seconds) of cached remote subscription state.
	MaxAge *int64 `json:"max-age,omitempty"`
	// Verbose If true, includes subscription information per node (with enough privileges)
	Verbose *bool `json:"verbose,omitempty"`
	// View View name.
	View *string `json:"view,omitempty"`
}

// ListSubscriptionResponse mirrors the shape returned by GET /resources/subscription.
type ListSubscriptionResponse []json.RawMessage

// ListSubscription implements Service.ListSubscription. GET /resources/subscription.
func (s *service) ListSubscription(ctx context.Context, params *ListSubscriptionParams) (*ListSubscriptionResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("resources.ListSubscription: ctx must not be nil")
	}
	path := "/resources/subscription"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("resources.ListSubscription: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("resources.ListSubscription: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("resources.ListSubscription: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("resources.ListSubscription: nil response from client")
	}
	if resp.Data == nil {
		out := ListSubscriptionResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("resources.ListSubscription: re-marshal data: %w", err)
	}
	out := &ListSubscriptionResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("resources.ListSubscription: unmarshal data: %w", err)
	}
	return out, nil
}

// ListTopEntitiesParams is the request payload for ListTopEntities.
type ListTopEntitiesParams struct {
	// Timeframe RRD time frame
	Timeframe *string `json:"timeframe,omitempty"`
	// View View name.
	View *string `json:"view,omitempty"`
}

// ListTopEntitiesResponse mirrors the shape returned by GET /resources/top-entities.
type ListTopEntitiesResponse struct {
	// GuestCpu The top entries for Guest CPU
	GuestCpu []json.RawMessage `json:"guest-cpu"`
	// NodeCpu The top entries for Node CPU
	NodeCpu []json.RawMessage `json:"node-cpu"`
	// NodeMemory The top entries for Node Memory
	NodeMemory []json.RawMessage `json:"node-memory"`
}

// ListTopEntities implements Service.ListTopEntities. GET /resources/top-entities.
func (s *service) ListTopEntities(ctx context.Context, params *ListTopEntitiesParams) (*ListTopEntitiesResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("resources.ListTopEntities: ctx must not be nil")
	}
	path := "/resources/top-entities"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("resources.ListTopEntities: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("resources.ListTopEntities: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("resources.ListTopEntities: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("resources.ListTopEntities: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("resources.ListTopEntities: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("resources.ListTopEntities: re-marshal data: %w", err)
	}
	out := &ListTopEntitiesResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("resources.ListTopEntities: unmarshal data: %w", err)
	}
	return out, nil
}
