// Code generated by cmd/pvegen. DO NOT EDIT.

// Package tape exposes typed bindings for the PVE /tape endpoint family.
package tape

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
)

var _ = strings.TrimPrefix
var _ = json.RawMessage(nil)
var _ = url.PathEscape
var _ = sort.Ints
var _ = strconv.Itoa

// Service exposes typed operations on the /tape endpoint family.
type Service interface {
	// ListTape GET /tape
	// Directory index.
	ListTape(ctx context.Context) error
	// ListBackup GET /tape/backup
	// List all tape backup jobs
	ListBackup(ctx context.Context) (*ListBackupResponse, error)
	// CreateBackup POST /tape/backup
	// Backup datastore to tape media pool
	CreateBackup(ctx context.Context, params *CreateBackupParams) (*CreateBackupResponse, error)
	// CreateBackup2 POST /tape/backup/{id}
	// Runs a tape backup job manually.
	CreateBackup2(ctx context.Context, id string) error
	// ListChanger GET /tape/changer
	// List changers
	ListChanger(ctx context.Context) (*ListChangerResponse, error)
	// GetChanger GET /tape/changer/{name}
	// Directory index.
	GetChanger(ctx context.Context, name string) error
	// ListChangerStatus GET /tape/changer/{name}/status
	// Get tape changer status
	ListChangerStatus(ctx context.Context, name string, params *ListChangerStatusParams) (*ListChangerStatusResponse, error)
	// CreateChangerTransfer POST /tape/changer/{name}/transfer
	// Transfers media from one slot to another
	CreateChangerTransfer(ctx context.Context, name string, params *CreateChangerTransferParams) error
	// ListDrive GET /tape/drive
	// List drives
	ListDrive(ctx context.Context, params *ListDriveParams) (*ListDriveResponse, error)
	// GetDrive GET /tape/drive/{drive}
	// Directory index.
	GetDrive(ctx context.Context, drive string) error
	// CreateDriveBarcodeLabelMedia POST /tape/drive/{drive}/barcode-label-media
	// Label media with barcodes from changer device
	CreateDriveBarcodeLabelMedia(ctx context.Context, drive string, params *CreateDriveBarcodeLabelMediaParams) (*CreateDriveBarcodeLabelMediaResponse, error)
	// ListDriveCartridgeMemory GET /tape/drive/{drive}/cartridge-memory
	// Read Cartridge Memory (Medium auxiliary memory attributes)
	ListDriveCartridgeMemory(ctx context.Context, drive string) (*ListDriveCartridgeMemoryResponse, error)
	// CreateDriveCatalog POST /tape/drive/{drive}/catalog
	// Scan media and record content
	CreateDriveCatalog(ctx context.Context, drive string, params *CreateDriveCatalogParams) (*CreateDriveCatalogResponse, error)
	// UpdateDriveClean PUT /tape/drive/{drive}/clean
	// Clean drive
	UpdateDriveClean(ctx context.Context, drive string) (*UpdateDriveCleanResponse, error)
	// CreateDriveEjectMedia POST /tape/drive/{drive}/eject-media
	// Eject/Unload drive media
	CreateDriveEjectMedia(ctx context.Context, drive string) (*CreateDriveEjectMediaResponse, error)
	// UpdateDriveExportMedia PUT /tape/drive/{drive}/export-media
	// Export media with specified label
	UpdateDriveExportMedia(ctx context.Context, drive string, params *UpdateDriveExportMediaParams) (*UpdateDriveExportMediaResponse, error)
	// CreateDriveFormatMedia POST /tape/drive/{drive}/format-media
	// Format media. Check for label-text if given (cancels if wrong media).
	CreateDriveFormatMedia(ctx context.Context, drive string, params *CreateDriveFormatMediaParams) (*CreateDriveFormatMediaResponse, error)
	// ListDriveInventory GET /tape/drive/{drive}/inventory
	// List known media labels (Changer Inventory)  Note: Only useful for drives with associated changer device.  This method queries the changer to get a list of media labels.  Note: This updates the media online status.
	ListDriveInventory(ctx context.Context, drive string) (*ListDriveInventoryResponse, error)
	// UpdateDriveInventory PUT /tape/drive/{drive}/inventory
	// Update inventory  Note: Only useful for drives with associated changer device.  This method queries the changer to get a list of media labels. It then loads any unknown media into the drive, reads the label, and store the result to the media database.  If `catalog` is true, also tries to restore the catalog from tape.  Note: This updates the media online status.
	UpdateDriveInventory(ctx context.Context, drive string, params *UpdateDriveInventoryParams) (*UpdateDriveInventoryResponse, error)
	// CreateDriveLabelMedia POST /tape/drive/{drive}/label-media
	// Label media  Write a new media label to the media in 'drive'. The media is assigned to the specified 'pool', or else to the free media pool.  Note: The media need to be empty (you may want to format it first).
	CreateDriveLabelMedia(ctx context.Context, drive string, params *CreateDriveLabelMediaParams) (*CreateDriveLabelMediaResponse, error)
	// CreateDriveLoadMedia POST /tape/drive/{drive}/load-media
	// Load media with specified label  Issue a media load request to the associated changer device.
	CreateDriveLoadMedia(ctx context.Context, drive string, params *CreateDriveLoadMediaParams) (*CreateDriveLoadMediaResponse, error)
	// CreateDriveLoadSlot POST /tape/drive/{drive}/load-slot
	// Load media from the specified slot  Issue a media load request to the associated changer device.
	CreateDriveLoadSlot(ctx context.Context, drive string, params *CreateDriveLoadSlotParams) error
	// ListDriveReadLabel GET /tape/drive/{drive}/read-label
	// Read media label (optionally inventorize media)
	ListDriveReadLabel(ctx context.Context, drive string, params *ListDriveReadLabelParams) (*ListDriveReadLabelResponse, error)
	// CreateDriveRestoreKey POST /tape/drive/{drive}/restore-key
	// Try to restore a tape encryption key
	CreateDriveRestoreKey(ctx context.Context, drive string, params *CreateDriveRestoreKeyParams) error
	// CreateDriveRewind POST /tape/drive/{drive}/rewind
	// Rewind tape
	CreateDriveRewind(ctx context.Context, drive string) (*CreateDriveRewindResponse, error)
	// ListDriveStatus GET /tape/drive/{drive}/status
	// Get drive/media status
	ListDriveStatus(ctx context.Context, drive string) (*ListDriveStatusResponse, error)
	// CreateDriveUnload POST /tape/drive/{drive}/unload
	// Unload media via changer
	CreateDriveUnload(ctx context.Context, drive string, params *CreateDriveUnloadParams) (*CreateDriveUnloadResponse, error)
	// ListDriveVolumeStatistics GET /tape/drive/{drive}/volume-statistics
	// Read Volume Statistics (SCSI log page 17h)
	ListDriveVolumeStatistics(ctx context.Context, drive string) (*ListDriveVolumeStatisticsResponse, error)
	// ListMedia GET /tape/media
	// Directory index.
	ListMedia(ctx context.Context) error
	// ListMediaContent GET /tape/media/content
	// List media content
	ListMediaContent(ctx context.Context, params *ListMediaContentParams) (*ListMediaContentResponse, error)
	// ListMediaDestroy GET /tape/media/destroy
	// Destroy media (completely remove from database)
	ListMediaDestroy(ctx context.Context, params *ListMediaDestroyParams) error
	// ListMediaList GET /tape/media/list
	// List pool media
	ListMediaList(ctx context.Context, params *ListMediaListParams) (*ListMediaListResponse, error)
	// GetMediaList GET /tape/media/list/{uuid}
	// Directory index.
	GetMediaList(ctx context.Context, uuid string) error
	// ListMediaListStatus GET /tape/media/list/{uuid}/status
	// Get current media status
	ListMediaListStatus(ctx context.Context, uuid string) error
	// CreateMediaListStatus POST /tape/media/list/{uuid}/status
	// Update media status (None, 'full', 'damaged' or 'retired')  It is not allowed to set status to 'writable' or 'unknown' (those are internally managed states).
	CreateMediaListStatus(ctx context.Context, uuid string, params *CreateMediaListStatusParams) error
	// ListMediaMediaSets GET /tape/media/media-sets
	// List Media sets
	ListMediaMediaSets(ctx context.Context) (*ListMediaMediaSetsResponse, error)
	// CreateMediaMove POST /tape/media/move
	// Change Tape location to vault (if given), or offline.
	CreateMediaMove(ctx context.Context, params *CreateMediaMoveParams) error
	// CreateRestore POST /tape/restore
	// Restore data from media-set. Namespaces will be automatically created if necessary.
	CreateRestore(ctx context.Context, params *CreateRestoreParams) (*CreateRestoreResponse, error)
	// ListScanChangers GET /tape/scan-changers
	// Scan for SCSI tape changers
	ListScanChangers(ctx context.Context) (*ListScanChangersResponse, error)
	// ListScanDrives GET /tape/scan-drives
	// Scan tape drives
	ListScanDrives(ctx context.Context) (*ListScanDrivesResponse, error)
}

// New constructs a Service backed by the given pkg/client.Client.
// The client owns authentication, TLS, retries, and logging; this
// service only translates between typed Go shapes and the raw client.
func New(c client.Client) Service {
	if c == nil {
		panic("tape: New called with nil client")
	}
	return &service{c: c}
}

type service struct {
	c client.Client
}

// ListTape implements Service.ListTape. GET /tape.
func (s *service) ListTape(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("tape.ListTape: ctx must not be nil")
	}
	path := "/tape"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("tape.ListTape: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("tape.ListTape: nil response from client")
	}
	_ = resp
	return nil
}

// ListBackupResponse mirrors the shape returned by GET /tape/backup.
type ListBackupResponse []json.RawMessage

// ListBackup implements Service.ListBackup. GET /tape/backup.
func (s *service) ListBackup(ctx context.Context) (*ListBackupResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.ListBackup: ctx must not be nil")
	}
	path := "/tape/backup"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.ListBackup: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.ListBackup: nil response from client")
	}
	if resp.Data == nil {
		out := ListBackupResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.ListBackup: re-marshal data: %w", err)
	}
	out := &ListBackupResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.ListBackup: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateBackupParams is the request payload for CreateBackup.
type CreateBackupParams struct {
	// Drive Drive Identifier.
	Drive string `json:"drive"`
	// EjectMedia Eject media upon job completion.
	EjectMedia *bool `json:"eject-media,omitempty"`
	// ExportMediaSet Export media set upon job completion.
	ExportMediaSet *bool `json:"export-media-set,omitempty"`
	// ForceMediaSet Ignore the allocation policy and start a new media-set.
	ForceMediaSet *bool `json:"force-media-set,omitempty"`
	// GroupFilter List of group filters.
	GroupFilter []string `json:"group-filter,omitempty"`
	// LatestOnly Backup latest snapshots only.
	LatestOnly *bool `json:"latest-only,omitempty"`
	// MaxDepth How many levels of namespaces should be operated on (0 == no recursion)
	MaxDepth *int64 `json:"max-depth,omitempty"`
	// NotificationMode Configure how notifications for this datastore should be sent. `legacy-sendmail` sends email notifications to the user configured in `notify-user` via the system's `sendmail` executable. `notification-system` emits matchable notification events to the notification system.
	NotificationMode *string `json:"notification-mode,omitempty"`
	// NotifyUser User ID
	NotifyUser *string `json:"notify-user,omitempty"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
	// Pool Media pool name.
	Pool string `json:"pool"`
	// Store Datastore name.
	Store string `json:"store"`
	// WorkerThreads The number of threads to use for the tape backup job.
	WorkerThreads *int64 `json:"worker-threads,omitempty"`
}

// CreateBackupResponse is the raw JSON returned by POST /tape/backup.
type CreateBackupResponse = json.RawMessage

// CreateBackup implements Service.CreateBackup. POST /tape/backup.
func (s *service) CreateBackup(ctx context.Context, params *CreateBackupParams) (*CreateBackupResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.CreateBackup: ctx must not be nil")
	}
	path := "/tape/backup"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateBackup: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateBackup: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateBackup: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.CreateBackup: nil response from client")
	}
	if resp.Data == nil {
		out := CreateBackupResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateBackup: re-marshal data: %w", err)
	}
	out := &CreateBackupResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateBackup: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateBackup2 implements Service.CreateBackup2. POST /tape/backup/{id}.
func (s *service) CreateBackup2(ctx context.Context, id string) error {
	if ctx == nil {
		return fmt.Errorf("tape.CreateBackup2: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/backup/%s", url.PathEscape(id))
	var body map[string]interface{}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("tape.CreateBackup2: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("tape.CreateBackup2: nil response from client")
	}
	_ = resp
	return nil
}

// ListChangerResponse mirrors the shape returned by GET /tape/changer.
type ListChangerResponse []json.RawMessage

// ListChanger implements Service.ListChanger. GET /tape/changer.
func (s *service) ListChanger(ctx context.Context) (*ListChangerResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.ListChanger: ctx must not be nil")
	}
	path := "/tape/changer"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.ListChanger: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.ListChanger: nil response from client")
	}
	if resp.Data == nil {
		out := ListChangerResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.ListChanger: re-marshal data: %w", err)
	}
	out := &ListChangerResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.ListChanger: unmarshal data: %w", err)
	}
	return out, nil
}

// GetChanger implements Service.GetChanger. GET /tape/changer/{name}.
func (s *service) GetChanger(ctx context.Context, name string) error {
	if ctx == nil {
		return fmt.Errorf("tape.GetChanger: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/changer/%s", url.PathEscape(name))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("tape.GetChanger: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("tape.GetChanger: nil response from client")
	}
	_ = resp
	return nil
}

// ListChangerStatusParams is the request payload for ListChangerStatus.
type ListChangerStatusParams struct {
	// Cache Use cached value.
	Cache *bool `json:"cache,omitempty"`
}

// ListChangerStatusResponse mirrors the shape returned by GET /tape/changer/{name}/status.
type ListChangerStatusResponse []json.RawMessage

// ListChangerStatus implements Service.ListChangerStatus. GET /tape/changer/{name}/status.
func (s *service) ListChangerStatus(ctx context.Context, name string, params *ListChangerStatusParams) (*ListChangerStatusResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.ListChangerStatus: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/changer/%s/status", url.PathEscape(name))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("tape.ListChangerStatus: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("tape.ListChangerStatus: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.ListChangerStatus: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.ListChangerStatus: nil response from client")
	}
	if resp.Data == nil {
		out := ListChangerStatusResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.ListChangerStatus: re-marshal data: %w", err)
	}
	out := &ListChangerStatusResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.ListChangerStatus: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateChangerTransferParams is the request payload for CreateChangerTransfer.
type CreateChangerTransferParams struct {
	// From Source slot number
	From int64 `json:"from"`
	// To Destination slot number
	To int64 `json:"to"`
}

// CreateChangerTransfer implements Service.CreateChangerTransfer. POST /tape/changer/{name}/transfer.
func (s *service) CreateChangerTransfer(ctx context.Context, name string, params *CreateChangerTransferParams) error {
	if ctx == nil {
		return fmt.Errorf("tape.CreateChangerTransfer: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/changer/%s/transfer", url.PathEscape(name))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("tape.CreateChangerTransfer: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("tape.CreateChangerTransfer: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("tape.CreateChangerTransfer: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("tape.CreateChangerTransfer: nil response from client")
	}
	_ = resp
	return nil
}

// ListDriveParams is the request payload for ListDrive.
type ListDriveParams struct {
	// Changer Tape Changer Identifier.
	Changer *string `json:"changer,omitempty"`
	// QueryActivity If true, queries and returns the drive activity for each drive.
	QueryActivity *bool `json:"query-activity,omitempty"`
}

// ListDriveResponse mirrors the shape returned by GET /tape/drive.
type ListDriveResponse []json.RawMessage

// ListDrive implements Service.ListDrive. GET /tape/drive.
func (s *service) ListDrive(ctx context.Context, params *ListDriveParams) (*ListDriveResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.ListDrive: ctx must not be nil")
	}
	path := "/tape/drive"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("tape.ListDrive: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("tape.ListDrive: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDrive: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.ListDrive: nil response from client")
	}
	if resp.Data == nil {
		out := ListDriveResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDrive: re-marshal data: %w", err)
	}
	out := &ListDriveResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDrive: unmarshal data: %w", err)
	}
	return out, nil
}

// GetDrive implements Service.GetDrive. GET /tape/drive/{drive}.
func (s *service) GetDrive(ctx context.Context, drive string) error {
	if ctx == nil {
		return fmt.Errorf("tape.GetDrive: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s", url.PathEscape(drive))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("tape.GetDrive: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("tape.GetDrive: nil response from client")
	}
	_ = resp
	return nil
}

// CreateDriveBarcodeLabelMediaParams is the request payload for CreateDriveBarcodeLabelMedia.
type CreateDriveBarcodeLabelMediaParams struct {
	// Pool Media pool name.
	Pool *string `json:"pool,omitempty"`
}

// CreateDriveBarcodeLabelMediaResponse is the raw JSON returned by POST /tape/drive/{drive}/barcode-label-media.
type CreateDriveBarcodeLabelMediaResponse = json.RawMessage

// CreateDriveBarcodeLabelMedia implements Service.CreateDriveBarcodeLabelMedia. POST /tape/drive/{drive}/barcode-label-media.
func (s *service) CreateDriveBarcodeLabelMedia(ctx context.Context, drive string, params *CreateDriveBarcodeLabelMediaParams) (*CreateDriveBarcodeLabelMediaResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.CreateDriveBarcodeLabelMedia: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/barcode-label-media", url.PathEscape(drive))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateDriveBarcodeLabelMedia: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateDriveBarcodeLabelMedia: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveBarcodeLabelMedia: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.CreateDriveBarcodeLabelMedia: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDriveBarcodeLabelMediaResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveBarcodeLabelMedia: re-marshal data: %w", err)
	}
	out := &CreateDriveBarcodeLabelMediaResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveBarcodeLabelMedia: unmarshal data: %w", err)
	}
	return out, nil
}

// ListDriveCartridgeMemoryResponse mirrors the shape returned by GET /tape/drive/{drive}/cartridge-memory.
type ListDriveCartridgeMemoryResponse []json.RawMessage

// ListDriveCartridgeMemory implements Service.ListDriveCartridgeMemory. GET /tape/drive/{drive}/cartridge-memory.
func (s *service) ListDriveCartridgeMemory(ctx context.Context, drive string) (*ListDriveCartridgeMemoryResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.ListDriveCartridgeMemory: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/cartridge-memory", url.PathEscape(drive))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDriveCartridgeMemory: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.ListDriveCartridgeMemory: nil response from client")
	}
	if resp.Data == nil {
		out := ListDriveCartridgeMemoryResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDriveCartridgeMemory: re-marshal data: %w", err)
	}
	out := &ListDriveCartridgeMemoryResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDriveCartridgeMemory: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDriveCatalogParams is the request payload for CreateDriveCatalog.
type CreateDriveCatalogParams struct {
	// Force Force overriding existing index.
	Force *bool `json:"force,omitempty"`
	// Scan Re-read the whole tape to reconstruct the catalog instead of restoring saved versions.
	Scan *bool `json:"scan,omitempty"`
	// Verbose Verbose mode - log all found chunks.
	Verbose *bool `json:"verbose,omitempty"`
}

// CreateDriveCatalogResponse is the raw JSON returned by POST /tape/drive/{drive}/catalog.
type CreateDriveCatalogResponse = json.RawMessage

// CreateDriveCatalog implements Service.CreateDriveCatalog. POST /tape/drive/{drive}/catalog.
func (s *service) CreateDriveCatalog(ctx context.Context, drive string, params *CreateDriveCatalogParams) (*CreateDriveCatalogResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.CreateDriveCatalog: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/catalog", url.PathEscape(drive))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateDriveCatalog: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateDriveCatalog: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveCatalog: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.CreateDriveCatalog: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDriveCatalogResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveCatalog: re-marshal data: %w", err)
	}
	out := &CreateDriveCatalogResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveCatalog: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateDriveCleanResponse is the raw JSON returned by PUT /tape/drive/{drive}/clean.
type UpdateDriveCleanResponse = json.RawMessage

// UpdateDriveClean implements Service.UpdateDriveClean. PUT /tape/drive/{drive}/clean.
func (s *service) UpdateDriveClean(ctx context.Context, drive string) (*UpdateDriveCleanResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.UpdateDriveClean: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/clean", url.PathEscape(drive))
	var body map[string]interface{}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.UpdateDriveClean: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.UpdateDriveClean: nil response from client")
	}
	if resp.Data == nil {
		out := UpdateDriveCleanResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.UpdateDriveClean: re-marshal data: %w", err)
	}
	out := &UpdateDriveCleanResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.UpdateDriveClean: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDriveEjectMediaResponse is the raw JSON returned by POST /tape/drive/{drive}/eject-media.
type CreateDriveEjectMediaResponse = json.RawMessage

// CreateDriveEjectMedia implements Service.CreateDriveEjectMedia. POST /tape/drive/{drive}/eject-media.
func (s *service) CreateDriveEjectMedia(ctx context.Context, drive string) (*CreateDriveEjectMediaResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.CreateDriveEjectMedia: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/eject-media", url.PathEscape(drive))
	var body map[string]interface{}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveEjectMedia: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.CreateDriveEjectMedia: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDriveEjectMediaResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveEjectMedia: re-marshal data: %w", err)
	}
	out := &CreateDriveEjectMediaResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveEjectMedia: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateDriveExportMediaParams is the request payload for UpdateDriveExportMedia.
type UpdateDriveExportMediaParams struct {
	// LabelText Media Label/Barcode.
	LabelText string `json:"label-text"`
}

// UpdateDriveExportMediaResponse is the raw JSON returned by PUT /tape/drive/{drive}/export-media.
type UpdateDriveExportMediaResponse = json.RawMessage

// UpdateDriveExportMedia implements Service.UpdateDriveExportMedia. PUT /tape/drive/{drive}/export-media.
func (s *service) UpdateDriveExportMedia(ctx context.Context, drive string, params *UpdateDriveExportMediaParams) (*UpdateDriveExportMediaResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.UpdateDriveExportMedia: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/export-media", url.PathEscape(drive))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("tape.UpdateDriveExportMedia: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("tape.UpdateDriveExportMedia: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.UpdateDriveExportMedia: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.UpdateDriveExportMedia: nil response from client")
	}
	if resp.Data == nil {
		out := UpdateDriveExportMediaResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.UpdateDriveExportMedia: re-marshal data: %w", err)
	}
	out := &UpdateDriveExportMediaResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.UpdateDriveExportMedia: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDriveFormatMediaParams is the request payload for CreateDriveFormatMedia.
type CreateDriveFormatMediaParams struct {
	// Fast Use fast erase.
	Fast *bool `json:"fast,omitempty"`
	// LabelText Media Label/Barcode.
	LabelText *string `json:"label-text,omitempty"`
	// LoadBarcode Media Label/Barcode.
	LoadBarcode *string `json:"load-barcode,omitempty"`
}

// CreateDriveFormatMediaResponse is the raw JSON returned by POST /tape/drive/{drive}/format-media.
type CreateDriveFormatMediaResponse = json.RawMessage

// CreateDriveFormatMedia implements Service.CreateDriveFormatMedia. POST /tape/drive/{drive}/format-media.
func (s *service) CreateDriveFormatMedia(ctx context.Context, drive string, params *CreateDriveFormatMediaParams) (*CreateDriveFormatMediaResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.CreateDriveFormatMedia: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/format-media", url.PathEscape(drive))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateDriveFormatMedia: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateDriveFormatMedia: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveFormatMedia: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.CreateDriveFormatMedia: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDriveFormatMediaResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveFormatMedia: re-marshal data: %w", err)
	}
	out := &CreateDriveFormatMediaResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveFormatMedia: unmarshal data: %w", err)
	}
	return out, nil
}

// ListDriveInventoryResponse mirrors the shape returned by GET /tape/drive/{drive}/inventory.
type ListDriveInventoryResponse []json.RawMessage

// ListDriveInventory implements Service.ListDriveInventory. GET /tape/drive/{drive}/inventory.
func (s *service) ListDriveInventory(ctx context.Context, drive string) (*ListDriveInventoryResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.ListDriveInventory: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/inventory", url.PathEscape(drive))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDriveInventory: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.ListDriveInventory: nil response from client")
	}
	if resp.Data == nil {
		out := ListDriveInventoryResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDriveInventory: re-marshal data: %w", err)
	}
	out := &ListDriveInventoryResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDriveInventory: unmarshal data: %w", err)
	}
	return out, nil
}

// UpdateDriveInventoryParams is the request payload for UpdateDriveInventory.
type UpdateDriveInventoryParams struct {
	// Catalog Restore the catalog from tape.
	Catalog *bool `json:"catalog,omitempty"`
	// ReadAllLabels Load all tapes and try read labels (even if already inventoried)
	ReadAllLabels *bool `json:"read-all-labels,omitempty"`
}

// UpdateDriveInventoryResponse is the raw JSON returned by PUT /tape/drive/{drive}/inventory.
type UpdateDriveInventoryResponse = json.RawMessage

// UpdateDriveInventory implements Service.UpdateDriveInventory. PUT /tape/drive/{drive}/inventory.
func (s *service) UpdateDriveInventory(ctx context.Context, drive string, params *UpdateDriveInventoryParams) (*UpdateDriveInventoryResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.UpdateDriveInventory: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/inventory", url.PathEscape(drive))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("tape.UpdateDriveInventory: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("tape.UpdateDriveInventory: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.UpdateDriveInventory: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.UpdateDriveInventory: nil response from client")
	}
	if resp.Data == nil {
		out := UpdateDriveInventoryResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.UpdateDriveInventory: re-marshal data: %w", err)
	}
	out := &UpdateDriveInventoryResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.UpdateDriveInventory: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDriveLabelMediaParams is the request payload for CreateDriveLabelMedia.
type CreateDriveLabelMediaParams struct {
	// LabelText Media Label/Barcode.
	LabelText string `json:"label-text"`
	// Pool Media pool name.
	Pool *string `json:"pool,omitempty"`
}

// CreateDriveLabelMediaResponse is the raw JSON returned by POST /tape/drive/{drive}/label-media.
type CreateDriveLabelMediaResponse = json.RawMessage

// CreateDriveLabelMedia implements Service.CreateDriveLabelMedia. POST /tape/drive/{drive}/label-media.
func (s *service) CreateDriveLabelMedia(ctx context.Context, drive string, params *CreateDriveLabelMediaParams) (*CreateDriveLabelMediaResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.CreateDriveLabelMedia: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/label-media", url.PathEscape(drive))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateDriveLabelMedia: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateDriveLabelMedia: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveLabelMedia: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.CreateDriveLabelMedia: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDriveLabelMediaResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveLabelMedia: re-marshal data: %w", err)
	}
	out := &CreateDriveLabelMediaResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveLabelMedia: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDriveLoadMediaParams is the request payload for CreateDriveLoadMedia.
type CreateDriveLoadMediaParams struct {
	// LabelText Media Label/Barcode.
	LabelText string `json:"label-text"`
}

// CreateDriveLoadMediaResponse is the raw JSON returned by POST /tape/drive/{drive}/load-media.
type CreateDriveLoadMediaResponse = json.RawMessage

// CreateDriveLoadMedia implements Service.CreateDriveLoadMedia. POST /tape/drive/{drive}/load-media.
func (s *service) CreateDriveLoadMedia(ctx context.Context, drive string, params *CreateDriveLoadMediaParams) (*CreateDriveLoadMediaResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.CreateDriveLoadMedia: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/load-media", url.PathEscape(drive))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateDriveLoadMedia: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateDriveLoadMedia: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveLoadMedia: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.CreateDriveLoadMedia: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDriveLoadMediaResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveLoadMedia: re-marshal data: %w", err)
	}
	out := &CreateDriveLoadMediaResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveLoadMedia: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDriveLoadSlotParams is the request payload for CreateDriveLoadSlot.
type CreateDriveLoadSlotParams struct {
	// SourceSlot Source slot number.
	SourceSlot int64 `json:"source-slot"`
}

// CreateDriveLoadSlot implements Service.CreateDriveLoadSlot. POST /tape/drive/{drive}/load-slot.
func (s *service) CreateDriveLoadSlot(ctx context.Context, drive string, params *CreateDriveLoadSlotParams) error {
	if ctx == nil {
		return fmt.Errorf("tape.CreateDriveLoadSlot: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/load-slot", url.PathEscape(drive))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("tape.CreateDriveLoadSlot: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("tape.CreateDriveLoadSlot: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("tape.CreateDriveLoadSlot: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("tape.CreateDriveLoadSlot: nil response from client")
	}
	_ = resp
	return nil
}

// ListDriveReadLabelParams is the request payload for ListDriveReadLabel.
type ListDriveReadLabelParams struct {
	// Inventorize Inventorize media
	Inventorize *bool `json:"inventorize,omitempty"`
}

// ListDriveReadLabelResponse mirrors the shape returned by GET /tape/drive/{drive}/read-label.
type ListDriveReadLabelResponse struct {
	// Ctime Creation time stamp
	Ctime client.PVEInt `json:"ctime"`
	// EncryptionKeyFingerprint Encryption key fingerprint
	EncryptionKeyFingerprint *string `json:"encryption-key-fingerprint,omitempty"`
	// LabelText Media label text (or Barcode)
	LabelText string `json:"label-text"`
	// MediaSetCtime MediaSet Creation time stamp
	MediaSetCtime *client.PVEInt `json:"media-set-ctime,omitempty"`
	// MediaSetUuid MediaSet Uuid (We use the all-zero Uuid to reserve an empty media for a specific pool).
	MediaSetUuid *string `json:"media-set-uuid,omitempty"`
	// Pool MediaSet Pool
	Pool *string `json:"pool,omitempty"`
	// SeqNr MediaSet media sequence number
	SeqNr *client.PVEInt `json:"seq-nr,omitempty"`
	// Uuid Media Uuid.
	Uuid string `json:"uuid"`
}

// ListDriveReadLabel implements Service.ListDriveReadLabel. GET /tape/drive/{drive}/read-label.
func (s *service) ListDriveReadLabel(ctx context.Context, drive string, params *ListDriveReadLabelParams) (*ListDriveReadLabelResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.ListDriveReadLabel: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/read-label", url.PathEscape(drive))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("tape.ListDriveReadLabel: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("tape.ListDriveReadLabel: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDriveReadLabel: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.ListDriveReadLabel: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("tape.ListDriveReadLabel: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDriveReadLabel: re-marshal data: %w", err)
	}
	out := &ListDriveReadLabelResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDriveReadLabel: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDriveRestoreKeyParams is the request payload for CreateDriveRestoreKey.
type CreateDriveRestoreKeyParams struct {
	// Password The password the key was encrypted with.
	Password string `json:"password"`
}

// CreateDriveRestoreKey implements Service.CreateDriveRestoreKey. POST /tape/drive/{drive}/restore-key.
func (s *service) CreateDriveRestoreKey(ctx context.Context, drive string, params *CreateDriveRestoreKeyParams) error {
	if ctx == nil {
		return fmt.Errorf("tape.CreateDriveRestoreKey: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/restore-key", url.PathEscape(drive))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("tape.CreateDriveRestoreKey: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("tape.CreateDriveRestoreKey: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("tape.CreateDriveRestoreKey: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("tape.CreateDriveRestoreKey: nil response from client")
	}
	_ = resp
	return nil
}

// CreateDriveRewindResponse is the raw JSON returned by POST /tape/drive/{drive}/rewind.
type CreateDriveRewindResponse = json.RawMessage

// CreateDriveRewind implements Service.CreateDriveRewind. POST /tape/drive/{drive}/rewind.
func (s *service) CreateDriveRewind(ctx context.Context, drive string) (*CreateDriveRewindResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.CreateDriveRewind: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/rewind", url.PathEscape(drive))
	var body map[string]interface{}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveRewind: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.CreateDriveRewind: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDriveRewindResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveRewind: re-marshal data: %w", err)
	}
	out := &CreateDriveRewindResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveRewind: unmarshal data: %w", err)
	}
	return out, nil
}

// ListDriveStatusResponse mirrors the shape returned by GET /tape/drive/{drive}/status.
type ListDriveStatusResponse struct {
	// AlertFlags Tape Alert Flags
	AlertFlags *string `json:"alert-flags,omitempty"`
	// BlockNumber Current block number
	BlockNumber *client.PVEInt `json:"block-number,omitempty"`
	// Blocksize Block size (0 is variable size)
	Blocksize client.PVEInt `json:"blocksize"`
	// BufferMode Drive buffer mode
	BufferMode client.PVEInt `json:"buffer-mode"`
	// BytesRead Total Bytes Read in Medium Life
	BytesRead *client.PVEInt `json:"bytes-read,omitempty"`
	// BytesWritten Total Bytes Written in Medium Life
	BytesWritten *client.PVEInt `json:"bytes-written,omitempty"`
	// Compression Compression enabled
	Compression client.PVEBool `json:"compression"`
	// Density The density of a tape medium, derived from the LTO version.
	Density *string `json:"density,omitempty"`
	// DriveActivity The DT Device Activity from DT Device Status LP page
	DriveActivity *string `json:"drive-activity,omitempty"`
	// FileNumber Current file number
	FileNumber *client.PVEInt `json:"file-number,omitempty"`
	// Manufactured Medium Manufacture Date (epoch)
	Manufactured *client.PVEInt `json:"manufactured,omitempty"`
	// MediumPasses Count of the total number of times the medium has passed over the head.
	MediumPasses *client.PVEInt `json:"medium-passes,omitempty"`
	// MediumWearout Estimated tape wearout factor (assuming max. 16000 end-to-end passes)
	MediumWearout *client.PVEFloat `json:"medium-wearout,omitempty"`
	// Product Product
	Product string `json:"product"`
	// Revision Revision
	Revision string `json:"revision"`
	// Vendor Vendor
	Vendor string `json:"vendor"`
	// VolumeMounts Number of mounts for the current volume (i.e., Thread Count)
	VolumeMounts *client.PVEInt `json:"volume-mounts,omitempty"`
	// WriteProtect Media is write protected
	WriteProtect *client.PVEBool `json:"write-protect,omitempty"`
}

// ListDriveStatus implements Service.ListDriveStatus. GET /tape/drive/{drive}/status.
func (s *service) ListDriveStatus(ctx context.Context, drive string) (*ListDriveStatusResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.ListDriveStatus: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/status", url.PathEscape(drive))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDriveStatus: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.ListDriveStatus: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("tape.ListDriveStatus: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDriveStatus: re-marshal data: %w", err)
	}
	out := &ListDriveStatusResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDriveStatus: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDriveUnloadParams is the request payload for CreateDriveUnload.
type CreateDriveUnloadParams struct {
	// TargetSlot Target slot number. If omitted, defaults to the slot that the drive was loaded from.
	TargetSlot *int64 `json:"target-slot,omitempty"`
}

// CreateDriveUnloadResponse is the raw JSON returned by POST /tape/drive/{drive}/unload.
type CreateDriveUnloadResponse = json.RawMessage

// CreateDriveUnload implements Service.CreateDriveUnload. POST /tape/drive/{drive}/unload.
func (s *service) CreateDriveUnload(ctx context.Context, drive string, params *CreateDriveUnloadParams) (*CreateDriveUnloadResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.CreateDriveUnload: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/unload", url.PathEscape(drive))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateDriveUnload: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateDriveUnload: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveUnload: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.CreateDriveUnload: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDriveUnloadResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveUnload: re-marshal data: %w", err)
	}
	out := &CreateDriveUnloadResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateDriveUnload: unmarshal data: %w", err)
	}
	return out, nil
}

// ListDriveVolumeStatisticsResponse mirrors the shape returned by GET /tape/drive/{drive}/volume-statistics.
type ListDriveVolumeStatisticsResponse struct {
	// BeginningOfMediumPasses Beginning of medium passes
	BeginningOfMediumPasses client.PVEInt `json:"beginning-of-medium-passes"`
	// LastLoadReadCompressionRatio Last load read compression ratio
	LastLoadReadCompressionRatio client.PVEInt `json:"last-load-read-compression-ratio"`
	// LastLoadWriteCompressionRatio Last load write compression ratio
	LastLoadWriteCompressionRatio client.PVEInt `json:"last-load-write-compression-ratio"`
	// LastMountBytesRead Last mount bytes read
	LastMountBytesRead client.PVEInt `json:"last-mount-bytes-read"`
	// LastMountBytesWritten Last mount bytes written
	LastMountBytesWritten client.PVEInt `json:"last-mount-bytes-written"`
	// LastMountUnrecoveredReadErrors Last mount unrecovered read errors
	LastMountUnrecoveredReadErrors client.PVEInt `json:"last-mount-unrecovered-read-errors"`
	// LastMountUnrecoveredWriteErrors Last mount unrecovered write errors
	LastMountUnrecoveredWriteErrors client.PVEInt `json:"last-mount-unrecovered-write-errors"`
	// LifetimeBytesRead Lifetime bytes read
	LifetimeBytesRead client.PVEInt `json:"lifetime-bytes-read"`
	// LifetimeBytesWritten Lifetime bytes written
	LifetimeBytesWritten client.PVEInt `json:"lifetime-bytes-written"`
	// MediumMountTime Medium mount time
	MediumMountTime client.PVEInt `json:"medium-mount-time"`
	// MediumReadyTime Medium ready time
	MediumReadyTime client.PVEInt `json:"medium-ready-time"`
	// MiddleOfTapePasses Middle of medium passes
	MiddleOfTapePasses client.PVEInt `json:"middle-of-tape-passes"`
	// Serial Volume serial number
	Serial string `json:"serial"`
	// TotalNativeCapacity Total native capacity
	TotalNativeCapacity client.PVEInt `json:"total-native-capacity"`
	// TotalUsedNativeCapacity Total used native capacity
	TotalUsedNativeCapacity client.PVEInt `json:"total-used-native-capacity"`
	// VolumeDatasetsRead Total datasets read
	VolumeDatasetsRead client.PVEInt `json:"volume-datasets-read"`
	// VolumeDatasetsWritten Total data sets written
	VolumeDatasetsWritten client.PVEInt `json:"volume-datasets-written"`
	// VolumeMounts Volume mounts (thread count)
	VolumeMounts client.PVEInt `json:"volume-mounts"`
	// VolumeRecoveredReadErrors Total read retries
	VolumeRecoveredReadErrors client.PVEInt `json:"volume-recovered-read-errors"`
	// VolumeRecoveredWriteDataErrors Write retries
	VolumeRecoveredWriteDataErrors client.PVEInt `json:"volume-recovered-write-data-errors"`
	// VolumeUnrecoveredReadErrors Total unrecovered read errors
	VolumeUnrecoveredReadErrors client.PVEInt `json:"volume-unrecovered-read-errors"`
	// VolumeUnrecoveredWriteDataErrors Total unrecovered write errors
	VolumeUnrecoveredWriteDataErrors client.PVEInt `json:"volume-unrecovered-write-data-errors"`
	// VolumeUnrecoveredWriteServoErrors Total fatal suspended writes
	VolumeUnrecoveredWriteServoErrors client.PVEInt `json:"volume-unrecovered-write-servo-errors"`
	// VolumeWriteServoErrors Total suspended writes
	VolumeWriteServoErrors client.PVEInt `json:"volume-write-servo-errors"`
	// Worm Volume is WORM
	Worm client.PVEBool `json:"worm"`
	// WriteProtect Write protect
	WriteProtect client.PVEBool `json:"write-protect"`
}

// ListDriveVolumeStatistics implements Service.ListDriveVolumeStatistics. GET /tape/drive/{drive}/volume-statistics.
func (s *service) ListDriveVolumeStatistics(ctx context.Context, drive string) (*ListDriveVolumeStatisticsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.ListDriveVolumeStatistics: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/drive/%s/volume-statistics", url.PathEscape(drive))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDriveVolumeStatistics: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.ListDriveVolumeStatistics: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("tape.ListDriveVolumeStatistics: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDriveVolumeStatistics: re-marshal data: %w", err)
	}
	out := &ListDriveVolumeStatisticsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.ListDriveVolumeStatistics: unmarshal data: %w", err)
	}
	return out, nil
}

// ListMedia implements Service.ListMedia. GET /tape/media.
func (s *service) ListMedia(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("tape.ListMedia: ctx must not be nil")
	}
	path := "/tape/media"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("tape.ListMedia: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("tape.ListMedia: nil response from client")
	}
	_ = resp
	return nil
}

// ListMediaContentParams is the request payload for ListMediaContent.
type ListMediaContentParams struct {
	// BackupId Backup ID.
	BackupId *string `json:"backup-id,omitempty"`
	// BackupType Backup types.
	BackupType *string `json:"backup-type,omitempty"`
	// LabelText Media Label/Barcode.
	LabelText *string `json:"label-text,omitempty"`
	// Media Media Uuid.
	Media *string `json:"media,omitempty"`
	// MediaSet MediaSet Uuid (We use the all-zero Uuid to reserve an empty media for a specific pool).
	MediaSet *string `json:"media-set,omitempty"`
	// Pool Media pool name.
	Pool *string `json:"pool,omitempty"`
}

// ListMediaContentResponse mirrors the shape returned by GET /tape/media/content.
type ListMediaContentResponse []json.RawMessage

// ListMediaContent implements Service.ListMediaContent. GET /tape/media/content.
func (s *service) ListMediaContent(ctx context.Context, params *ListMediaContentParams) (*ListMediaContentResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.ListMediaContent: ctx must not be nil")
	}
	path := "/tape/media/content"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("tape.ListMediaContent: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("tape.ListMediaContent: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.ListMediaContent: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.ListMediaContent: nil response from client")
	}
	if resp.Data == nil {
		out := ListMediaContentResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.ListMediaContent: re-marshal data: %w", err)
	}
	out := &ListMediaContentResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.ListMediaContent: unmarshal data: %w", err)
	}
	return out, nil
}

// ListMediaDestroyParams is the request payload for ListMediaDestroy.
type ListMediaDestroyParams struct {
	// Force Force removal (even if media is used in a media set).
	Force *bool `json:"force,omitempty"`
	// LabelText Media Label/Barcode.
	LabelText *string `json:"label-text,omitempty"`
	// Uuid Media Uuid.
	Uuid *string `json:"uuid,omitempty"`
}

// ListMediaDestroy implements Service.ListMediaDestroy. GET /tape/media/destroy.
func (s *service) ListMediaDestroy(ctx context.Context, params *ListMediaDestroyParams) error {
	if ctx == nil {
		return fmt.Errorf("tape.ListMediaDestroy: ctx must not be nil")
	}
	path := "/tape/media/destroy"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("tape.ListMediaDestroy: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("tape.ListMediaDestroy: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("tape.ListMediaDestroy: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("tape.ListMediaDestroy: nil response from client")
	}
	_ = resp
	return nil
}

// ListMediaListParams is the request payload for ListMediaList.
type ListMediaListParams struct {
	// Pool Media pool name.
	Pool *string `json:"pool,omitempty"`
	// UpdateStatus Try to update tape library status (check what tapes are online).
	UpdateStatus *bool `json:"update-status,omitempty"`
	// UpdateStatusChanger Tape Changer Identifier.
	UpdateStatusChanger *string `json:"update-status-changer,omitempty"`
}

// ListMediaListResponse mirrors the shape returned by GET /tape/media/list.
type ListMediaListResponse []json.RawMessage

// ListMediaList implements Service.ListMediaList. GET /tape/media/list.
func (s *service) ListMediaList(ctx context.Context, params *ListMediaListParams) (*ListMediaListResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.ListMediaList: ctx must not be nil")
	}
	path := "/tape/media/list"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("tape.ListMediaList: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("tape.ListMediaList: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.ListMediaList: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.ListMediaList: nil response from client")
	}
	if resp.Data == nil {
		out := ListMediaListResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.ListMediaList: re-marshal data: %w", err)
	}
	out := &ListMediaListResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.ListMediaList: unmarshal data: %w", err)
	}
	return out, nil
}

// GetMediaList implements Service.GetMediaList. GET /tape/media/list/{uuid}.
func (s *service) GetMediaList(ctx context.Context, uuid string) error {
	if ctx == nil {
		return fmt.Errorf("tape.GetMediaList: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/media/list/%s", url.PathEscape(uuid))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("tape.GetMediaList: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("tape.GetMediaList: nil response from client")
	}
	_ = resp
	return nil
}

// ListMediaListStatus implements Service.ListMediaListStatus. GET /tape/media/list/{uuid}/status.
func (s *service) ListMediaListStatus(ctx context.Context, uuid string) error {
	if ctx == nil {
		return fmt.Errorf("tape.ListMediaListStatus: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/media/list/%s/status", url.PathEscape(uuid))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("tape.ListMediaListStatus: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("tape.ListMediaListStatus: nil response from client")
	}
	_ = resp
	return nil
}

// CreateMediaListStatusParams is the request payload for CreateMediaListStatus.
type CreateMediaListStatusParams struct {
	// Status Media status Media Status
	Status *string `json:"status,omitempty"`
}

// CreateMediaListStatus implements Service.CreateMediaListStatus. POST /tape/media/list/{uuid}/status.
func (s *service) CreateMediaListStatus(ctx context.Context, uuid string, params *CreateMediaListStatusParams) error {
	if ctx == nil {
		return fmt.Errorf("tape.CreateMediaListStatus: ctx must not be nil")
	}
	path := fmt.Sprintf("/tape/media/list/%s/status", url.PathEscape(uuid))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("tape.CreateMediaListStatus: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("tape.CreateMediaListStatus: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("tape.CreateMediaListStatus: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("tape.CreateMediaListStatus: nil response from client")
	}
	_ = resp
	return nil
}

// ListMediaMediaSetsResponse mirrors the shape returned by GET /tape/media/media-sets.
type ListMediaMediaSetsResponse []json.RawMessage

// ListMediaMediaSets implements Service.ListMediaMediaSets. GET /tape/media/media-sets.
func (s *service) ListMediaMediaSets(ctx context.Context) (*ListMediaMediaSetsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.ListMediaMediaSets: ctx must not be nil")
	}
	path := "/tape/media/media-sets"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.ListMediaMediaSets: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.ListMediaMediaSets: nil response from client")
	}
	if resp.Data == nil {
		out := ListMediaMediaSetsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.ListMediaMediaSets: re-marshal data: %w", err)
	}
	out := &ListMediaMediaSetsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.ListMediaMediaSets: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateMediaMoveParams is the request payload for CreateMediaMove.
type CreateMediaMoveParams struct {
	// LabelText Media Label/Barcode.
	LabelText *string `json:"label-text,omitempty"`
	// Uuid Media Uuid.
	Uuid *string `json:"uuid,omitempty"`
	// VaultName Vault name.
	VaultName *string `json:"vault-name,omitempty"`
}

// CreateMediaMove implements Service.CreateMediaMove. POST /tape/media/move.
func (s *service) CreateMediaMove(ctx context.Context, params *CreateMediaMoveParams) error {
	if ctx == nil {
		return fmt.Errorf("tape.CreateMediaMove: ctx must not be nil")
	}
	path := "/tape/media/move"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("tape.CreateMediaMove: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("tape.CreateMediaMove: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("tape.CreateMediaMove: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("tape.CreateMediaMove: nil response from client")
	}
	_ = resp
	return nil
}

// CreateRestoreParams is the request payload for CreateRestore.
type CreateRestoreParams struct {
	// Drive Drive Identifier.
	Drive string `json:"drive"`
	// MediaSet Media set UUID.
	MediaSet string `json:"media-set"`
	// Namespaces List of namespace to restore.
	Namespaces []string `json:"namespaces,omitempty"`
	// NotificationMode Configure how notifications for this datastore should be sent. `legacy-sendmail` sends email notifications to the user configured in `notify-user` via the system's `sendmail` executable. `notification-system` emits matchable notification events to the notification system.
	NotificationMode *string `json:"notification-mode,omitempty"`
	// NotifyUser User ID
	NotifyUser *string `json:"notify-user,omitempty"`
	// Owner Authentication ID
	Owner *string `json:"owner,omitempty"`
	// Snapshots List of snapshots.
	Snapshots []string `json:"snapshots,omitempty"`
	// Store A list of Datastore mappings (or single datastore), comma separated. For example 'a=b,e' maps the source datastore 'a' to target 'b and all other sources to the default 'e'. If no default is given, only the specified sources are mapped.
	Store string `json:"store"`
}

// CreateRestoreResponse is the raw JSON returned by POST /tape/restore.
type CreateRestoreResponse = json.RawMessage

// CreateRestore implements Service.CreateRestore. POST /tape/restore.
func (s *service) CreateRestore(ctx context.Context, params *CreateRestoreParams) (*CreateRestoreResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.CreateRestore: ctx must not be nil")
	}
	path := "/tape/restore"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateRestore: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("tape.CreateRestore: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateRestore: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.CreateRestore: nil response from client")
	}
	if resp.Data == nil {
		out := CreateRestoreResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateRestore: re-marshal data: %w", err)
	}
	out := &CreateRestoreResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.CreateRestore: unmarshal data: %w", err)
	}
	return out, nil
}

// ListScanChangersResponse mirrors the shape returned by GET /tape/scan-changers.
type ListScanChangersResponse []json.RawMessage

// ListScanChangers implements Service.ListScanChangers. GET /tape/scan-changers.
func (s *service) ListScanChangers(ctx context.Context) (*ListScanChangersResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.ListScanChangers: ctx must not be nil")
	}
	path := "/tape/scan-changers"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.ListScanChangers: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.ListScanChangers: nil response from client")
	}
	if resp.Data == nil {
		out := ListScanChangersResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.ListScanChangers: re-marshal data: %w", err)
	}
	out := &ListScanChangersResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.ListScanChangers: unmarshal data: %w", err)
	}
	return out, nil
}

// ListScanDrivesResponse mirrors the shape returned by GET /tape/scan-drives.
type ListScanDrivesResponse []json.RawMessage

// ListScanDrives implements Service.ListScanDrives. GET /tape/scan-drives.
func (s *service) ListScanDrives(ctx context.Context) (*ListScanDrivesResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("tape.ListScanDrives: ctx must not be nil")
	}
	path := "/tape/scan-drives"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("tape.ListScanDrives: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("tape.ListScanDrives: nil response from client")
	}
	if resp.Data == nil {
		out := ListScanDrivesResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("tape.ListScanDrives: re-marshal data: %w", err)
	}
	out := &ListScanDrivesResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("tape.ListScanDrives: unmarshal data: %w", err)
	}
	return out, nil
}
