// Package pdm groups the typed, generated bindings for the Proxmox
// Datacenter Manager REST API. Each child package (access, remotes,
// resources, nodes, …) is generated by cmd/pvegen from
// _data/pdm-apidoc.json and exposes a Service interface plus typed
// request/response shapes.
//
// PDM shares the PVE wire conventions (/api2/json base path,
// /access/ticket login, CSRFPreventionToken header) but listens on
// port 8443 and uses the PDMAPIToken/PDMAuthCookie credential names;
// see DefaultOptions in options.go for a preconfigured pkg/client
// Options value.
//
// Do not add hand-written code at this directory level beyond the
// client preset; everything else is metadata so that
// `go generate ./...` has a stable home.
package pdm

//go:generate go run ../../cmd/pvegen --dialect pdm --spec ../../_data/pdm-apidoc.json --out .
