// Code generated by cmd/pvegen. DO NOT EDIT.

package config_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"sync"
	"testing"

	pveclient "github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/pdm/config"
)

var _ = json.RawMessage(nil)

func smokeOptsFromServerURL(u string) pveclient.Options {
	parsed, err := url.Parse(u)
	if err != nil {
		panic("test setup: invalid server URL: " + err.Error())
	}

	host := parsed.Hostname()

	port := 0
	if p := parsed.Port(); p != "" {
		port, _ = strconv.Atoi(p)
	}

	return pveclient.Options{
		Host:     host,
		Port:     port,
		Protocol: "http",
		APIToken: "user@pam!tok=sec",
	}
}

// recordedRequest captures what the mock server observed for the most
// recently dispatched request.
type recordedRequest struct {
	method string
	path   string
	query  url.Values
	form   url.Values
}

// testHarness runs a single httptest.Server shared by every subtest in this
// file. Subtests are never run in parallel (each sets the desired response
// immediately before invoking the method under test, then reads back the
// recorded request), so the mutex below only guards against the harness
// goroutine and the test goroutine overlapping on a single in-flight
// request, never against concurrent subtests.
type testHarness struct {
	mu       sync.Mutex
	last     recordedRequest
	nextCode int
	nextBody string
}

// newTestHarness starts the mock server and returns it alongside the harness
// used to configure responses and inspect recorded requests.
func newTestHarness() (*httptest.Server, *testHarness) {
	h := &testHarness{nextCode: http.StatusOK}

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		h.mu.Lock()
		defer h.mu.Unlock()

		_ = r.ParseForm()
		h.last = recordedRequest{
			method: r.Method,
			path:   r.URL.Path,
			query:  r.URL.Query(),
			form:   r.PostForm,
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(h.nextCode)
		_, _ = w.Write([]byte(h.nextBody))
	}))

	return srv, h
}

// set configures the status code and body the next request will receive.
func (h *testHarness) set(code int, body string) {
	h.mu.Lock()
	defer h.mu.Unlock()

	h.nextCode = code
	h.nextBody = body
}

// snapshot returns a copy of the most recently recorded request.
func (h *testHarness) snapshot() recordedRequest {
	h.mu.Lock()
	defer h.mu.Unlock()

	return h.last
}

// assertRequestLine fails the test when the recorded method or resolved
// path does not exactly match what the endpoint's spec entry declares.
func assertRequestLine(t *testing.T, got recordedRequest, wantMethod, wantPath string) {
	t.Helper()

	if got.method != wantMethod {
		t.Errorf("method = %q, want %q", got.method, wantMethod)
	}

	if got.path != wantPath {
		t.Errorf("path = %q, want %q", got.path, wantPath)
	}
}

// assertParamValue fails the test when the wire-encoded value of key does
// not exactly equal want.
func assertParamValue(t *testing.T, values url.Values, key, want string) {
	t.Helper()

	if got := values.Get(key); got != want {
		t.Errorf("param %q = %q, want %q", key, got, want)
	}
}

// assertParamPresent fails the test when key is absent from values. Used for
// required parameters whose wire encoding is not a simple comparable string
// (e.g. json.RawMessage-typed fields).
func assertParamPresent(t *testing.T, values url.Values, key string) {
	t.Helper()

	if _, ok := values[key]; !ok {
		t.Errorf("param %q missing from request", key)
	}
}

func TestGenerated_Config_Methods(t *testing.T) {
	srv, harness := newTestHarness()
	defer srv.Close()

	c, err := pveclient.NewClient(smokeOptsFromServerURL(srv.URL))
	if err != nil {
		t.Fatalf("NewClient: %v", err)
	}

	svc := config.New(c)
	ctx := context.Background()

	t.Run("ListConfig", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListConfig(ctx)
		if err != nil {
			t.Fatalf("ListConfig: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config")

		var nilCtx context.Context
		if err := svc.ListConfig(nilCtx); err == nil {
			t.Errorf("ListConfig: expected error for nil context, got nil")
		}
	})
	t.Run("ListAccess", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListAccess(ctx)
		if err != nil {
			t.Fatalf("ListAccess: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/access")

		var nilCtx context.Context
		if err := svc.ListAccess(nilCtx); err == nil {
			t.Errorf("ListAccess: expected error for nil context, got nil")
		}
	})
	t.Run("ListAccessAd", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListAccessAd(ctx)
		if err != nil {
			t.Fatalf("ListAccessAd: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListAccessAd: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/access/ad")

		var nilCtx context.Context
		if _, err := svc.ListAccessAd(nilCtx); err == nil {
			t.Errorf("ListAccessAd: expected error for nil context, got nil")
		}
	})
	t.Run("CreateAccessAd", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateAccessAd(ctx, &config.CreateAccessAdParams{Realm: "sample-realm", Server1: "sample-server1"})
		if err != nil {
			t.Fatalf("CreateAccessAd: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/config/access/ad")
		assertParamValue(t, got.form, "realm", "sample-realm")
		assertParamValue(t, got.form, "server1", "sample-server1")

		var nilCtx context.Context
		if err := svc.CreateAccessAd(nilCtx, &config.CreateAccessAdParams{Realm: "sample-realm", Server1: "sample-server1"}); err == nil {
			t.Errorf("CreateAccessAd: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteAccessAd", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.DeleteAccessAd(ctx, "sample-realm", &config.DeleteAccessAdParams{})
		if err != nil {
			t.Fatalf("DeleteAccessAd: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/config/access/ad/sample-realm")

		var nilCtx context.Context
		if err := svc.DeleteAccessAd(nilCtx, "sample-realm", &config.DeleteAccessAdParams{}); err == nil {
			t.Errorf("DeleteAccessAd: expected error for nil context, got nil")
		}
	})
	t.Run("GetAccessAd", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.GetAccessAd(ctx, "sample-realm")
		if err != nil {
			t.Fatalf("GetAccessAd: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("GetAccessAd: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/access/ad/sample-realm")

		var nilCtx context.Context
		if _, err := svc.GetAccessAd(nilCtx, "sample-realm"); err == nil {
			t.Errorf("GetAccessAd: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateAccessAd", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateAccessAd(ctx, "sample-realm", &config.UpdateAccessAdParams{})
		if err != nil {
			t.Fatalf("UpdateAccessAd: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/config/access/ad/sample-realm")

		var nilCtx context.Context
		if err := svc.UpdateAccessAd(nilCtx, "sample-realm", &config.UpdateAccessAdParams{}); err == nil {
			t.Errorf("UpdateAccessAd: expected error for nil context, got nil")
		}
	})
	t.Run("ListAccessLdap", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListAccessLdap(ctx)
		if err != nil {
			t.Fatalf("ListAccessLdap: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListAccessLdap: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/access/ldap")

		var nilCtx context.Context
		if _, err := svc.ListAccessLdap(nilCtx); err == nil {
			t.Errorf("ListAccessLdap: expected error for nil context, got nil")
		}
	})
	t.Run("CreateAccessLdap", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateAccessLdap(ctx, &config.CreateAccessLdapParams{BaseDn: "sample-base-dn", Realm: "sample-realm", Server1: "sample-server1", UserAttr: "sample-user-attr"})
		if err != nil {
			t.Fatalf("CreateAccessLdap: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/config/access/ldap")
		assertParamValue(t, got.form, "base-dn", "sample-base-dn")
		assertParamValue(t, got.form, "realm", "sample-realm")
		assertParamValue(t, got.form, "server1", "sample-server1")
		assertParamValue(t, got.form, "user-attr", "sample-user-attr")

		var nilCtx context.Context
		if err := svc.CreateAccessLdap(nilCtx, &config.CreateAccessLdapParams{BaseDn: "sample-base-dn", Realm: "sample-realm", Server1: "sample-server1", UserAttr: "sample-user-attr"}); err == nil {
			t.Errorf("CreateAccessLdap: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteAccessLdap", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.DeleteAccessLdap(ctx, "sample-realm", &config.DeleteAccessLdapParams{})
		if err != nil {
			t.Fatalf("DeleteAccessLdap: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/config/access/ldap/sample-realm")

		var nilCtx context.Context
		if err := svc.DeleteAccessLdap(nilCtx, "sample-realm", &config.DeleteAccessLdapParams{}); err == nil {
			t.Errorf("DeleteAccessLdap: expected error for nil context, got nil")
		}
	})
	t.Run("GetAccessLdap", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.GetAccessLdap(ctx, "sample-realm")
		if err != nil {
			t.Fatalf("GetAccessLdap: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("GetAccessLdap: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/access/ldap/sample-realm")

		var nilCtx context.Context
		if _, err := svc.GetAccessLdap(nilCtx, "sample-realm"); err == nil {
			t.Errorf("GetAccessLdap: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateAccessLdap", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateAccessLdap(ctx, "sample-realm", &config.UpdateAccessLdapParams{})
		if err != nil {
			t.Fatalf("UpdateAccessLdap: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/config/access/ldap/sample-realm")

		var nilCtx context.Context
		if err := svc.UpdateAccessLdap(nilCtx, "sample-realm", &config.UpdateAccessLdapParams{}); err == nil {
			t.Errorf("UpdateAccessLdap: expected error for nil context, got nil")
		}
	})
	t.Run("ListAccessOpenid", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListAccessOpenid(ctx)
		if err != nil {
			t.Fatalf("ListAccessOpenid: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListAccessOpenid: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/access/openid")

		var nilCtx context.Context
		if _, err := svc.ListAccessOpenid(nilCtx); err == nil {
			t.Errorf("ListAccessOpenid: expected error for nil context, got nil")
		}
	})
	t.Run("CreateAccessOpenid", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateAccessOpenid(ctx, &config.CreateAccessOpenidParams{ClientId: "sample-client-id", IssuerUrl: "sample-issuer-url", Realm: "sample-realm"})
		if err != nil {
			t.Fatalf("CreateAccessOpenid: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/config/access/openid")
		assertParamValue(t, got.form, "client-id", "sample-client-id")
		assertParamValue(t, got.form, "issuer-url", "sample-issuer-url")
		assertParamValue(t, got.form, "realm", "sample-realm")

		var nilCtx context.Context
		if err := svc.CreateAccessOpenid(nilCtx, &config.CreateAccessOpenidParams{ClientId: "sample-client-id", IssuerUrl: "sample-issuer-url", Realm: "sample-realm"}); err == nil {
			t.Errorf("CreateAccessOpenid: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteAccessOpenid", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.DeleteAccessOpenid(ctx, "sample-realm", &config.DeleteAccessOpenidParams{})
		if err != nil {
			t.Fatalf("DeleteAccessOpenid: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/config/access/openid/sample-realm")

		var nilCtx context.Context
		if err := svc.DeleteAccessOpenid(nilCtx, "sample-realm", &config.DeleteAccessOpenidParams{}); err == nil {
			t.Errorf("DeleteAccessOpenid: expected error for nil context, got nil")
		}
	})
	t.Run("GetAccessOpenid", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.GetAccessOpenid(ctx, "sample-realm")
		if err != nil {
			t.Fatalf("GetAccessOpenid: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("GetAccessOpenid: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/access/openid/sample-realm")

		var nilCtx context.Context
		if _, err := svc.GetAccessOpenid(nilCtx, "sample-realm"); err == nil {
			t.Errorf("GetAccessOpenid: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateAccessOpenid", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateAccessOpenid(ctx, "sample-realm", &config.UpdateAccessOpenidParams{})
		if err != nil {
			t.Fatalf("UpdateAccessOpenid: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/config/access/openid/sample-realm")

		var nilCtx context.Context
		if err := svc.UpdateAccessOpenid(nilCtx, "sample-realm", &config.UpdateAccessOpenidParams{}); err == nil {
			t.Errorf("UpdateAccessOpenid: expected error for nil context, got nil")
		}
	})
	t.Run("ListAccessPam", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListAccessPam(ctx)
		if err != nil {
			t.Fatalf("ListAccessPam: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListAccessPam: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/access/pam")

		var nilCtx context.Context
		if _, err := svc.ListAccessPam(nilCtx); err == nil {
			t.Errorf("ListAccessPam: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateAccessPam", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.UpdateAccessPam(ctx, &config.UpdateAccessPamParams{})
		if err != nil {
			t.Fatalf("UpdateAccessPam: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("UpdateAccessPam: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/config/access/pam")

		var nilCtx context.Context
		if _, err := svc.UpdateAccessPam(nilCtx, &config.UpdateAccessPamParams{}); err == nil {
			t.Errorf("UpdateAccessPam: expected error for nil context, got nil")
		}
	})
	t.Run("ListAccessPdm", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListAccessPdm(ctx)
		if err != nil {
			t.Fatalf("ListAccessPdm: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListAccessPdm: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/access/pdm")

		var nilCtx context.Context
		if _, err := svc.ListAccessPdm(nilCtx); err == nil {
			t.Errorf("ListAccessPdm: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateAccessPdm", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.UpdateAccessPdm(ctx, &config.UpdateAccessPdmParams{})
		if err != nil {
			t.Fatalf("UpdateAccessPdm: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("UpdateAccessPdm: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/config/access/pdm")

		var nilCtx context.Context
		if _, err := svc.UpdateAccessPdm(nilCtx, &config.UpdateAccessPdmParams{}); err == nil {
			t.Errorf("UpdateAccessPdm: expected error for nil context, got nil")
		}
	})
	t.Run("ListAccessTfa", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListAccessTfa(ctx)
		if err != nil {
			t.Fatalf("ListAccessTfa: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/access/tfa")

		var nilCtx context.Context
		if err := svc.ListAccessTfa(nilCtx); err == nil {
			t.Errorf("ListAccessTfa: expected error for nil context, got nil")
		}
	})
	t.Run("ListAccessTfaWebauthn", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListAccessTfaWebauthn(ctx)
		if err != nil {
			t.Fatalf("ListAccessTfaWebauthn: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListAccessTfaWebauthn: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/access/tfa/webauthn")

		var nilCtx context.Context
		if _, err := svc.ListAccessTfaWebauthn(nilCtx); err == nil {
			t.Errorf("ListAccessTfaWebauthn: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateAccessTfaWebauthn", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateAccessTfaWebauthn(ctx, &config.UpdateAccessTfaWebauthnParams{})
		if err != nil {
			t.Fatalf("UpdateAccessTfaWebauthn: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/config/access/tfa/webauthn")

		var nilCtx context.Context
		if err := svc.UpdateAccessTfaWebauthn(nilCtx, &config.UpdateAccessTfaWebauthnParams{}); err == nil {
			t.Errorf("UpdateAccessTfaWebauthn: expected error for nil context, got nil")
		}
	})
	t.Run("ListAcme", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListAcme(ctx)
		if err != nil {
			t.Fatalf("ListAcme: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/acme")

		var nilCtx context.Context
		if err := svc.ListAcme(nilCtx); err == nil {
			t.Errorf("ListAcme: expected error for nil context, got nil")
		}
	})
	t.Run("ListAcmeAccount", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListAcmeAccount(ctx)
		if err != nil {
			t.Fatalf("ListAcmeAccount: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListAcmeAccount: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/acme/account")

		var nilCtx context.Context
		if _, err := svc.ListAcmeAccount(nilCtx); err == nil {
			t.Errorf("ListAcmeAccount: expected error for nil context, got nil")
		}
	})
	t.Run("CreateAcmeAccount", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateAcmeAccount(ctx, &config.CreateAcmeAccountParams{Contact: "sample-contact"})
		if err != nil {
			t.Fatalf("CreateAcmeAccount: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateAcmeAccount: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/config/acme/account")
		assertParamValue(t, got.form, "contact", "sample-contact")

		var nilCtx context.Context
		if _, err := svc.CreateAcmeAccount(nilCtx, &config.CreateAcmeAccountParams{Contact: "sample-contact"}); err == nil {
			t.Errorf("CreateAcmeAccount: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteAcmeAccount", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.DeleteAcmeAccount(ctx, "sample-name", &config.DeleteAcmeAccountParams{})
		if err != nil {
			t.Fatalf("DeleteAcmeAccount: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("DeleteAcmeAccount: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/config/acme/account/sample-name")

		var nilCtx context.Context
		if _, err := svc.DeleteAcmeAccount(nilCtx, "sample-name", &config.DeleteAcmeAccountParams{}); err == nil {
			t.Errorf("DeleteAcmeAccount: expected error for nil context, got nil")
		}
	})
	t.Run("GetAcmeAccount", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.GetAcmeAccount(ctx, "sample-name")
		if err != nil {
			t.Fatalf("GetAcmeAccount: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("GetAcmeAccount: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/acme/account/sample-name")

		var nilCtx context.Context
		if _, err := svc.GetAcmeAccount(nilCtx, "sample-name"); err == nil {
			t.Errorf("GetAcmeAccount: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateAcmeAccount", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.UpdateAcmeAccount(ctx, "sample-name", &config.UpdateAcmeAccountParams{})
		if err != nil {
			t.Fatalf("UpdateAcmeAccount: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("UpdateAcmeAccount: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/config/acme/account/sample-name")

		var nilCtx context.Context
		if _, err := svc.UpdateAcmeAccount(nilCtx, "sample-name", &config.UpdateAcmeAccountParams{}); err == nil {
			t.Errorf("UpdateAcmeAccount: expected error for nil context, got nil")
		}
	})
	t.Run("ListAcmeChallengeSchema", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListAcmeChallengeSchema(ctx)
		if err != nil {
			t.Fatalf("ListAcmeChallengeSchema: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListAcmeChallengeSchema: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/acme/challenge-schema")

		var nilCtx context.Context
		if _, err := svc.ListAcmeChallengeSchema(nilCtx); err == nil {
			t.Errorf("ListAcmeChallengeSchema: expected error for nil context, got nil")
		}
	})
	t.Run("ListAcmeDirectories", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListAcmeDirectories(ctx)
		if err != nil {
			t.Fatalf("ListAcmeDirectories: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListAcmeDirectories: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/acme/directories")

		var nilCtx context.Context
		if _, err := svc.ListAcmeDirectories(nilCtx); err == nil {
			t.Errorf("ListAcmeDirectories: expected error for nil context, got nil")
		}
	})
	t.Run("ListAcmePlugins", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListAcmePlugins(ctx)
		if err != nil {
			t.Fatalf("ListAcmePlugins: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListAcmePlugins: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/acme/plugins")

		var nilCtx context.Context
		if _, err := svc.ListAcmePlugins(nilCtx); err == nil {
			t.Errorf("ListAcmePlugins: expected error for nil context, got nil")
		}
	})
	t.Run("CreateAcmePlugins", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateAcmePlugins(ctx, &config.CreateAcmePluginsParams{Api: "sample-api", Data: "sample-data", Id: "sample-id", Type: "sample-type"})
		if err != nil {
			t.Fatalf("CreateAcmePlugins: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/config/acme/plugins")
		assertParamValue(t, got.form, "api", "sample-api")
		assertParamValue(t, got.form, "data", "sample-data")
		assertParamValue(t, got.form, "id", "sample-id")
		assertParamValue(t, got.form, "type", "sample-type")

		var nilCtx context.Context
		if err := svc.CreateAcmePlugins(nilCtx, &config.CreateAcmePluginsParams{Api: "sample-api", Data: "sample-data", Id: "sample-id", Type: "sample-type"}); err == nil {
			t.Errorf("CreateAcmePlugins: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteAcmePlugins", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.DeleteAcmePlugins(ctx, "sample-id")
		if err != nil {
			t.Fatalf("DeleteAcmePlugins: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/config/acme/plugins/sample-id")

		var nilCtx context.Context
		if err := svc.DeleteAcmePlugins(nilCtx, "sample-id"); err == nil {
			t.Errorf("DeleteAcmePlugins: expected error for nil context, got nil")
		}
	})
	t.Run("GetAcmePlugins", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.GetAcmePlugins(ctx, "sample-id")
		if err != nil {
			t.Fatalf("GetAcmePlugins: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("GetAcmePlugins: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/acme/plugins/sample-id")

		var nilCtx context.Context
		if _, err := svc.GetAcmePlugins(nilCtx, "sample-id"); err == nil {
			t.Errorf("GetAcmePlugins: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateAcmePlugins", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateAcmePlugins(ctx, "sample-id", &config.UpdateAcmePluginsParams{})
		if err != nil {
			t.Fatalf("UpdateAcmePlugins: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/config/acme/plugins/sample-id")

		var nilCtx context.Context
		if err := svc.UpdateAcmePlugins(nilCtx, "sample-id", &config.UpdateAcmePluginsParams{}); err == nil {
			t.Errorf("UpdateAcmePlugins: expected error for nil context, got nil")
		}
	})
	t.Run("ListAcmeTos", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListAcmeTos(ctx, &config.ListAcmeTosParams{})
		if err != nil {
			t.Fatalf("ListAcmeTos: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListAcmeTos: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/acme/tos")

		var nilCtx context.Context
		if _, err := svc.ListAcmeTos(nilCtx, &config.ListAcmeTosParams{}); err == nil {
			t.Errorf("ListAcmeTos: expected error for nil context, got nil")
		}
	})
	t.Run("ListCertificate", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListCertificate(ctx)
		if err != nil {
			t.Fatalf("ListCertificate: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListCertificate: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/certificate")

		var nilCtx context.Context
		if _, err := svc.ListCertificate(nilCtx); err == nil {
			t.Errorf("ListCertificate: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateCertificate", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateCertificate(ctx, &config.UpdateCertificateParams{})
		if err != nil {
			t.Fatalf("UpdateCertificate: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/config/certificate")

		var nilCtx context.Context
		if err := svc.UpdateCertificate(nilCtx, &config.UpdateCertificateParams{}); err == nil {
			t.Errorf("UpdateCertificate: expected error for nil context, got nil")
		}
	})
	t.Run("ListNotes", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListNotes(ctx)
		if err != nil {
			t.Fatalf("ListNotes: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListNotes: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/notes")

		var nilCtx context.Context
		if _, err := svc.ListNotes(nilCtx); err == nil {
			t.Errorf("ListNotes: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateNotes", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateNotes(ctx, &config.UpdateNotesParams{Notes: "sample-notes"})
		if err != nil {
			t.Fatalf("UpdateNotes: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/config/notes")
		assertParamValue(t, got.form, "notes", "sample-notes")

		var nilCtx context.Context
		if err := svc.UpdateNotes(nilCtx, &config.UpdateNotesParams{Notes: "sample-notes"}); err == nil {
			t.Errorf("UpdateNotes: expected error for nil context, got nil")
		}
	})
	t.Run("ListViews", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListViews(ctx)
		if err != nil {
			t.Fatalf("ListViews: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListViews: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/views")

		var nilCtx context.Context
		if _, err := svc.ListViews(nilCtx); err == nil {
			t.Errorf("ListViews: expected error for nil context, got nil")
		}
	})
	t.Run("CreateViews", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateViews(ctx, &config.CreateViewsParams{Id: "sample-id"})
		if err != nil {
			t.Fatalf("CreateViews: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/config/views")
		assertParamValue(t, got.form, "id", "sample-id")

		var nilCtx context.Context
		if err := svc.CreateViews(nilCtx, &config.CreateViewsParams{Id: "sample-id"}); err == nil {
			t.Errorf("CreateViews: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteViews", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.DeleteViews(ctx, "sample-id", &config.DeleteViewsParams{})
		if err != nil {
			t.Fatalf("DeleteViews: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/config/views/sample-id")

		var nilCtx context.Context
		if err := svc.DeleteViews(nilCtx, "sample-id", &config.DeleteViewsParams{}); err == nil {
			t.Errorf("DeleteViews: expected error for nil context, got nil")
		}
	})
	t.Run("GetViews", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.GetViews(ctx, "sample-id")
		if err != nil {
			t.Fatalf("GetViews: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("GetViews: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/config/views/sample-id")

		var nilCtx context.Context
		if _, err := svc.GetViews(nilCtx, "sample-id"); err == nil {
			t.Errorf("GetViews: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateViews", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateViews(ctx, "sample-id", &config.UpdateViewsParams{})
		if err != nil {
			t.Fatalf("UpdateViews: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/config/views/sample-id")

		var nilCtx context.Context
		if err := svc.UpdateViews(nilCtx, "sample-id", &config.UpdateViewsParams{}); err == nil {
			t.Errorf("UpdateViews: expected error for nil context, got nil")
		}
	})
	t.Run("ErrorPath_GET", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.ListConfig(ctx)
		if err == nil {
			t.Fatalf("ListConfig: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_POST", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.CreateAccessAd(ctx, &config.CreateAccessAdParams{Realm: "sample-realm", Server1: "sample-server1"})
		if err == nil {
			t.Fatalf("CreateAccessAd: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_DELETE", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.DeleteAccessAd(ctx, "sample-realm", &config.DeleteAccessAdParams{})
		if err == nil {
			t.Fatalf("DeleteAccessAd: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_PUT", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.UpdateAccessAd(ctx, "sample-realm", &config.UpdateAccessAdParams{})
		if err == nil {
			t.Fatalf("UpdateAccessAd: expected error on 500 response, got nil")
		}
	})
}
