// Code generated by cmd/pvegen. DO NOT EDIT.

// Package ping exposes typed bindings for the PVE /ping endpoint family.
package ping

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
)

var _ = strings.TrimPrefix
var _ = json.RawMessage(nil)
var _ = url.PathEscape
var _ = sort.Ints
var _ = strconv.Itoa

// Service exposes typed operations on the /ping endpoint family.
type Service interface {
	// Ping GET /ping
	// A simple ping method. returns "pong"
	Ping(ctx context.Context) (*PingResponse, error)
}

// New constructs a Service backed by the given pkg/client.Client.
// The client owns authentication, TLS, retries, and logging; this
// service only translates between typed Go shapes and the raw client.
func New(c client.Client) Service {
	if c == nil {
		panic("ping: New called with nil client")
	}
	return &service{c: c}
}

type service struct {
	c client.Client
}

// PingResponse is the raw JSON returned by GET /ping.
type PingResponse = json.RawMessage

// Ping implements Service.Ping. GET /ping.
func (s *service) Ping(ctx context.Context) (*PingResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("ping.Ping: ctx must not be nil")
	}
	path := "/ping"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("ping.Ping: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("ping.Ping: nil response from client")
	}
	if resp.Data == nil {
		out := PingResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("ping.Ping: re-marshal data: %w", err)
	}
	out := &PingResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("ping.Ping: unmarshal data: %w", err)
	}
	return out, nil
}
