// Code generated by cmd/pvegen. DO NOT EDIT.

package subscriptions_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"sync"
	"testing"

	pveclient "github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/pdm/subscriptions"
)

var _ = json.RawMessage(nil)

func smokeOptsFromServerURL(u string) pveclient.Options {
	parsed, err := url.Parse(u)
	if err != nil {
		panic("test setup: invalid server URL: " + err.Error())
	}

	host := parsed.Hostname()

	port := 0
	if p := parsed.Port(); p != "" {
		port, _ = strconv.Atoi(p)
	}

	return pveclient.Options{
		Host:     host,
		Port:     port,
		Protocol: "http",
		APIToken: "user@pam!tok=sec",
	}
}

// recordedRequest captures what the mock server observed for the most
// recently dispatched request.
type recordedRequest struct {
	method string
	path   string
	query  url.Values
	form   url.Values
}

// testHarness runs a single httptest.Server shared by every subtest in this
// file. Subtests are never run in parallel (each sets the desired response
// immediately before invoking the method under test, then reads back the
// recorded request), so the mutex below only guards against the harness
// goroutine and the test goroutine overlapping on a single in-flight
// request, never against concurrent subtests.
type testHarness struct {
	mu       sync.Mutex
	last     recordedRequest
	nextCode int
	nextBody string
}

// newTestHarness starts the mock server and returns it alongside the harness
// used to configure responses and inspect recorded requests.
func newTestHarness() (*httptest.Server, *testHarness) {
	h := &testHarness{nextCode: http.StatusOK}

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		h.mu.Lock()
		defer h.mu.Unlock()

		_ = r.ParseForm()
		h.last = recordedRequest{
			method: r.Method,
			path:   r.URL.Path,
			query:  r.URL.Query(),
			form:   r.PostForm,
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(h.nextCode)
		_, _ = w.Write([]byte(h.nextBody))
	}))

	return srv, h
}

// set configures the status code and body the next request will receive.
func (h *testHarness) set(code int, body string) {
	h.mu.Lock()
	defer h.mu.Unlock()

	h.nextCode = code
	h.nextBody = body
}

// snapshot returns a copy of the most recently recorded request.
func (h *testHarness) snapshot() recordedRequest {
	h.mu.Lock()
	defer h.mu.Unlock()

	return h.last
}

// assertRequestLine fails the test when the recorded method or resolved
// path does not exactly match what the endpoint's spec entry declares.
func assertRequestLine(t *testing.T, got recordedRequest, wantMethod, wantPath string) {
	t.Helper()

	if got.method != wantMethod {
		t.Errorf("method = %q, want %q", got.method, wantMethod)
	}

	if got.path != wantPath {
		t.Errorf("path = %q, want %q", got.path, wantPath)
	}
}

// assertParamValue fails the test when the wire-encoded value of key does
// not exactly equal want.
func assertParamValue(t *testing.T, values url.Values, key, want string) {
	t.Helper()

	if got := values.Get(key); got != want {
		t.Errorf("param %q = %q, want %q", key, got, want)
	}
}

// assertParamPresent fails the test when key is absent from values. Used for
// required parameters whose wire encoding is not a simple comparable string
// (e.g. json.RawMessage-typed fields).
func assertParamPresent(t *testing.T, values url.Values, key string) {
	t.Helper()

	if _, ok := values[key]; !ok {
		t.Errorf("param %q missing from request", key)
	}
}

func TestGenerated_Subscriptions_Methods(t *testing.T) {
	srv, harness := newTestHarness()
	defer srv.Close()

	c, err := pveclient.NewClient(smokeOptsFromServerURL(srv.URL))
	if err != nil {
		t.Fatalf("NewClient: %v", err)
	}

	svc := subscriptions.New(c)
	ctx := context.Background()

	t.Run("ListSubscriptions", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListSubscriptions(ctx)
		if err != nil {
			t.Fatalf("ListSubscriptions: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/subscriptions")

		var nilCtx context.Context
		if err := svc.ListSubscriptions(nilCtx); err == nil {
			t.Errorf("ListSubscriptions: expected error for nil context, got nil")
		}
	})
	t.Run("CreateAdoptAll", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.CreateAdoptAll(ctx, &subscriptions.CreateAdoptAllParams{})
		if err != nil {
			t.Fatalf("CreateAdoptAll: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateAdoptAll: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/subscriptions/adopt-all")

		var nilCtx context.Context
		if _, err := svc.CreateAdoptAll(nilCtx, &subscriptions.CreateAdoptAllParams{}); err == nil {
			t.Errorf("CreateAdoptAll: expected error for nil context, got nil")
		}
	})
	t.Run("CreateAdoptKey", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateAdoptKey(ctx, &subscriptions.CreateAdoptKeyParams{Node: "sample-node", Remote: "sample-remote"})
		if err != nil {
			t.Fatalf("CreateAdoptKey: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/subscriptions/adopt-key")
		assertParamValue(t, got.form, "node", "sample-node")
		assertParamValue(t, got.form, "remote", "sample-remote")

		var nilCtx context.Context
		if err := svc.CreateAdoptKey(nilCtx, &subscriptions.CreateAdoptKeyParams{Node: "sample-node", Remote: "sample-remote"}); err == nil {
			t.Errorf("CreateAdoptKey: expected error for nil context, got nil")
		}
	})
	t.Run("CreateApplyPending", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateApplyPending(ctx, &subscriptions.CreateApplyPendingParams{})
		if err != nil {
			t.Fatalf("CreateApplyPending: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateApplyPending: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/subscriptions/apply-pending")

		var nilCtx context.Context
		if _, err := svc.CreateApplyPending(nilCtx, &subscriptions.CreateApplyPendingParams{}); err == nil {
			t.Errorf("CreateApplyPending: expected error for nil context, got nil")
		}
	})
	t.Run("CreateAutoAssign", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateAutoAssign(ctx)
		if err != nil {
			t.Fatalf("CreateAutoAssign: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateAutoAssign: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/subscriptions/auto-assign")

		var nilCtx context.Context
		if _, err := svc.CreateAutoAssign(nilCtx); err == nil {
			t.Errorf("CreateAutoAssign: expected error for nil context, got nil")
		}
	})
	t.Run("CreateBulkAssign", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.CreateBulkAssign(ctx, &subscriptions.CreateBulkAssignParams{Proposal: json.RawMessage("{}")})
		if err != nil {
			t.Fatalf("CreateBulkAssign: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateBulkAssign: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/subscriptions/bulk-assign")
		assertParamPresent(t, got.form, "proposal")

		var nilCtx context.Context
		if _, err := svc.CreateBulkAssign(nilCtx, &subscriptions.CreateBulkAssignParams{Proposal: json.RawMessage("{}")}); err == nil {
			t.Errorf("CreateBulkAssign: expected error for nil context, got nil")
		}
	})
	t.Run("CreateCheck", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateCheck(ctx, &subscriptions.CreateCheckParams{Node: "sample-node", Remote: "sample-remote"})
		if err != nil {
			t.Fatalf("CreateCheck: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/subscriptions/check")
		assertParamValue(t, got.form, "node", "sample-node")
		assertParamValue(t, got.form, "remote", "sample-remote")

		var nilCtx context.Context
		if err := svc.CreateCheck(nilCtx, &subscriptions.CreateCheckParams{Node: "sample-node", Remote: "sample-remote"}); err == nil {
			t.Errorf("CreateCheck: expected error for nil context, got nil")
		}
	})
	t.Run("CreateClearPending", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateClearPending(ctx, &subscriptions.CreateClearPendingParams{})
		if err != nil {
			t.Fatalf("CreateClearPending: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateClearPending: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/subscriptions/clear-pending")

		var nilCtx context.Context
		if _, err := svc.CreateClearPending(nilCtx, &subscriptions.CreateClearPendingParams{}); err == nil {
			t.Errorf("CreateClearPending: expected error for nil context, got nil")
		}
	})
	t.Run("ListKeys", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListKeys(ctx)
		if err != nil {
			t.Fatalf("ListKeys: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListKeys: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/subscriptions/keys")

		var nilCtx context.Context
		if _, err := svc.ListKeys(nilCtx); err == nil {
			t.Errorf("ListKeys: expected error for nil context, got nil")
		}
	})
	t.Run("CreateKeys", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateKeys(ctx, &subscriptions.CreateKeysParams{Keys: []string{"sample-keys"}})
		if err != nil {
			t.Fatalf("CreateKeys: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateKeys: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/subscriptions/keys")
		assertParamValue(t, got.form, "keys", "sample-keys")

		var nilCtx context.Context
		if _, err := svc.CreateKeys(nilCtx, &subscriptions.CreateKeysParams{Keys: []string{"sample-keys"}}); err == nil {
			t.Errorf("CreateKeys: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteKeys", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.DeleteKeys(ctx, "sample-key", &subscriptions.DeleteKeysParams{})
		if err != nil {
			t.Fatalf("DeleteKeys: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/subscriptions/keys/sample-key")

		var nilCtx context.Context
		if err := svc.DeleteKeys(nilCtx, "sample-key", &subscriptions.DeleteKeysParams{}); err == nil {
			t.Errorf("DeleteKeys: expected error for nil context, got nil")
		}
	})
	t.Run("GetKeys", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.GetKeys(ctx, "sample-key")
		if err != nil {
			t.Fatalf("GetKeys: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("GetKeys: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/subscriptions/keys/sample-key")

		var nilCtx context.Context
		if _, err := svc.GetKeys(nilCtx, "sample-key"); err == nil {
			t.Errorf("GetKeys: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteKeysAssignment", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.DeleteKeysAssignment(ctx, "sample-key", &subscriptions.DeleteKeysAssignmentParams{})
		if err != nil {
			t.Fatalf("DeleteKeysAssignment: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/subscriptions/keys/sample-key/assignment")

		var nilCtx context.Context
		if err := svc.DeleteKeysAssignment(nilCtx, "sample-key", &subscriptions.DeleteKeysAssignmentParams{}); err == nil {
			t.Errorf("DeleteKeysAssignment: expected error for nil context, got nil")
		}
	})
	t.Run("CreateKeysAssignment", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateKeysAssignment(ctx, "sample-key", &subscriptions.CreateKeysAssignmentParams{Node: "sample-node", Remote: "sample-remote"})
		if err != nil {
			t.Fatalf("CreateKeysAssignment: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/subscriptions/keys/sample-key/assignment")
		assertParamValue(t, got.form, "node", "sample-node")
		assertParamValue(t, got.form, "remote", "sample-remote")

		var nilCtx context.Context
		if err := svc.CreateKeysAssignment(nilCtx, "sample-key", &subscriptions.CreateKeysAssignmentParams{Node: "sample-node", Remote: "sample-remote"}); err == nil {
			t.Errorf("CreateKeysAssignment: expected error for nil context, got nil")
		}
	})
	t.Run("ListNodeStatus", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListNodeStatus(ctx, &subscriptions.ListNodeStatusParams{})
		if err != nil {
			t.Fatalf("ListNodeStatus: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListNodeStatus: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/subscriptions/node-status")

		var nilCtx context.Context
		if _, err := svc.ListNodeStatus(nilCtx, &subscriptions.ListNodeStatusParams{}); err == nil {
			t.Errorf("ListNodeStatus: expected error for nil context, got nil")
		}
	})
	t.Run("CreateQueueClear", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateQueueClear(ctx, &subscriptions.CreateQueueClearParams{Node: "sample-node", Remote: "sample-remote"})
		if err != nil {
			t.Fatalf("CreateQueueClear: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/subscriptions/queue-clear")
		assertParamValue(t, got.form, "node", "sample-node")
		assertParamValue(t, got.form, "remote", "sample-remote")

		var nilCtx context.Context
		if err := svc.CreateQueueClear(nilCtx, &subscriptions.CreateQueueClearParams{Node: "sample-node", Remote: "sample-remote"}); err == nil {
			t.Errorf("CreateQueueClear: expected error for nil context, got nil")
		}
	})
	t.Run("CreateRevertPendingClear", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateRevertPendingClear(ctx, &subscriptions.CreateRevertPendingClearParams{Node: "sample-node", Remote: "sample-remote"})
		if err != nil {
			t.Fatalf("CreateRevertPendingClear: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/subscriptions/revert-pending-clear")
		assertParamValue(t, got.form, "node", "sample-node")
		assertParamValue(t, got.form, "remote", "sample-remote")

		var nilCtx context.Context
		if err := svc.CreateRevertPendingClear(nilCtx, &subscriptions.CreateRevertPendingClearParams{Node: "sample-node", Remote: "sample-remote"}); err == nil {
			t.Errorf("CreateRevertPendingClear: expected error for nil context, got nil")
		}
	})
	t.Run("ErrorPath_GET", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.ListSubscriptions(ctx)
		if err == nil {
			t.Fatalf("ListSubscriptions: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_POST", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		_, err := svc.CreateAdoptAll(ctx, &subscriptions.CreateAdoptAllParams{})
		if err == nil {
			t.Fatalf("CreateAdoptAll: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_DELETE", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.DeleteKeys(ctx, "sample-key", &subscriptions.DeleteKeysParams{})
		if err == nil {
			t.Fatalf("DeleteKeys: expected error on 500 response, got nil")
		}
	})
}
