// Code generated by cmd/pvegen. DO NOT EDIT.

// Package admin exposes typed bindings for the PVE /admin endpoint family.
package admin

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
)

var _ = strings.TrimPrefix
var _ = json.RawMessage(nil)
var _ = url.PathEscape
var _ = sort.Ints
var _ = strconv.Itoa

// Service exposes typed operations on the /admin endpoint family.
type Service interface {
	// ListAdmin GET /admin
	// Directory index.
	ListAdmin(ctx context.Context) error
	// ListDatastore GET /admin/datastore
	// Datastore list
	ListDatastore(ctx context.Context) (*ListDatastoreResponse, error)
	// GetDatastore GET /admin/datastore/{store}
	// Directory index.
	GetDatastore(ctx context.Context, store string) error
	// ListDatastoreActiveOperations GET /admin/datastore/{store}/active-operations
	// Read datastore stats
	ListDatastoreActiveOperations(ctx context.Context, store string) error
	// ListDatastoreCatalog GET /admin/datastore/{store}/catalog
	// Get the entries of the given path of the catalog
	ListDatastoreCatalog(ctx context.Context, store string, params *ListDatastoreCatalogParams) error
	// CreateDatastoreChangeOwner POST /admin/datastore/{store}/change-owner
	// Change owner of a backup group
	CreateDatastoreChangeOwner(ctx context.Context, store string, params *CreateDatastoreChangeOwnerParams) error
	// ListDatastoreDownload GET /admin/datastore/{store}/download
	// Download single raw file from backup snapshot.
	ListDatastoreDownload(ctx context.Context, store string, params *ListDatastoreDownloadParams) error
	// ListDatastoreDownloadDecoded GET /admin/datastore/{store}/download-decoded
	// Download single decoded file from backup snapshot. Only works if it's not encrypted.
	ListDatastoreDownloadDecoded(ctx context.Context, store string, params *ListDatastoreDownloadDecodedParams) error
	// ListDatastoreFiles GET /admin/datastore/{store}/files
	// List snapshot files.
	ListDatastoreFiles(ctx context.Context, store string, params *ListDatastoreFilesParams) (*ListDatastoreFilesResponse, error)
	// ListDatastoreGc GET /admin/datastore/{store}/gc
	// Garbage collection status.
	ListDatastoreGc(ctx context.Context, store string) (*ListDatastoreGcResponse, error)
	// CreateDatastoreGc POST /admin/datastore/{store}/gc
	// Start garbage collection.
	CreateDatastoreGc(ctx context.Context, store string) (*CreateDatastoreGcResponse, error)
	// ListDatastoreGroupNotes GET /admin/datastore/{store}/group-notes
	// Get "notes" for a backup group
	ListDatastoreGroupNotes(ctx context.Context, store string, params *ListDatastoreGroupNotesParams) error
	// UpdateDatastoreGroupNotes PUT /admin/datastore/{store}/group-notes
	// Set "notes" for a backup group
	UpdateDatastoreGroupNotes(ctx context.Context, store string, params *UpdateDatastoreGroupNotesParams) error
	// DeleteDatastoreGroups DELETE /admin/datastore/{store}/groups
	// Delete backup group including all snapshots.
	DeleteDatastoreGroups(ctx context.Context, store string, params *DeleteDatastoreGroupsParams) (*DeleteDatastoreGroupsResponse, error)
	// ListDatastoreGroups GET /admin/datastore/{store}/groups
	// List backup groups.
	ListDatastoreGroups(ctx context.Context, store string, params *ListDatastoreGroupsParams) (*ListDatastoreGroupsResponse, error)
	// CreateDatastoreMount POST /admin/datastore/{store}/mount
	// Mount removable datastore.
	CreateDatastoreMount(ctx context.Context, store string) (*CreateDatastoreMountResponse, error)
	// CreateDatastoreMoveGroup POST /admin/datastore/{store}/move-group
	// Move a backup group to a different namespace within the same datastore.
	CreateDatastoreMoveGroup(ctx context.Context, store string, params *CreateDatastoreMoveGroupParams) (*CreateDatastoreMoveGroupResponse, error)
	// CreateDatastoreMoveNamespace POST /admin/datastore/{store}/move-namespace
	// Move a backup namespace (including all child namespaces and groups) to a new location.
	CreateDatastoreMoveNamespace(ctx context.Context, store string, params *CreateDatastoreMoveNamespaceParams) (*CreateDatastoreMoveNamespaceResponse, error)
	// DeleteDatastoreNamespace DELETE /admin/datastore/{store}/namespace
	// Delete a backup namespace including all snapshots.
	DeleteDatastoreNamespace(ctx context.Context, store string, params *DeleteDatastoreNamespaceParams) error
	// ListDatastoreNamespace GET /admin/datastore/{store}/namespace
	// List the namespaces of a datastore.
	ListDatastoreNamespace(ctx context.Context, store string, params *ListDatastoreNamespaceParams) (*ListDatastoreNamespaceResponse, error)
	// CreateDatastoreNamespace POST /admin/datastore/{store}/namespace
	// Create a new datastore namespace.
	CreateDatastoreNamespace(ctx context.Context, store string, params *CreateDatastoreNamespaceParams) (*CreateDatastoreNamespaceResponse, error)
	// ListDatastoreNotes GET /admin/datastore/{store}/notes
	// Get "notes" for a specific backup
	ListDatastoreNotes(ctx context.Context, store string, params *ListDatastoreNotesParams) error
	// UpdateDatastoreNotes PUT /admin/datastore/{store}/notes
	// Set "notes" for a specific backup
	UpdateDatastoreNotes(ctx context.Context, store string, params *UpdateDatastoreNotesParams) error
	// ListDatastoreProtected GET /admin/datastore/{store}/protected
	// Query protection for a specific backup
	ListDatastoreProtected(ctx context.Context, store string, params *ListDatastoreProtectedParams) error
	// UpdateDatastoreProtected PUT /admin/datastore/{store}/protected
	// En- or disable protection for a specific backup
	UpdateDatastoreProtected(ctx context.Context, store string, params *UpdateDatastoreProtectedParams) error
	// CreateDatastorePrune POST /admin/datastore/{store}/prune
	// Prune a group on the datastore
	CreateDatastorePrune(ctx context.Context, store string, params *CreateDatastorePruneParams) (*CreateDatastorePruneResponse, error)
	// CreateDatastorePruneDatastore POST /admin/datastore/{store}/prune-datastore
	// Prune the datastore
	CreateDatastorePruneDatastore(ctx context.Context, store string, params *CreateDatastorePruneDatastoreParams) (*CreateDatastorePruneDatastoreResponse, error)
	// ListDatastorePxarFileDownload GET /admin/datastore/{store}/pxar-file-download
	// Download single file from pxar file of a backup snapshot. Only works if it's not encrypted.
	ListDatastorePxarFileDownload(ctx context.Context, store string, params *ListDatastorePxarFileDownloadParams) error
	// ListDatastoreRrd GET /admin/datastore/{store}/rrd
	// Read datastore stats
	ListDatastoreRrd(ctx context.Context, store string, params *ListDatastoreRrdParams) error
	// UpdateDatastoreS3Refresh PUT /admin/datastore/{store}/s3-refresh
	// Refresh datastore contents from S3 to local cache store.
	UpdateDatastoreS3Refresh(ctx context.Context, store string) (*UpdateDatastoreS3RefreshResponse, error)
	// DeleteDatastoreSnapshots DELETE /admin/datastore/{store}/snapshots
	// Delete backup snapshot.
	DeleteDatastoreSnapshots(ctx context.Context, store string, params *DeleteDatastoreSnapshotsParams) error
	// ListDatastoreSnapshots GET /admin/datastore/{store}/snapshots
	// List backup snapshots.
	ListDatastoreSnapshots(ctx context.Context, store string, params *ListDatastoreSnapshotsParams) (*ListDatastoreSnapshotsResponse, error)
	// ListDatastoreStatus GET /admin/datastore/{store}/status
	// Get datastore status.
	ListDatastoreStatus(ctx context.Context, store string, params *ListDatastoreStatusParams) (*ListDatastoreStatusResponse, error)
	// CreateDatastoreUnmount POST /admin/datastore/{store}/unmount
	// Unmount a removable device that is associated with the datastore
	CreateDatastoreUnmount(ctx context.Context, store string) (*CreateDatastoreUnmountResponse, error)
	// CreateDatastoreUploadBackupLog POST /admin/datastore/{store}/upload-backup-log
	// Upload the client backup log file into a backup snapshot ('client.log.blob').
	CreateDatastoreUploadBackupLog(ctx context.Context, store string, params *CreateDatastoreUploadBackupLogParams) error
	// CreateDatastoreVerify POST /admin/datastore/{store}/verify
	// Verify backups.  This function can verify a single backup snapshot, all backups from a backup group, or all backups in the datastore.
	CreateDatastoreVerify(ctx context.Context, store string, params *CreateDatastoreVerifyParams) (*CreateDatastoreVerifyResponse, error)
	// ListGc GET /admin/gc
	// List all GC jobs (max one per datastore)
	ListGc(ctx context.Context, params *ListGcParams) (*ListGcResponse, error)
	// GetGc GET /admin/gc/{store}
	// List all GC jobs (max one per datastore)
	GetGc(ctx context.Context, store string) (*GetGcResponse, error)
	// ListMetrics GET /admin/metrics
	// List configured metric servers.
	ListMetrics(ctx context.Context) (*ListMetricsResponse, error)
	// ListPrune GET /admin/prune
	// List all prune jobs
	ListPrune(ctx context.Context, params *ListPruneParams) (*ListPruneResponse, error)
	// GetPrune GET /admin/prune/{id}
	// Directory index.
	GetPrune(ctx context.Context, id string) error
	// CreatePruneRun POST /admin/prune/{id}/run
	// Runs a prune job manually.
	CreatePruneRun(ctx context.Context, id string) error
	// GetS3 GET /admin/s3/{s3-endpoint-id}
	// Directory index.
	GetS3(ctx context.Context, s3EndpointId string) error
	// UpdateS3Check PUT /admin/s3/{s3-endpoint-id}/check
	// Perform basic sanity check for given s3 client configuration
	UpdateS3Check(ctx context.Context, s3EndpointId string, params *UpdateS3CheckParams) error
	// UpdateS3ResetCounters PUT /admin/s3/{s3-endpoint-id}/reset-counters
	// Reset the S3 request counters for matching endpoint, bucket or datastore (if prefix is given).
	UpdateS3ResetCounters(ctx context.Context, s3EndpointId string, params *UpdateS3ResetCountersParams) error
	// ListSync GET /admin/sync
	// List all configured sync jobs
	ListSync(ctx context.Context, params *ListSyncParams) (*ListSyncResponse, error)
	// GetSync GET /admin/sync/{id}
	// Directory index.
	GetSync(ctx context.Context, id string) error
	// CreateSyncRun POST /admin/sync/{id}/run
	// Runs the sync jobs manually.
	CreateSyncRun(ctx context.Context, id string) error
	// ListTrafficControl GET /admin/traffic-control
	// Show current traffic for all traffic control rules.
	ListTrafficControl(ctx context.Context) (*ListTrafficControlResponse, error)
	// ListVerify GET /admin/verify
	// List all verification jobs
	ListVerify(ctx context.Context, params *ListVerifyParams) (*ListVerifyResponse, error)
	// GetVerify GET /admin/verify/{id}
	// Directory index.
	GetVerify(ctx context.Context, id string) error
	// CreateVerifyRun POST /admin/verify/{id}/run
	// Runs a verification job manually.
	CreateVerifyRun(ctx context.Context, id string) error
}

// New constructs a Service backed by the given pkg/client.Client.
// The client owns authentication, TLS, retries, and logging; this
// service only translates between typed Go shapes and the raw client.
func New(c client.Client) Service {
	if c == nil {
		panic("admin: New called with nil client")
	}
	return &service{c: c}
}

type service struct {
	c client.Client
}

// ListAdmin implements Service.ListAdmin. GET /admin.
func (s *service) ListAdmin(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("admin.ListAdmin: ctx must not be nil")
	}
	path := "/admin"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.ListAdmin: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.ListAdmin: nil response from client")
	}
	_ = resp
	return nil
}

// ListDatastoreResponse mirrors the shape returned by GET /admin/datastore.
type ListDatastoreResponse []json.RawMessage

// ListDatastore implements Service.ListDatastore. GET /admin/datastore.
func (s *service) ListDatastore(ctx context.Context) (*ListDatastoreResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.ListDatastore: ctx must not be nil")
	}
	path := "/admin/datastore"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastore: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.ListDatastore: nil response from client")
	}
	if resp.Data == nil {
		out := ListDatastoreResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastore: re-marshal data: %w", err)
	}
	out := &ListDatastoreResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastore: unmarshal data: %w", err)
	}
	return out, nil
}

// GetDatastore implements Service.GetDatastore. GET /admin/datastore/{store}.
func (s *service) GetDatastore(ctx context.Context, store string) error {
	if ctx == nil {
		return fmt.Errorf("admin.GetDatastore: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s", url.PathEscape(store))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.GetDatastore: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.GetDatastore: nil response from client")
	}
	_ = resp
	return nil
}

// ListDatastoreActiveOperations implements Service.ListDatastoreActiveOperations. GET /admin/datastore/{store}/active-operations.
func (s *service) ListDatastoreActiveOperations(ctx context.Context, store string) error {
	if ctx == nil {
		return fmt.Errorf("admin.ListDatastoreActiveOperations: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/active-operations", url.PathEscape(store))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.ListDatastoreActiveOperations: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.ListDatastoreActiveOperations: nil response from client")
	}
	_ = resp
	return nil
}

// ListDatastoreCatalogParams is the request payload for ListDatastoreCatalog.
type ListDatastoreCatalogParams struct {
	// ArchiveName Backup archive name.
	ArchiveName *string `json:"archive-name,omitempty"`
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupTime Backup time (Unix epoch.)
	BackupTime int64 `json:"backup-time"`
	// BackupType Backup types.
	BackupType string `json:"backup-type"`
	// Filepath Base64 encoded path.
	Filepath string `json:"filepath"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// ListDatastoreCatalog implements Service.ListDatastoreCatalog. GET /admin/datastore/{store}/catalog.
func (s *service) ListDatastoreCatalog(ctx context.Context, store string, params *ListDatastoreCatalogParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.ListDatastoreCatalog: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/catalog", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.ListDatastoreCatalog: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.ListDatastoreCatalog: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.ListDatastoreCatalog: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.ListDatastoreCatalog: nil response from client")
	}
	_ = resp
	return nil
}

// CreateDatastoreChangeOwnerParams is the request payload for CreateDatastoreChangeOwner.
type CreateDatastoreChangeOwnerParams struct {
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupType Backup types.
	BackupType string `json:"backup-type"`
	// NewOwner Authentication ID
	NewOwner string `json:"new-owner"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// CreateDatastoreChangeOwner implements Service.CreateDatastoreChangeOwner. POST /admin/datastore/{store}/change-owner.
func (s *service) CreateDatastoreChangeOwner(ctx context.Context, store string, params *CreateDatastoreChangeOwnerParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.CreateDatastoreChangeOwner: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/change-owner", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.CreateDatastoreChangeOwner: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.CreateDatastoreChangeOwner: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.CreateDatastoreChangeOwner: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.CreateDatastoreChangeOwner: nil response from client")
	}
	_ = resp
	return nil
}

// ListDatastoreDownloadParams is the request payload for ListDatastoreDownload.
type ListDatastoreDownloadParams struct {
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupTime Backup time (Unix epoch.)
	BackupTime int64 `json:"backup-time"`
	// BackupType Backup type.
	BackupType string `json:"backup-type"`
	// FileName Backup archive name.
	FileName string `json:"file-name"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// ListDatastoreDownload implements Service.ListDatastoreDownload. GET /admin/datastore/{store}/download.
func (s *service) ListDatastoreDownload(ctx context.Context, store string, params *ListDatastoreDownloadParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.ListDatastoreDownload: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/download", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.ListDatastoreDownload: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.ListDatastoreDownload: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.ListDatastoreDownload: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.ListDatastoreDownload: nil response from client")
	}
	_ = resp
	return nil
}

// ListDatastoreDownloadDecodedParams is the request payload for ListDatastoreDownloadDecoded.
type ListDatastoreDownloadDecodedParams struct {
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupTime Backup time (Unix epoch.)
	BackupTime int64 `json:"backup-time"`
	// BackupType Backup type.
	BackupType string `json:"backup-type"`
	// FileName Backup archive name.
	FileName string `json:"file-name"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// ListDatastoreDownloadDecoded implements Service.ListDatastoreDownloadDecoded. GET /admin/datastore/{store}/download-decoded.
func (s *service) ListDatastoreDownloadDecoded(ctx context.Context, store string, params *ListDatastoreDownloadDecodedParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.ListDatastoreDownloadDecoded: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/download-decoded", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.ListDatastoreDownloadDecoded: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.ListDatastoreDownloadDecoded: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.ListDatastoreDownloadDecoded: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.ListDatastoreDownloadDecoded: nil response from client")
	}
	_ = resp
	return nil
}

// ListDatastoreFilesParams is the request payload for ListDatastoreFiles.
type ListDatastoreFilesParams struct {
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupTime Backup time (Unix epoch.)
	BackupTime int64 `json:"backup-time"`
	// BackupType Backup types.
	BackupType string `json:"backup-type"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// ListDatastoreFilesResponse mirrors the shape returned by GET /admin/datastore/{store}/files.
type ListDatastoreFilesResponse []json.RawMessage

// ListDatastoreFiles implements Service.ListDatastoreFiles. GET /admin/datastore/{store}/files.
func (s *service) ListDatastoreFiles(ctx context.Context, store string, params *ListDatastoreFilesParams) (*ListDatastoreFilesResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.ListDatastoreFiles: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/files", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.ListDatastoreFiles: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.ListDatastoreFiles: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreFiles: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.ListDatastoreFiles: nil response from client")
	}
	if resp.Data == nil {
		out := ListDatastoreFilesResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreFiles: re-marshal data: %w", err)
	}
	out := &ListDatastoreFilesResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreFiles: unmarshal data: %w", err)
	}
	return out, nil
}

// ListDatastoreGcResponse mirrors the shape returned by GET /admin/datastore/{store}/gc.
type ListDatastoreGcResponse struct {
	// CacheStats Garbage collection cache statistics
	CacheStats json.RawMessage `json:"cache-stats,omitempty"`
	// DiskBytes Bytes used on disk.
	DiskBytes int64 `json:"disk-bytes"`
	// DiskChunks Chunks used on disk.
	DiskChunks int64 `json:"disk-chunks"`
	// Duration Duration of last gc run
	Duration *int64 `json:"duration,omitempty"`
	// IndexDataBytes Sum of bytes referred by index files.
	IndexDataBytes int64 `json:"index-data-bytes"`
	// IndexFileCount Number of processed index files.
	IndexFileCount int64 `json:"index-file-count"`
	// LastRunEndtime Endtime of the last gc run
	LastRunEndtime *int64 `json:"last-run-endtime,omitempty"`
	// LastRunState State of the last gc run
	LastRunState *string `json:"last-run-state,omitempty"`
	// NextRun Time of the next gc run
	NextRun *int64 `json:"next-run,omitempty"`
	// PendingBytes Sum of pending bytes (pending removal - kept for safety).
	PendingBytes int64 `json:"pending-bytes"`
	// PendingChunks Number of pending chunks (pending removal - kept for safety).
	PendingChunks int64 `json:"pending-chunks"`
	// RemovedBad Number of chunks marked as .bad by verify that have been removed by GC.
	RemovedBad int64 `json:"removed-bad"`
	// RemovedBytes Sum of removed bytes.
	RemovedBytes int64 `json:"removed-bytes"`
	// RemovedChunks Number of removed chunks.
	RemovedChunks int64 `json:"removed-chunks"`
	// Schedule Schedule of the gc job
	Schedule *string `json:"schedule,omitempty"`
	// StillBad Number of chunks still marked as .bad after garbage collection.
	StillBad int64 `json:"still-bad"`
	// Store Datastore
	Store string `json:"store"`
	// Upid Unique Process/Task Identifier
	Upid *string `json:"upid,omitempty"`
}

// ListDatastoreGc implements Service.ListDatastoreGc. GET /admin/datastore/{store}/gc.
func (s *service) ListDatastoreGc(ctx context.Context, store string) (*ListDatastoreGcResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.ListDatastoreGc: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/gc", url.PathEscape(store))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreGc: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.ListDatastoreGc: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("admin.ListDatastoreGc: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreGc: re-marshal data: %w", err)
	}
	out := &ListDatastoreGcResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreGc: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDatastoreGcResponse is the raw JSON returned by POST /admin/datastore/{store}/gc.
type CreateDatastoreGcResponse = json.RawMessage

// CreateDatastoreGc implements Service.CreateDatastoreGc. POST /admin/datastore/{store}/gc.
func (s *service) CreateDatastoreGc(ctx context.Context, store string) (*CreateDatastoreGcResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.CreateDatastoreGc: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/gc", url.PathEscape(store))
	var body map[string]interface{}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreGc: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.CreateDatastoreGc: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDatastoreGcResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreGc: re-marshal data: %w", err)
	}
	out := &CreateDatastoreGcResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreGc: unmarshal data: %w", err)
	}
	return out, nil
}

// ListDatastoreGroupNotesParams is the request payload for ListDatastoreGroupNotes.
type ListDatastoreGroupNotesParams struct {
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupType Backup types.
	BackupType string `json:"backup-type"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// ListDatastoreGroupNotes implements Service.ListDatastoreGroupNotes. GET /admin/datastore/{store}/group-notes.
func (s *service) ListDatastoreGroupNotes(ctx context.Context, store string, params *ListDatastoreGroupNotesParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.ListDatastoreGroupNotes: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/group-notes", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.ListDatastoreGroupNotes: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.ListDatastoreGroupNotes: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.ListDatastoreGroupNotes: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.ListDatastoreGroupNotes: nil response from client")
	}
	_ = resp
	return nil
}

// UpdateDatastoreGroupNotesParams is the request payload for UpdateDatastoreGroupNotes.
type UpdateDatastoreGroupNotesParams struct {
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupType Backup types.
	BackupType string `json:"backup-type"`
	// Notes A multiline text.
	Notes string `json:"notes"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// UpdateDatastoreGroupNotes implements Service.UpdateDatastoreGroupNotes. PUT /admin/datastore/{store}/group-notes.
func (s *service) UpdateDatastoreGroupNotes(ctx context.Context, store string, params *UpdateDatastoreGroupNotesParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.UpdateDatastoreGroupNotes: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/group-notes", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.UpdateDatastoreGroupNotes: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.UpdateDatastoreGroupNotes: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.UpdateDatastoreGroupNotes: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.UpdateDatastoreGroupNotes: nil response from client")
	}
	_ = resp
	return nil
}

// DeleteDatastoreGroupsParams is the request payload for DeleteDatastoreGroups.
type DeleteDatastoreGroupsParams struct {
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupType Backup types.
	BackupType string `json:"backup-type"`
	// ErrorOnProtected Return error when group cannot be deleted because of protected snapshots
	ErrorOnProtected *bool `json:"error-on-protected,omitempty"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// DeleteDatastoreGroupsResponse mirrors the shape returned by DELETE /admin/datastore/{store}/groups.
type DeleteDatastoreGroupsResponse struct {
	// ProtectedSnapshots Number of entities
	ProtectedSnapshots int64 `json:"protected-snapshots"`
	// RemovedGroups Number of entities
	RemovedGroups int64 `json:"removed-groups"`
	// RemovedSnapshots Number of entities
	RemovedSnapshots int64 `json:"removed-snapshots"`
}

// DeleteDatastoreGroups implements Service.DeleteDatastoreGroups. DELETE /admin/datastore/{store}/groups.
func (s *service) DeleteDatastoreGroups(ctx context.Context, store string, params *DeleteDatastoreGroupsParams) (*DeleteDatastoreGroupsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.DeleteDatastoreGroups: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/groups", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.DeleteDatastoreGroups: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.DeleteDatastoreGroups: decode params: %w", err)
		}
	}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.DeleteDatastoreGroups: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.DeleteDatastoreGroups: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("admin.DeleteDatastoreGroups: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.DeleteDatastoreGroups: re-marshal data: %w", err)
	}
	out := &DeleteDatastoreGroupsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.DeleteDatastoreGroups: unmarshal data: %w", err)
	}
	return out, nil
}

// ListDatastoreGroupsParams is the request payload for ListDatastoreGroups.
type ListDatastoreGroupsParams struct {
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// ListDatastoreGroupsResponse mirrors the shape returned by GET /admin/datastore/{store}/groups.
type ListDatastoreGroupsResponse []json.RawMessage

// ListDatastoreGroups implements Service.ListDatastoreGroups. GET /admin/datastore/{store}/groups.
func (s *service) ListDatastoreGroups(ctx context.Context, store string, params *ListDatastoreGroupsParams) (*ListDatastoreGroupsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.ListDatastoreGroups: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/groups", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.ListDatastoreGroups: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.ListDatastoreGroups: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreGroups: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.ListDatastoreGroups: nil response from client")
	}
	if resp.Data == nil {
		out := ListDatastoreGroupsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreGroups: re-marshal data: %w", err)
	}
	out := &ListDatastoreGroupsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreGroups: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDatastoreMountResponse is the raw JSON returned by POST /admin/datastore/{store}/mount.
type CreateDatastoreMountResponse = json.RawMessage

// CreateDatastoreMount implements Service.CreateDatastoreMount. POST /admin/datastore/{store}/mount.
func (s *service) CreateDatastoreMount(ctx context.Context, store string) (*CreateDatastoreMountResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.CreateDatastoreMount: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/mount", url.PathEscape(store))
	var body map[string]interface{}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreMount: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.CreateDatastoreMount: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDatastoreMountResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreMount: re-marshal data: %w", err)
	}
	out := &CreateDatastoreMountResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreMount: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDatastoreMoveGroupParams is the request payload for CreateDatastoreMoveGroup.
type CreateDatastoreMoveGroupParams struct {
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupType Backup types.
	BackupType string `json:"backup-type"`
	// MergeGroup If the group already exists in the target namespace, merge snapshots into it. Requires matching ownership and non-overlapping snapshot times.
	MergeGroup *bool `json:"merge-group,omitempty"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
	// TargetNs Namespace.
	TargetNs *string `json:"target-ns,omitempty"`
}

// CreateDatastoreMoveGroupResponse is the raw JSON returned by POST /admin/datastore/{store}/move-group.
type CreateDatastoreMoveGroupResponse = json.RawMessage

// CreateDatastoreMoveGroup implements Service.CreateDatastoreMoveGroup. POST /admin/datastore/{store}/move-group.
func (s *service) CreateDatastoreMoveGroup(ctx context.Context, store string, params *CreateDatastoreMoveGroupParams) (*CreateDatastoreMoveGroupResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.CreateDatastoreMoveGroup: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/move-group", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.CreateDatastoreMoveGroup: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.CreateDatastoreMoveGroup: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreMoveGroup: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.CreateDatastoreMoveGroup: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDatastoreMoveGroupResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreMoveGroup: re-marshal data: %w", err)
	}
	out := &CreateDatastoreMoveGroupResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreMoveGroup: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDatastoreMoveNamespaceParams is the request payload for CreateDatastoreMoveNamespace.
type CreateDatastoreMoveNamespaceParams struct {
	// DeleteSource Remove the source namespace after moving all contents. Defaults to true.
	DeleteSource *bool `json:"delete-source,omitempty"`
	// MaxDepth How many levels of namespaces should be operated on (0 == no recursion)
	MaxDepth *int64 `json:"max-depth,omitempty"`
	// MergeGroups If a group with the same name already exists in the target namespace, merge snapshots into it. Requires matching ownership and non-overlapping snapshot times.
	MergeGroups *bool `json:"merge-groups,omitempty"`
	// Ns Namespace.
	Ns string `json:"ns"`
	// TargetNs Namespace.
	TargetNs string `json:"target-ns"`
}

// CreateDatastoreMoveNamespaceResponse is the raw JSON returned by POST /admin/datastore/{store}/move-namespace.
type CreateDatastoreMoveNamespaceResponse = json.RawMessage

// CreateDatastoreMoveNamespace implements Service.CreateDatastoreMoveNamespace. POST /admin/datastore/{store}/move-namespace.
func (s *service) CreateDatastoreMoveNamespace(ctx context.Context, store string, params *CreateDatastoreMoveNamespaceParams) (*CreateDatastoreMoveNamespaceResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.CreateDatastoreMoveNamespace: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/move-namespace", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.CreateDatastoreMoveNamespace: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.CreateDatastoreMoveNamespace: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreMoveNamespace: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.CreateDatastoreMoveNamespace: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDatastoreMoveNamespaceResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreMoveNamespace: re-marshal data: %w", err)
	}
	out := &CreateDatastoreMoveNamespaceResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreMoveNamespace: unmarshal data: %w", err)
	}
	return out, nil
}

// DeleteDatastoreNamespaceParams is the request payload for DeleteDatastoreNamespace.
type DeleteDatastoreNamespaceParams struct {
	// DeleteGroups If set, all groups will be destroyed in the whole hierarchy below andincluding `ns`. If not set, only empty namespaces will be pruned.
	DeleteGroups *bool `json:"delete-groups,omitempty"`
	// ErrorOnProtected Return error when namespace cannot be deleted because of protected snapshots
	ErrorOnProtected *bool `json:"error-on-protected,omitempty"`
	// Ns Namespace.
	Ns string `json:"ns"`
}

// DeleteDatastoreNamespace implements Service.DeleteDatastoreNamespace. DELETE /admin/datastore/{store}/namespace.
func (s *service) DeleteDatastoreNamespace(ctx context.Context, store string, params *DeleteDatastoreNamespaceParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.DeleteDatastoreNamespace: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/namespace", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.DeleteDatastoreNamespace: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.DeleteDatastoreNamespace: decode params: %w", err)
		}
	}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.DeleteDatastoreNamespace: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.DeleteDatastoreNamespace: nil response from client")
	}
	_ = resp
	return nil
}

// ListDatastoreNamespaceParams is the request payload for ListDatastoreNamespace.
type ListDatastoreNamespaceParams struct {
	// MaxDepth How many levels of namespaces should be operated on (0 == no recursion)
	MaxDepth *int64 `json:"max-depth,omitempty"`
	// Parent Namespace.
	Parent *string `json:"parent,omitempty"`
}

// ListDatastoreNamespaceResponse mirrors the shape returned by GET /admin/datastore/{store}/namespace.
type ListDatastoreNamespaceResponse []json.RawMessage

// ListDatastoreNamespace implements Service.ListDatastoreNamespace. GET /admin/datastore/{store}/namespace.
func (s *service) ListDatastoreNamespace(ctx context.Context, store string, params *ListDatastoreNamespaceParams) (*ListDatastoreNamespaceResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.ListDatastoreNamespace: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/namespace", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.ListDatastoreNamespace: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.ListDatastoreNamespace: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreNamespace: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.ListDatastoreNamespace: nil response from client")
	}
	if resp.Data == nil {
		out := ListDatastoreNamespaceResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreNamespace: re-marshal data: %w", err)
	}
	out := &ListDatastoreNamespaceResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreNamespace: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDatastoreNamespaceParams is the request payload for CreateDatastoreNamespace.
type CreateDatastoreNamespaceParams struct {
	// Name The name of the new namespace to add at the parent.
	Name string `json:"name"`
	// Parent Namespace.
	Parent *string `json:"parent,omitempty"`
}

// CreateDatastoreNamespaceResponse is the raw JSON returned by POST /admin/datastore/{store}/namespace.
type CreateDatastoreNamespaceResponse = json.RawMessage

// CreateDatastoreNamespace implements Service.CreateDatastoreNamespace. POST /admin/datastore/{store}/namespace.
func (s *service) CreateDatastoreNamespace(ctx context.Context, store string, params *CreateDatastoreNamespaceParams) (*CreateDatastoreNamespaceResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.CreateDatastoreNamespace: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/namespace", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.CreateDatastoreNamespace: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.CreateDatastoreNamespace: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreNamespace: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.CreateDatastoreNamespace: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDatastoreNamespaceResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreNamespace: re-marshal data: %w", err)
	}
	out := &CreateDatastoreNamespaceResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreNamespace: unmarshal data: %w", err)
	}
	return out, nil
}

// ListDatastoreNotesParams is the request payload for ListDatastoreNotes.
type ListDatastoreNotesParams struct {
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupTime Backup time (Unix epoch.)
	BackupTime int64 `json:"backup-time"`
	// BackupType Backup types.
	BackupType string `json:"backup-type"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// ListDatastoreNotes implements Service.ListDatastoreNotes. GET /admin/datastore/{store}/notes.
func (s *service) ListDatastoreNotes(ctx context.Context, store string, params *ListDatastoreNotesParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.ListDatastoreNotes: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/notes", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.ListDatastoreNotes: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.ListDatastoreNotes: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.ListDatastoreNotes: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.ListDatastoreNotes: nil response from client")
	}
	_ = resp
	return nil
}

// UpdateDatastoreNotesParams is the request payload for UpdateDatastoreNotes.
type UpdateDatastoreNotesParams struct {
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupTime Backup time (Unix epoch.)
	BackupTime int64 `json:"backup-time"`
	// BackupType Backup types.
	BackupType string `json:"backup-type"`
	// Notes A multiline text.
	Notes string `json:"notes"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// UpdateDatastoreNotes implements Service.UpdateDatastoreNotes. PUT /admin/datastore/{store}/notes.
func (s *service) UpdateDatastoreNotes(ctx context.Context, store string, params *UpdateDatastoreNotesParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.UpdateDatastoreNotes: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/notes", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.UpdateDatastoreNotes: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.UpdateDatastoreNotes: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.UpdateDatastoreNotes: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.UpdateDatastoreNotes: nil response from client")
	}
	_ = resp
	return nil
}

// ListDatastoreProtectedParams is the request payload for ListDatastoreProtected.
type ListDatastoreProtectedParams struct {
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupTime Backup time (Unix epoch.)
	BackupTime int64 `json:"backup-time"`
	// BackupType Backup types.
	BackupType string `json:"backup-type"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// ListDatastoreProtected implements Service.ListDatastoreProtected. GET /admin/datastore/{store}/protected.
func (s *service) ListDatastoreProtected(ctx context.Context, store string, params *ListDatastoreProtectedParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.ListDatastoreProtected: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/protected", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.ListDatastoreProtected: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.ListDatastoreProtected: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.ListDatastoreProtected: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.ListDatastoreProtected: nil response from client")
	}
	_ = resp
	return nil
}

// UpdateDatastoreProtectedParams is the request payload for UpdateDatastoreProtected.
type UpdateDatastoreProtectedParams struct {
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupTime Backup time (Unix epoch.)
	BackupTime int64 `json:"backup-time"`
	// BackupType Backup types.
	BackupType string `json:"backup-type"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
	// Protected Enable/disable protection.
	Protected bool `json:"protected"`
}

// UpdateDatastoreProtected implements Service.UpdateDatastoreProtected. PUT /admin/datastore/{store}/protected.
func (s *service) UpdateDatastoreProtected(ctx context.Context, store string, params *UpdateDatastoreProtectedParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.UpdateDatastoreProtected: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/protected", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.UpdateDatastoreProtected: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.UpdateDatastoreProtected: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.UpdateDatastoreProtected: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.UpdateDatastoreProtected: nil response from client")
	}
	_ = resp
	return nil
}

// CreateDatastorePruneParams is the request payload for CreateDatastorePrune.
type CreateDatastorePruneParams struct {
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupType Backup types.
	BackupType string `json:"backup-type"`
	// DryRun Just show what prune would do, but do not delete anything.
	DryRun *bool `json:"dry-run,omitempty"`
	// KeepDaily Number of daily backups to keep.
	KeepDaily *int64 `json:"keep-daily,omitempty"`
	// KeepHourly Number of hourly backups to keep.
	KeepHourly *int64 `json:"keep-hourly,omitempty"`
	// KeepLast Number of backups to keep.
	KeepLast *int64 `json:"keep-last,omitempty"`
	// KeepMonthly Number of monthly backups to keep.
	KeepMonthly *int64 `json:"keep-monthly,omitempty"`
	// KeepWeekly Number of weekly backups to keep.
	KeepWeekly *int64 `json:"keep-weekly,omitempty"`
	// KeepYearly Number of yearly backups to keep.
	KeepYearly *int64 `json:"keep-yearly,omitempty"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
	// UseTask Spins up an asynchronous task that does the work.
	UseTask *bool `json:"use-task,omitempty"`
}

// CreateDatastorePruneResponse mirrors the shape returned by POST /admin/datastore/{store}/prune.
type CreateDatastorePruneResponse []json.RawMessage

// CreateDatastorePrune implements Service.CreateDatastorePrune. POST /admin/datastore/{store}/prune.
func (s *service) CreateDatastorePrune(ctx context.Context, store string, params *CreateDatastorePruneParams) (*CreateDatastorePruneResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.CreateDatastorePrune: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/prune", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.CreateDatastorePrune: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.CreateDatastorePrune: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastorePrune: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.CreateDatastorePrune: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDatastorePruneResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastorePrune: re-marshal data: %w", err)
	}
	out := &CreateDatastorePruneResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastorePrune: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDatastorePruneDatastoreParams is the request payload for CreateDatastorePruneDatastore.
type CreateDatastorePruneDatastoreParams struct {
	// DryRun Just show what prune would do, but do not delete anything.
	DryRun *bool `json:"dry-run,omitempty"`
	// KeepDaily Number of daily backups to keep.
	KeepDaily *int64 `json:"keep-daily,omitempty"`
	// KeepHourly Number of hourly backups to keep.
	KeepHourly *int64 `json:"keep-hourly,omitempty"`
	// KeepLast Number of backups to keep.
	KeepLast *int64 `json:"keep-last,omitempty"`
	// KeepMonthly Number of monthly backups to keep.
	KeepMonthly *int64 `json:"keep-monthly,omitempty"`
	// KeepWeekly Number of weekly backups to keep.
	KeepWeekly *int64 `json:"keep-weekly,omitempty"`
	// KeepYearly Number of yearly backups to keep.
	KeepYearly *int64 `json:"keep-yearly,omitempty"`
	// MaxDepth How many levels of namespaces should be operated on (0 == no recursion, empty == automatic full recursion, namespace depths reduce maximum allowed value)
	MaxDepth *int64 `json:"max-depth,omitempty"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// CreateDatastorePruneDatastoreResponse is the raw JSON returned by POST /admin/datastore/{store}/prune-datastore.
type CreateDatastorePruneDatastoreResponse = json.RawMessage

// CreateDatastorePruneDatastore implements Service.CreateDatastorePruneDatastore. POST /admin/datastore/{store}/prune-datastore.
func (s *service) CreateDatastorePruneDatastore(ctx context.Context, store string, params *CreateDatastorePruneDatastoreParams) (*CreateDatastorePruneDatastoreResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.CreateDatastorePruneDatastore: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/prune-datastore", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.CreateDatastorePruneDatastore: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.CreateDatastorePruneDatastore: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastorePruneDatastore: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.CreateDatastorePruneDatastore: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDatastorePruneDatastoreResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastorePruneDatastore: re-marshal data: %w", err)
	}
	out := &CreateDatastorePruneDatastoreResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastorePruneDatastore: unmarshal data: %w", err)
	}
	return out, nil
}

// ListDatastorePxarFileDownloadParams is the request payload for ListDatastorePxarFileDownload.
type ListDatastorePxarFileDownloadParams struct {
	// ArchiveName Backup archive name.
	ArchiveName *string `json:"archive-name,omitempty"`
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupTime Backup time (Unix epoch.)
	BackupTime int64 `json:"backup-time"`
	// BackupType Backup type.
	BackupType string `json:"backup-type"`
	// Filepath Base64 encoded path
	Filepath string `json:"filepath"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
	// Tar Download as .tar.zst
	Tar *bool `json:"tar,omitempty"`
}

// ListDatastorePxarFileDownload implements Service.ListDatastorePxarFileDownload. GET /admin/datastore/{store}/pxar-file-download.
func (s *service) ListDatastorePxarFileDownload(ctx context.Context, store string, params *ListDatastorePxarFileDownloadParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.ListDatastorePxarFileDownload: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/pxar-file-download", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.ListDatastorePxarFileDownload: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.ListDatastorePxarFileDownload: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.ListDatastorePxarFileDownload: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.ListDatastorePxarFileDownload: nil response from client")
	}
	_ = resp
	return nil
}

// ListDatastoreRrdParams is the request payload for ListDatastoreRrd.
type ListDatastoreRrdParams struct {
	// Cf RRD consolidation mode
	Cf string `json:"cf"`
	// Timeframe RRD time frame
	Timeframe string `json:"timeframe"`
}

// ListDatastoreRrd implements Service.ListDatastoreRrd. GET /admin/datastore/{store}/rrd.
func (s *service) ListDatastoreRrd(ctx context.Context, store string, params *ListDatastoreRrdParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.ListDatastoreRrd: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/rrd", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.ListDatastoreRrd: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.ListDatastoreRrd: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.ListDatastoreRrd: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.ListDatastoreRrd: nil response from client")
	}
	_ = resp
	return nil
}

// UpdateDatastoreS3RefreshResponse is the raw JSON returned by PUT /admin/datastore/{store}/s3-refresh.
type UpdateDatastoreS3RefreshResponse = json.RawMessage

// UpdateDatastoreS3Refresh implements Service.UpdateDatastoreS3Refresh. PUT /admin/datastore/{store}/s3-refresh.
func (s *service) UpdateDatastoreS3Refresh(ctx context.Context, store string) (*UpdateDatastoreS3RefreshResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.UpdateDatastoreS3Refresh: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/s3-refresh", url.PathEscape(store))
	var body map[string]interface{}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.UpdateDatastoreS3Refresh: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.UpdateDatastoreS3Refresh: nil response from client")
	}
	if resp.Data == nil {
		out := UpdateDatastoreS3RefreshResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.UpdateDatastoreS3Refresh: re-marshal data: %w", err)
	}
	out := &UpdateDatastoreS3RefreshResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.UpdateDatastoreS3Refresh: unmarshal data: %w", err)
	}
	return out, nil
}

// DeleteDatastoreSnapshotsParams is the request payload for DeleteDatastoreSnapshots.
type DeleteDatastoreSnapshotsParams struct {
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupTime Backup time (Unix epoch.)
	BackupTime int64 `json:"backup-time"`
	// BackupType Backup types.
	BackupType string `json:"backup-type"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// DeleteDatastoreSnapshots implements Service.DeleteDatastoreSnapshots. DELETE /admin/datastore/{store}/snapshots.
func (s *service) DeleteDatastoreSnapshots(ctx context.Context, store string, params *DeleteDatastoreSnapshotsParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.DeleteDatastoreSnapshots: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/snapshots", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.DeleteDatastoreSnapshots: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.DeleteDatastoreSnapshots: decode params: %w", err)
		}
	}
	resp, err := s.c.DeleteRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.DeleteDatastoreSnapshots: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.DeleteDatastoreSnapshots: nil response from client")
	}
	_ = resp
	return nil
}

// ListDatastoreSnapshotsParams is the request payload for ListDatastoreSnapshots.
type ListDatastoreSnapshotsParams struct {
	// BackupId Backup ID.
	BackupId *string `json:"backup-id,omitempty"`
	// BackupType Backup types.
	BackupType *string `json:"backup-type,omitempty"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// ListDatastoreSnapshotsResponse mirrors the shape returned by GET /admin/datastore/{store}/snapshots.
type ListDatastoreSnapshotsResponse []json.RawMessage

// ListDatastoreSnapshots implements Service.ListDatastoreSnapshots. GET /admin/datastore/{store}/snapshots.
func (s *service) ListDatastoreSnapshots(ctx context.Context, store string, params *ListDatastoreSnapshotsParams) (*ListDatastoreSnapshotsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.ListDatastoreSnapshots: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/snapshots", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.ListDatastoreSnapshots: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.ListDatastoreSnapshots: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreSnapshots: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.ListDatastoreSnapshots: nil response from client")
	}
	if resp.Data == nil {
		out := ListDatastoreSnapshotsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreSnapshots: re-marshal data: %w", err)
	}
	out := &ListDatastoreSnapshotsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreSnapshots: unmarshal data: %w", err)
	}
	return out, nil
}

// ListDatastoreStatusParams is the request payload for ListDatastoreStatus.
type ListDatastoreStatusParams struct {
	// Verbose Include additional information like snapshot counts and GC status.
	Verbose *bool `json:"verbose,omitempty"`
}

// ListDatastoreStatusResponse mirrors the shape returned by GET /admin/datastore/{store}/status.
type ListDatastoreStatusResponse struct {
	// Avail Available space (bytes).
	Avail int64 `json:"avail"`
	// BackendType Datastore backend type
	BackendType string `json:"backend-type"`
	// Counts Counts of groups/snapshots per BackupType.
	Counts json.RawMessage `json:"counts,omitempty"`
	// GcStatus Garbage collection status.
	GcStatus json.RawMessage `json:"gc-status,omitempty"`
	// S3Statistics Statistics specific to the S3 backend
	S3Statistics json.RawMessage `json:"s3-statistics,omitempty"`
	// Total Total space (bytes).
	Total int64 `json:"total"`
	// Used Used space (bytes).
	Used int64 `json:"used"`
}

// ListDatastoreStatus implements Service.ListDatastoreStatus. GET /admin/datastore/{store}/status.
func (s *service) ListDatastoreStatus(ctx context.Context, store string, params *ListDatastoreStatusParams) (*ListDatastoreStatusResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.ListDatastoreStatus: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/status", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.ListDatastoreStatus: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.ListDatastoreStatus: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreStatus: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.ListDatastoreStatus: nil response from client")
	}
	if resp.Data == nil {
		return nil, fmt.Errorf("admin.ListDatastoreStatus: empty data in response (code=%d)", resp.Code)
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreStatus: re-marshal data: %w", err)
	}
	out := &ListDatastoreStatusResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.ListDatastoreStatus: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDatastoreUnmountResponse is the raw JSON returned by POST /admin/datastore/{store}/unmount.
type CreateDatastoreUnmountResponse = json.RawMessage

// CreateDatastoreUnmount implements Service.CreateDatastoreUnmount. POST /admin/datastore/{store}/unmount.
func (s *service) CreateDatastoreUnmount(ctx context.Context, store string) (*CreateDatastoreUnmountResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.CreateDatastoreUnmount: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/unmount", url.PathEscape(store))
	var body map[string]interface{}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreUnmount: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.CreateDatastoreUnmount: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDatastoreUnmountResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreUnmount: re-marshal data: %w", err)
	}
	out := &CreateDatastoreUnmountResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreUnmount: unmarshal data: %w", err)
	}
	return out, nil
}

// CreateDatastoreUploadBackupLogParams is the request payload for CreateDatastoreUploadBackupLog.
type CreateDatastoreUploadBackupLogParams struct {
	// BackupId Backup ID.
	BackupId string `json:"backup-id"`
	// BackupTime Backup time (Unix epoch.)
	BackupTime int64 `json:"backup-time"`
	// BackupType Backup type.
	BackupType string `json:"backup-type"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
}

// CreateDatastoreUploadBackupLog implements Service.CreateDatastoreUploadBackupLog. POST /admin/datastore/{store}/upload-backup-log.
func (s *service) CreateDatastoreUploadBackupLog(ctx context.Context, store string, params *CreateDatastoreUploadBackupLogParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.CreateDatastoreUploadBackupLog: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/upload-backup-log", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.CreateDatastoreUploadBackupLog: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.CreateDatastoreUploadBackupLog: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.CreateDatastoreUploadBackupLog: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.CreateDatastoreUploadBackupLog: nil response from client")
	}
	_ = resp
	return nil
}

// CreateDatastoreVerifyParams is the request payload for CreateDatastoreVerify.
type CreateDatastoreVerifyParams struct {
	// BackupId Backup ID.
	BackupId *string `json:"backup-id,omitempty"`
	// BackupTime Backup time (Unix epoch.)
	BackupTime *int64 `json:"backup-time,omitempty"`
	// BackupType Backup types.
	BackupType *string `json:"backup-type,omitempty"`
	// IgnoreVerified Do not verify backups that are already verified if their verification is not outdated.
	IgnoreVerified *bool `json:"ignore-verified,omitempty"`
	// MaxDepth How many levels of namespaces should be operated on (0 == no recursion)
	MaxDepth *int64 `json:"max-depth,omitempty"`
	// Ns Namespace.
	Ns *string `json:"ns,omitempty"`
	// OutdatedAfter Days after that a verification becomes outdated. (0 is deprecated)'
	OutdatedAfter *int64 `json:"outdated-after,omitempty"`
	// ReadThreads The number of threads to use for reading chunks in verify job.
	ReadThreads *int64 `json:"read-threads,omitempty"`
	// VerifyThreads The number of threads to use for verifying chunks in verify job.
	VerifyThreads *int64 `json:"verify-threads,omitempty"`
}

// CreateDatastoreVerifyResponse is the raw JSON returned by POST /admin/datastore/{store}/verify.
type CreateDatastoreVerifyResponse = json.RawMessage

// CreateDatastoreVerify implements Service.CreateDatastoreVerify. POST /admin/datastore/{store}/verify.
func (s *service) CreateDatastoreVerify(ctx context.Context, store string, params *CreateDatastoreVerifyParams) (*CreateDatastoreVerifyResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.CreateDatastoreVerify: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/datastore/%s/verify", url.PathEscape(store))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.CreateDatastoreVerify: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.CreateDatastoreVerify: decode params: %w", err)
		}
	}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreVerify: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.CreateDatastoreVerify: nil response from client")
	}
	if resp.Data == nil {
		out := CreateDatastoreVerifyResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreVerify: re-marshal data: %w", err)
	}
	out := &CreateDatastoreVerifyResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.CreateDatastoreVerify: unmarshal data: %w", err)
	}
	return out, nil
}

// ListGcParams is the request payload for ListGc.
type ListGcParams struct {
	// Store Datastore name.
	Store *string `json:"store,omitempty"`
}

// ListGcResponse mirrors the shape returned by GET /admin/gc.
type ListGcResponse []json.RawMessage

// ListGc implements Service.ListGc. GET /admin/gc.
func (s *service) ListGc(ctx context.Context, params *ListGcParams) (*ListGcResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.ListGc: ctx must not be nil")
	}
	path := "/admin/gc"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.ListGc: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.ListGc: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.ListGc: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.ListGc: nil response from client")
	}
	if resp.Data == nil {
		out := ListGcResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.ListGc: re-marshal data: %w", err)
	}
	out := &ListGcResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.ListGc: unmarshal data: %w", err)
	}
	return out, nil
}

// GetGcResponse mirrors the shape returned by GET /admin/gc/{store}.
type GetGcResponse []json.RawMessage

// GetGc implements Service.GetGc. GET /admin/gc/{store}.
func (s *service) GetGc(ctx context.Context, store string) (*GetGcResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.GetGc: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/gc/%s", url.PathEscape(store))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.GetGc: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.GetGc: nil response from client")
	}
	if resp.Data == nil {
		out := GetGcResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.GetGc: re-marshal data: %w", err)
	}
	out := &GetGcResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.GetGc: unmarshal data: %w", err)
	}
	return out, nil
}

// ListMetricsResponse mirrors the shape returned by GET /admin/metrics.
type ListMetricsResponse []json.RawMessage

// ListMetrics implements Service.ListMetrics. GET /admin/metrics.
func (s *service) ListMetrics(ctx context.Context) (*ListMetricsResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.ListMetrics: ctx must not be nil")
	}
	path := "/admin/metrics"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.ListMetrics: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.ListMetrics: nil response from client")
	}
	if resp.Data == nil {
		out := ListMetricsResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.ListMetrics: re-marshal data: %w", err)
	}
	out := &ListMetricsResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.ListMetrics: unmarshal data: %w", err)
	}
	return out, nil
}

// ListPruneParams is the request payload for ListPrune.
type ListPruneParams struct {
	// Store Datastore name.
	Store *string `json:"store,omitempty"`
}

// ListPruneResponse mirrors the shape returned by GET /admin/prune.
type ListPruneResponse []json.RawMessage

// ListPrune implements Service.ListPrune. GET /admin/prune.
func (s *service) ListPrune(ctx context.Context, params *ListPruneParams) (*ListPruneResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.ListPrune: ctx must not be nil")
	}
	path := "/admin/prune"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.ListPrune: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.ListPrune: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.ListPrune: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.ListPrune: nil response from client")
	}
	if resp.Data == nil {
		out := ListPruneResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.ListPrune: re-marshal data: %w", err)
	}
	out := &ListPruneResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.ListPrune: unmarshal data: %w", err)
	}
	return out, nil
}

// GetPrune implements Service.GetPrune. GET /admin/prune/{id}.
func (s *service) GetPrune(ctx context.Context, id string) error {
	if ctx == nil {
		return fmt.Errorf("admin.GetPrune: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/prune/%s", url.PathEscape(id))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.GetPrune: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.GetPrune: nil response from client")
	}
	_ = resp
	return nil
}

// CreatePruneRun implements Service.CreatePruneRun. POST /admin/prune/{id}/run.
func (s *service) CreatePruneRun(ctx context.Context, id string) error {
	if ctx == nil {
		return fmt.Errorf("admin.CreatePruneRun: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/prune/%s/run", url.PathEscape(id))
	var body map[string]interface{}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.CreatePruneRun: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.CreatePruneRun: nil response from client")
	}
	_ = resp
	return nil
}

// GetS3 implements Service.GetS3. GET /admin/s3/{s3-endpoint-id}.
func (s *service) GetS3(ctx context.Context, s3EndpointId string) error {
	if ctx == nil {
		return fmt.Errorf("admin.GetS3: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/s3/%s", url.PathEscape(s3EndpointId))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.GetS3: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.GetS3: nil response from client")
	}
	_ = resp
	return nil
}

// UpdateS3CheckParams is the request payload for UpdateS3Check.
type UpdateS3CheckParams struct {
	// Bucket Bucket name for S3 object store.
	Bucket string `json:"bucket"`
	// StorePrefix Store prefix within bucket for S3 object keys (commonly datastore name)
	StorePrefix *string `json:"store-prefix,omitempty"`
}

// UpdateS3Check implements Service.UpdateS3Check. PUT /admin/s3/{s3-endpoint-id}/check.
func (s *service) UpdateS3Check(ctx context.Context, s3EndpointId string, params *UpdateS3CheckParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.UpdateS3Check: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/s3/%s/check", url.PathEscape(s3EndpointId))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.UpdateS3Check: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.UpdateS3Check: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.UpdateS3Check: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.UpdateS3Check: nil response from client")
	}
	_ = resp
	return nil
}

// UpdateS3ResetCountersParams is the request payload for UpdateS3ResetCounters.
type UpdateS3ResetCountersParams struct {
	// Bucket Bucket name for S3 object store.
	Bucket string `json:"bucket"`
	// StorePrefix Store prefix within bucket for S3 object keys (commonly datastore name)
	StorePrefix *string `json:"store-prefix,omitempty"`
}

// UpdateS3ResetCounters implements Service.UpdateS3ResetCounters. PUT /admin/s3/{s3-endpoint-id}/reset-counters.
func (s *service) UpdateS3ResetCounters(ctx context.Context, s3EndpointId string, params *UpdateS3ResetCountersParams) error {
	if ctx == nil {
		return fmt.Errorf("admin.UpdateS3ResetCounters: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/s3/%s/reset-counters", url.PathEscape(s3EndpointId))
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return fmt.Errorf("admin.UpdateS3ResetCounters: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return fmt.Errorf("admin.UpdateS3ResetCounters: decode params: %w", err)
		}
	}
	resp, err := s.c.PutRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.UpdateS3ResetCounters: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.UpdateS3ResetCounters: nil response from client")
	}
	_ = resp
	return nil
}

// ListSyncParams is the request payload for ListSync.
type ListSyncParams struct {
	// Store Datastore name.
	Store *string `json:"store,omitempty"`
	// SyncDirection The direction of the listed sync jobs: push, pull or all.
	SyncDirection *string `json:"sync-direction,omitempty"`
}

// ListSyncResponse mirrors the shape returned by GET /admin/sync.
type ListSyncResponse []json.RawMessage

// ListSync implements Service.ListSync. GET /admin/sync.
func (s *service) ListSync(ctx context.Context, params *ListSyncParams) (*ListSyncResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.ListSync: ctx must not be nil")
	}
	path := "/admin/sync"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.ListSync: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.ListSync: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.ListSync: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.ListSync: nil response from client")
	}
	if resp.Data == nil {
		out := ListSyncResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.ListSync: re-marshal data: %w", err)
	}
	out := &ListSyncResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.ListSync: unmarshal data: %w", err)
	}
	return out, nil
}

// GetSync implements Service.GetSync. GET /admin/sync/{id}.
func (s *service) GetSync(ctx context.Context, id string) error {
	if ctx == nil {
		return fmt.Errorf("admin.GetSync: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/sync/%s", url.PathEscape(id))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.GetSync: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.GetSync: nil response from client")
	}
	_ = resp
	return nil
}

// CreateSyncRun implements Service.CreateSyncRun. POST /admin/sync/{id}/run.
func (s *service) CreateSyncRun(ctx context.Context, id string) error {
	if ctx == nil {
		return fmt.Errorf("admin.CreateSyncRun: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/sync/%s/run", url.PathEscape(id))
	var body map[string]interface{}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.CreateSyncRun: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.CreateSyncRun: nil response from client")
	}
	_ = resp
	return nil
}

// ListTrafficControlResponse mirrors the shape returned by GET /admin/traffic-control.
type ListTrafficControlResponse []json.RawMessage

// ListTrafficControl implements Service.ListTrafficControl. GET /admin/traffic-control.
func (s *service) ListTrafficControl(ctx context.Context) (*ListTrafficControlResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.ListTrafficControl: ctx must not be nil")
	}
	path := "/admin/traffic-control"
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.ListTrafficControl: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.ListTrafficControl: nil response from client")
	}
	if resp.Data == nil {
		out := ListTrafficControlResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.ListTrafficControl: re-marshal data: %w", err)
	}
	out := &ListTrafficControlResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.ListTrafficControl: unmarshal data: %w", err)
	}
	return out, nil
}

// ListVerifyParams is the request payload for ListVerify.
type ListVerifyParams struct {
	// Store Datastore name.
	Store *string `json:"store,omitempty"`
}

// ListVerifyResponse mirrors the shape returned by GET /admin/verify.
type ListVerifyResponse []json.RawMessage

// ListVerify implements Service.ListVerify. GET /admin/verify.
func (s *service) ListVerify(ctx context.Context, params *ListVerifyParams) (*ListVerifyResponse, error) {
	if ctx == nil {
		return nil, fmt.Errorf("admin.ListVerify: ctx must not be nil")
	}
	path := "/admin/verify"
	var body map[string]interface{}
	if params != nil {
		raw, err := json.Marshal(params)
		if err != nil {
			return nil, fmt.Errorf("admin.ListVerify: marshal params: %w", err)
		}
		dec := json.NewDecoder(strings.NewReader(string(raw)))
		dec.UseNumber()
		err = dec.Decode(&body)
		if err != nil {
			return nil, fmt.Errorf("admin.ListVerify: decode params: %w", err)
		}
	}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return nil, fmt.Errorf("admin.ListVerify: %w", err)
	}
	if resp == nil {
		return nil, fmt.Errorf("admin.ListVerify: nil response from client")
	}
	if resp.Data == nil {
		out := ListVerifyResponse{}
		return &out, nil
	}
	raw, err := json.Marshal(resp.Data)
	if err != nil {
		return nil, fmt.Errorf("admin.ListVerify: re-marshal data: %w", err)
	}
	out := &ListVerifyResponse{}
	err = json.Unmarshal(raw, out)
	if err != nil {
		return nil, fmt.Errorf("admin.ListVerify: unmarshal data: %w", err)
	}
	return out, nil
}

// GetVerify implements Service.GetVerify. GET /admin/verify/{id}.
func (s *service) GetVerify(ctx context.Context, id string) error {
	if ctx == nil {
		return fmt.Errorf("admin.GetVerify: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/verify/%s", url.PathEscape(id))
	var body map[string]interface{}
	resp, err := s.c.GetRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.GetVerify: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.GetVerify: nil response from client")
	}
	_ = resp
	return nil
}

// CreateVerifyRun implements Service.CreateVerifyRun. POST /admin/verify/{id}/run.
func (s *service) CreateVerifyRun(ctx context.Context, id string) error {
	if ctx == nil {
		return fmt.Errorf("admin.CreateVerifyRun: ctx must not be nil")
	}
	path := fmt.Sprintf("/admin/verify/%s/run", url.PathEscape(id))
	var body map[string]interface{}
	resp, err := s.c.PostRawCtx(ctx, path, body)
	if err != nil {
		return fmt.Errorf("admin.CreateVerifyRun: %w", err)
	}
	if resp == nil {
		return fmt.Errorf("admin.CreateVerifyRun: nil response from client")
	}
	_ = resp
	return nil
}
