// Code generated by cmd/pvegen. DO NOT EDIT.

package admin_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"sync"
	"testing"

	pveclient "github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/pbs/admin"
)

var _ = json.RawMessage(nil)

func smokeOptsFromServerURL(u string) pveclient.Options {
	parsed, err := url.Parse(u)
	if err != nil {
		panic("test setup: invalid server URL: " + err.Error())
	}

	host := parsed.Hostname()

	port := 0
	if p := parsed.Port(); p != "" {
		port, _ = strconv.Atoi(p)
	}

	return pveclient.Options{
		Host:     host,
		Port:     port,
		Protocol: "http",
		APIToken: "user@pam!tok=sec",
	}
}

// recordedRequest captures what the mock server observed for the most
// recently dispatched request.
type recordedRequest struct {
	method string
	path   string
	query  url.Values
	form   url.Values
}

// testHarness runs a single httptest.Server shared by every subtest in this
// file. Subtests are never run in parallel (each sets the desired response
// immediately before invoking the method under test, then reads back the
// recorded request), so the mutex below only guards against the harness
// goroutine and the test goroutine overlapping on a single in-flight
// request, never against concurrent subtests.
type testHarness struct {
	mu       sync.Mutex
	last     recordedRequest
	nextCode int
	nextBody string
}

// newTestHarness starts the mock server and returns it alongside the harness
// used to configure responses and inspect recorded requests.
func newTestHarness() (*httptest.Server, *testHarness) {
	h := &testHarness{nextCode: http.StatusOK}

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		h.mu.Lock()
		defer h.mu.Unlock()

		_ = r.ParseForm()
		h.last = recordedRequest{
			method: r.Method,
			path:   r.URL.Path,
			query:  r.URL.Query(),
			form:   r.PostForm,
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(h.nextCode)
		_, _ = w.Write([]byte(h.nextBody))
	}))

	return srv, h
}

// set configures the status code and body the next request will receive.
func (h *testHarness) set(code int, body string) {
	h.mu.Lock()
	defer h.mu.Unlock()

	h.nextCode = code
	h.nextBody = body
}

// snapshot returns a copy of the most recently recorded request.
func (h *testHarness) snapshot() recordedRequest {
	h.mu.Lock()
	defer h.mu.Unlock()

	return h.last
}

// assertRequestLine fails the test when the recorded method or resolved
// path does not exactly match what the endpoint's spec entry declares.
func assertRequestLine(t *testing.T, got recordedRequest, wantMethod, wantPath string) {
	t.Helper()

	if got.method != wantMethod {
		t.Errorf("method = %q, want %q", got.method, wantMethod)
	}

	if got.path != wantPath {
		t.Errorf("path = %q, want %q", got.path, wantPath)
	}
}

// assertParamValue fails the test when the wire-encoded value of key does
// not exactly equal want.
func assertParamValue(t *testing.T, values url.Values, key, want string) {
	t.Helper()

	if got := values.Get(key); got != want {
		t.Errorf("param %q = %q, want %q", key, got, want)
	}
}

// assertParamPresent fails the test when key is absent from values. Used for
// required parameters whose wire encoding is not a simple comparable string
// (e.g. json.RawMessage-typed fields).
func assertParamPresent(t *testing.T, values url.Values, key string) {
	t.Helper()

	if _, ok := values[key]; !ok {
		t.Errorf("param %q missing from request", key)
	}
}

func TestGenerated_Admin_Methods(t *testing.T) {
	srv, harness := newTestHarness()
	defer srv.Close()

	c, err := pveclient.NewClient(smokeOptsFromServerURL(srv.URL))
	if err != nil {
		t.Fatalf("NewClient: %v", err)
	}

	svc := admin.New(c)
	ctx := context.Background()

	t.Run("ListAdmin", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListAdmin(ctx)
		if err != nil {
			t.Fatalf("ListAdmin: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin")

		var nilCtx context.Context
		if err := svc.ListAdmin(nilCtx); err == nil {
			t.Errorf("ListAdmin: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastore", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListDatastore(ctx)
		if err != nil {
			t.Fatalf("ListDatastore: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListDatastore: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore")

		var nilCtx context.Context
		if _, err := svc.ListDatastore(nilCtx); err == nil {
			t.Errorf("ListDatastore: expected error for nil context, got nil")
		}
	})
	t.Run("GetDatastore", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.GetDatastore(ctx, "sample-store")
		if err != nil {
			t.Fatalf("GetDatastore: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store")

		var nilCtx context.Context
		if err := svc.GetDatastore(nilCtx, "sample-store"); err == nil {
			t.Errorf("GetDatastore: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastoreActiveOperations", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListDatastoreActiveOperations(ctx, "sample-store")
		if err != nil {
			t.Fatalf("ListDatastoreActiveOperations: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store/active-operations")

		var nilCtx context.Context
		if err := svc.ListDatastoreActiveOperations(nilCtx, "sample-store"); err == nil {
			t.Errorf("ListDatastoreActiveOperations: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastoreCatalog", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListDatastoreCatalog(ctx, "sample-store", &admin.ListDatastoreCatalogParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type", Filepath: "sample-filepath"})
		if err != nil {
			t.Fatalf("ListDatastoreCatalog: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store/catalog")
		assertParamValue(t, got.query, "backup-id", "sample-backup-id")
		assertParamValue(t, got.query, "backup-time", "42")
		assertParamValue(t, got.query, "backup-type", "sample-backup-type")
		assertParamValue(t, got.query, "filepath", "sample-filepath")

		var nilCtx context.Context
		if err := svc.ListDatastoreCatalog(nilCtx, "sample-store", &admin.ListDatastoreCatalogParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type", Filepath: "sample-filepath"}); err == nil {
			t.Errorf("ListDatastoreCatalog: expected error for nil context, got nil")
		}
	})
	t.Run("CreateDatastoreChangeOwner", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateDatastoreChangeOwner(ctx, "sample-store", &admin.CreateDatastoreChangeOwnerParams{BackupId: "sample-backup-id", BackupType: "sample-backup-type", NewOwner: "sample-new-owner"})
		if err != nil {
			t.Fatalf("CreateDatastoreChangeOwner: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/admin/datastore/sample-store/change-owner")
		assertParamValue(t, got.form, "backup-id", "sample-backup-id")
		assertParamValue(t, got.form, "backup-type", "sample-backup-type")
		assertParamValue(t, got.form, "new-owner", "sample-new-owner")

		var nilCtx context.Context
		if err := svc.CreateDatastoreChangeOwner(nilCtx, "sample-store", &admin.CreateDatastoreChangeOwnerParams{BackupId: "sample-backup-id", BackupType: "sample-backup-type", NewOwner: "sample-new-owner"}); err == nil {
			t.Errorf("CreateDatastoreChangeOwner: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastoreDownload", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListDatastoreDownload(ctx, "sample-store", &admin.ListDatastoreDownloadParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type", FileName: "sample-file-name"})
		if err != nil {
			t.Fatalf("ListDatastoreDownload: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store/download")
		assertParamValue(t, got.query, "backup-id", "sample-backup-id")
		assertParamValue(t, got.query, "backup-time", "42")
		assertParamValue(t, got.query, "backup-type", "sample-backup-type")
		assertParamValue(t, got.query, "file-name", "sample-file-name")

		var nilCtx context.Context
		if err := svc.ListDatastoreDownload(nilCtx, "sample-store", &admin.ListDatastoreDownloadParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type", FileName: "sample-file-name"}); err == nil {
			t.Errorf("ListDatastoreDownload: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastoreDownloadDecoded", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListDatastoreDownloadDecoded(ctx, "sample-store", &admin.ListDatastoreDownloadDecodedParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type", FileName: "sample-file-name"})
		if err != nil {
			t.Fatalf("ListDatastoreDownloadDecoded: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store/download-decoded")
		assertParamValue(t, got.query, "backup-id", "sample-backup-id")
		assertParamValue(t, got.query, "backup-time", "42")
		assertParamValue(t, got.query, "backup-type", "sample-backup-type")
		assertParamValue(t, got.query, "file-name", "sample-file-name")

		var nilCtx context.Context
		if err := svc.ListDatastoreDownloadDecoded(nilCtx, "sample-store", &admin.ListDatastoreDownloadDecodedParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type", FileName: "sample-file-name"}); err == nil {
			t.Errorf("ListDatastoreDownloadDecoded: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastoreFiles", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListDatastoreFiles(ctx, "sample-store", &admin.ListDatastoreFilesParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type"})
		if err != nil {
			t.Fatalf("ListDatastoreFiles: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListDatastoreFiles: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store/files")
		assertParamValue(t, got.query, "backup-id", "sample-backup-id")
		assertParamValue(t, got.query, "backup-time", "42")
		assertParamValue(t, got.query, "backup-type", "sample-backup-type")

		var nilCtx context.Context
		if _, err := svc.ListDatastoreFiles(nilCtx, "sample-store", &admin.ListDatastoreFilesParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type"}); err == nil {
			t.Errorf("ListDatastoreFiles: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastoreGc", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListDatastoreGc(ctx, "sample-store")
		if err != nil {
			t.Fatalf("ListDatastoreGc: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListDatastoreGc: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store/gc")

		var nilCtx context.Context
		if _, err := svc.ListDatastoreGc(nilCtx, "sample-store"); err == nil {
			t.Errorf("ListDatastoreGc: expected error for nil context, got nil")
		}
	})
	t.Run("CreateDatastoreGc", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateDatastoreGc(ctx, "sample-store")
		if err != nil {
			t.Fatalf("CreateDatastoreGc: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateDatastoreGc: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/admin/datastore/sample-store/gc")

		var nilCtx context.Context
		if _, err := svc.CreateDatastoreGc(nilCtx, "sample-store"); err == nil {
			t.Errorf("CreateDatastoreGc: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastoreGroupNotes", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListDatastoreGroupNotes(ctx, "sample-store", &admin.ListDatastoreGroupNotesParams{BackupId: "sample-backup-id", BackupType: "sample-backup-type"})
		if err != nil {
			t.Fatalf("ListDatastoreGroupNotes: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store/group-notes")
		assertParamValue(t, got.query, "backup-id", "sample-backup-id")
		assertParamValue(t, got.query, "backup-type", "sample-backup-type")

		var nilCtx context.Context
		if err := svc.ListDatastoreGroupNotes(nilCtx, "sample-store", &admin.ListDatastoreGroupNotesParams{BackupId: "sample-backup-id", BackupType: "sample-backup-type"}); err == nil {
			t.Errorf("ListDatastoreGroupNotes: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateDatastoreGroupNotes", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateDatastoreGroupNotes(ctx, "sample-store", &admin.UpdateDatastoreGroupNotesParams{BackupId: "sample-backup-id", BackupType: "sample-backup-type", Notes: "sample-notes"})
		if err != nil {
			t.Fatalf("UpdateDatastoreGroupNotes: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/admin/datastore/sample-store/group-notes")
		assertParamValue(t, got.form, "backup-id", "sample-backup-id")
		assertParamValue(t, got.form, "backup-type", "sample-backup-type")
		assertParamValue(t, got.form, "notes", "sample-notes")

		var nilCtx context.Context
		if err := svc.UpdateDatastoreGroupNotes(nilCtx, "sample-store", &admin.UpdateDatastoreGroupNotesParams{BackupId: "sample-backup-id", BackupType: "sample-backup-type", Notes: "sample-notes"}); err == nil {
			t.Errorf("UpdateDatastoreGroupNotes: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteDatastoreGroups", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.DeleteDatastoreGroups(ctx, "sample-store", &admin.DeleteDatastoreGroupsParams{BackupId: "sample-backup-id", BackupType: "sample-backup-type"})
		if err != nil {
			t.Fatalf("DeleteDatastoreGroups: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("DeleteDatastoreGroups: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/admin/datastore/sample-store/groups")
		assertParamValue(t, got.query, "backup-id", "sample-backup-id")
		assertParamValue(t, got.query, "backup-type", "sample-backup-type")

		var nilCtx context.Context
		if _, err := svc.DeleteDatastoreGroups(nilCtx, "sample-store", &admin.DeleteDatastoreGroupsParams{BackupId: "sample-backup-id", BackupType: "sample-backup-type"}); err == nil {
			t.Errorf("DeleteDatastoreGroups: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastoreGroups", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListDatastoreGroups(ctx, "sample-store", &admin.ListDatastoreGroupsParams{})
		if err != nil {
			t.Fatalf("ListDatastoreGroups: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListDatastoreGroups: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store/groups")

		var nilCtx context.Context
		if _, err := svc.ListDatastoreGroups(nilCtx, "sample-store", &admin.ListDatastoreGroupsParams{}); err == nil {
			t.Errorf("ListDatastoreGroups: expected error for nil context, got nil")
		}
	})
	t.Run("CreateDatastoreMount", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateDatastoreMount(ctx, "sample-store")
		if err != nil {
			t.Fatalf("CreateDatastoreMount: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateDatastoreMount: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/admin/datastore/sample-store/mount")

		var nilCtx context.Context
		if _, err := svc.CreateDatastoreMount(nilCtx, "sample-store"); err == nil {
			t.Errorf("CreateDatastoreMount: expected error for nil context, got nil")
		}
	})
	t.Run("CreateDatastoreMoveGroup", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateDatastoreMoveGroup(ctx, "sample-store", &admin.CreateDatastoreMoveGroupParams{BackupId: "sample-backup-id", BackupType: "sample-backup-type"})
		if err != nil {
			t.Fatalf("CreateDatastoreMoveGroup: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateDatastoreMoveGroup: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/admin/datastore/sample-store/move-group")
		assertParamValue(t, got.form, "backup-id", "sample-backup-id")
		assertParamValue(t, got.form, "backup-type", "sample-backup-type")

		var nilCtx context.Context
		if _, err := svc.CreateDatastoreMoveGroup(nilCtx, "sample-store", &admin.CreateDatastoreMoveGroupParams{BackupId: "sample-backup-id", BackupType: "sample-backup-type"}); err == nil {
			t.Errorf("CreateDatastoreMoveGroup: expected error for nil context, got nil")
		}
	})
	t.Run("CreateDatastoreMoveNamespace", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateDatastoreMoveNamespace(ctx, "sample-store", &admin.CreateDatastoreMoveNamespaceParams{Ns: "sample-ns", TargetNs: "sample-target-ns"})
		if err != nil {
			t.Fatalf("CreateDatastoreMoveNamespace: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateDatastoreMoveNamespace: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/admin/datastore/sample-store/move-namespace")
		assertParamValue(t, got.form, "ns", "sample-ns")
		assertParamValue(t, got.form, "target-ns", "sample-target-ns")

		var nilCtx context.Context
		if _, err := svc.CreateDatastoreMoveNamespace(nilCtx, "sample-store", &admin.CreateDatastoreMoveNamespaceParams{Ns: "sample-ns", TargetNs: "sample-target-ns"}); err == nil {
			t.Errorf("CreateDatastoreMoveNamespace: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteDatastoreNamespace", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.DeleteDatastoreNamespace(ctx, "sample-store", &admin.DeleteDatastoreNamespaceParams{Ns: "sample-ns"})
		if err != nil {
			t.Fatalf("DeleteDatastoreNamespace: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/admin/datastore/sample-store/namespace")
		assertParamValue(t, got.query, "ns", "sample-ns")

		var nilCtx context.Context
		if err := svc.DeleteDatastoreNamespace(nilCtx, "sample-store", &admin.DeleteDatastoreNamespaceParams{Ns: "sample-ns"}); err == nil {
			t.Errorf("DeleteDatastoreNamespace: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastoreNamespace", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListDatastoreNamespace(ctx, "sample-store", &admin.ListDatastoreNamespaceParams{})
		if err != nil {
			t.Fatalf("ListDatastoreNamespace: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListDatastoreNamespace: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store/namespace")

		var nilCtx context.Context
		if _, err := svc.ListDatastoreNamespace(nilCtx, "sample-store", &admin.ListDatastoreNamespaceParams{}); err == nil {
			t.Errorf("ListDatastoreNamespace: expected error for nil context, got nil")
		}
	})
	t.Run("CreateDatastoreNamespace", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateDatastoreNamespace(ctx, "sample-store", &admin.CreateDatastoreNamespaceParams{Name: "sample-name"})
		if err != nil {
			t.Fatalf("CreateDatastoreNamespace: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateDatastoreNamespace: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/admin/datastore/sample-store/namespace")
		assertParamValue(t, got.form, "name", "sample-name")

		var nilCtx context.Context
		if _, err := svc.CreateDatastoreNamespace(nilCtx, "sample-store", &admin.CreateDatastoreNamespaceParams{Name: "sample-name"}); err == nil {
			t.Errorf("CreateDatastoreNamespace: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastoreNotes", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListDatastoreNotes(ctx, "sample-store", &admin.ListDatastoreNotesParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type"})
		if err != nil {
			t.Fatalf("ListDatastoreNotes: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store/notes")
		assertParamValue(t, got.query, "backup-id", "sample-backup-id")
		assertParamValue(t, got.query, "backup-time", "42")
		assertParamValue(t, got.query, "backup-type", "sample-backup-type")

		var nilCtx context.Context
		if err := svc.ListDatastoreNotes(nilCtx, "sample-store", &admin.ListDatastoreNotesParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type"}); err == nil {
			t.Errorf("ListDatastoreNotes: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateDatastoreNotes", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateDatastoreNotes(ctx, "sample-store", &admin.UpdateDatastoreNotesParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type", Notes: "sample-notes"})
		if err != nil {
			t.Fatalf("UpdateDatastoreNotes: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/admin/datastore/sample-store/notes")
		assertParamValue(t, got.form, "backup-id", "sample-backup-id")
		assertParamValue(t, got.form, "backup-time", "42")
		assertParamValue(t, got.form, "backup-type", "sample-backup-type")
		assertParamValue(t, got.form, "notes", "sample-notes")

		var nilCtx context.Context
		if err := svc.UpdateDatastoreNotes(nilCtx, "sample-store", &admin.UpdateDatastoreNotesParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type", Notes: "sample-notes"}); err == nil {
			t.Errorf("UpdateDatastoreNotes: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastoreProtected", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListDatastoreProtected(ctx, "sample-store", &admin.ListDatastoreProtectedParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type"})
		if err != nil {
			t.Fatalf("ListDatastoreProtected: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store/protected")
		assertParamValue(t, got.query, "backup-id", "sample-backup-id")
		assertParamValue(t, got.query, "backup-time", "42")
		assertParamValue(t, got.query, "backup-type", "sample-backup-type")

		var nilCtx context.Context
		if err := svc.ListDatastoreProtected(nilCtx, "sample-store", &admin.ListDatastoreProtectedParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type"}); err == nil {
			t.Errorf("ListDatastoreProtected: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateDatastoreProtected", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateDatastoreProtected(ctx, "sample-store", &admin.UpdateDatastoreProtectedParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type", Protected: true})
		if err != nil {
			t.Fatalf("UpdateDatastoreProtected: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/admin/datastore/sample-store/protected")
		assertParamValue(t, got.form, "backup-id", "sample-backup-id")
		assertParamValue(t, got.form, "backup-time", "42")
		assertParamValue(t, got.form, "backup-type", "sample-backup-type")
		assertParamValue(t, got.form, "protected", "1")

		var nilCtx context.Context
		if err := svc.UpdateDatastoreProtected(nilCtx, "sample-store", &admin.UpdateDatastoreProtectedParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type", Protected: true}); err == nil {
			t.Errorf("UpdateDatastoreProtected: expected error for nil context, got nil")
		}
	})
	t.Run("CreateDatastorePrune", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.CreateDatastorePrune(ctx, "sample-store", &admin.CreateDatastorePruneParams{BackupId: "sample-backup-id", BackupType: "sample-backup-type"})
		if err != nil {
			t.Fatalf("CreateDatastorePrune: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateDatastorePrune: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/admin/datastore/sample-store/prune")
		assertParamValue(t, got.form, "backup-id", "sample-backup-id")
		assertParamValue(t, got.form, "backup-type", "sample-backup-type")

		var nilCtx context.Context
		if _, err := svc.CreateDatastorePrune(nilCtx, "sample-store", &admin.CreateDatastorePruneParams{BackupId: "sample-backup-id", BackupType: "sample-backup-type"}); err == nil {
			t.Errorf("CreateDatastorePrune: expected error for nil context, got nil")
		}
	})
	t.Run("CreateDatastorePruneDatastore", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateDatastorePruneDatastore(ctx, "sample-store", &admin.CreateDatastorePruneDatastoreParams{})
		if err != nil {
			t.Fatalf("CreateDatastorePruneDatastore: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateDatastorePruneDatastore: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/admin/datastore/sample-store/prune-datastore")

		var nilCtx context.Context
		if _, err := svc.CreateDatastorePruneDatastore(nilCtx, "sample-store", &admin.CreateDatastorePruneDatastoreParams{}); err == nil {
			t.Errorf("CreateDatastorePruneDatastore: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastorePxarFileDownload", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListDatastorePxarFileDownload(ctx, "sample-store", &admin.ListDatastorePxarFileDownloadParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type", Filepath: "sample-filepath"})
		if err != nil {
			t.Fatalf("ListDatastorePxarFileDownload: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store/pxar-file-download")
		assertParamValue(t, got.query, "backup-id", "sample-backup-id")
		assertParamValue(t, got.query, "backup-time", "42")
		assertParamValue(t, got.query, "backup-type", "sample-backup-type")
		assertParamValue(t, got.query, "filepath", "sample-filepath")

		var nilCtx context.Context
		if err := svc.ListDatastorePxarFileDownload(nilCtx, "sample-store", &admin.ListDatastorePxarFileDownloadParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type", Filepath: "sample-filepath"}); err == nil {
			t.Errorf("ListDatastorePxarFileDownload: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastoreRrd", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListDatastoreRrd(ctx, "sample-store", &admin.ListDatastoreRrdParams{Cf: "sample-cf", Timeframe: "sample-timeframe"})
		if err != nil {
			t.Fatalf("ListDatastoreRrd: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store/rrd")
		assertParamValue(t, got.query, "cf", "sample-cf")
		assertParamValue(t, got.query, "timeframe", "sample-timeframe")

		var nilCtx context.Context
		if err := svc.ListDatastoreRrd(nilCtx, "sample-store", &admin.ListDatastoreRrdParams{Cf: "sample-cf", Timeframe: "sample-timeframe"}); err == nil {
			t.Errorf("ListDatastoreRrd: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateDatastoreS3Refresh", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.UpdateDatastoreS3Refresh(ctx, "sample-store")
		if err != nil {
			t.Fatalf("UpdateDatastoreS3Refresh: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("UpdateDatastoreS3Refresh: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/admin/datastore/sample-store/s3-refresh")

		var nilCtx context.Context
		if _, err := svc.UpdateDatastoreS3Refresh(nilCtx, "sample-store"); err == nil {
			t.Errorf("UpdateDatastoreS3Refresh: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteDatastoreSnapshots", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.DeleteDatastoreSnapshots(ctx, "sample-store", &admin.DeleteDatastoreSnapshotsParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type"})
		if err != nil {
			t.Fatalf("DeleteDatastoreSnapshots: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/admin/datastore/sample-store/snapshots")
		assertParamValue(t, got.query, "backup-id", "sample-backup-id")
		assertParamValue(t, got.query, "backup-time", "42")
		assertParamValue(t, got.query, "backup-type", "sample-backup-type")

		var nilCtx context.Context
		if err := svc.DeleteDatastoreSnapshots(nilCtx, "sample-store", &admin.DeleteDatastoreSnapshotsParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type"}); err == nil {
			t.Errorf("DeleteDatastoreSnapshots: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastoreSnapshots", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListDatastoreSnapshots(ctx, "sample-store", &admin.ListDatastoreSnapshotsParams{})
		if err != nil {
			t.Fatalf("ListDatastoreSnapshots: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListDatastoreSnapshots: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store/snapshots")

		var nilCtx context.Context
		if _, err := svc.ListDatastoreSnapshots(nilCtx, "sample-store", &admin.ListDatastoreSnapshotsParams{}); err == nil {
			t.Errorf("ListDatastoreSnapshots: expected error for nil context, got nil")
		}
	})
	t.Run("ListDatastoreStatus", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListDatastoreStatus(ctx, "sample-store", &admin.ListDatastoreStatusParams{})
		if err != nil {
			t.Fatalf("ListDatastoreStatus: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListDatastoreStatus: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/datastore/sample-store/status")

		var nilCtx context.Context
		if _, err := svc.ListDatastoreStatus(nilCtx, "sample-store", &admin.ListDatastoreStatusParams{}); err == nil {
			t.Errorf("ListDatastoreStatus: expected error for nil context, got nil")
		}
	})
	t.Run("CreateDatastoreUnmount", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateDatastoreUnmount(ctx, "sample-store")
		if err != nil {
			t.Fatalf("CreateDatastoreUnmount: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateDatastoreUnmount: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/admin/datastore/sample-store/unmount")

		var nilCtx context.Context
		if _, err := svc.CreateDatastoreUnmount(nilCtx, "sample-store"); err == nil {
			t.Errorf("CreateDatastoreUnmount: expected error for nil context, got nil")
		}
	})
	t.Run("CreateDatastoreUploadBackupLog", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateDatastoreUploadBackupLog(ctx, "sample-store", &admin.CreateDatastoreUploadBackupLogParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type"})
		if err != nil {
			t.Fatalf("CreateDatastoreUploadBackupLog: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/admin/datastore/sample-store/upload-backup-log")
		assertParamValue(t, got.form, "backup-id", "sample-backup-id")
		assertParamValue(t, got.form, "backup-time", "42")
		assertParamValue(t, got.form, "backup-type", "sample-backup-type")

		var nilCtx context.Context
		if err := svc.CreateDatastoreUploadBackupLog(nilCtx, "sample-store", &admin.CreateDatastoreUploadBackupLogParams{BackupId: "sample-backup-id", BackupTime: 42, BackupType: "sample-backup-type"}); err == nil {
			t.Errorf("CreateDatastoreUploadBackupLog: expected error for nil context, got nil")
		}
	})
	t.Run("CreateDatastoreVerify", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateDatastoreVerify(ctx, "sample-store", &admin.CreateDatastoreVerifyParams{})
		if err != nil {
			t.Fatalf("CreateDatastoreVerify: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateDatastoreVerify: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/admin/datastore/sample-store/verify")

		var nilCtx context.Context
		if _, err := svc.CreateDatastoreVerify(nilCtx, "sample-store", &admin.CreateDatastoreVerifyParams{}); err == nil {
			t.Errorf("CreateDatastoreVerify: expected error for nil context, got nil")
		}
	})
	t.Run("ListGc", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListGc(ctx, &admin.ListGcParams{})
		if err != nil {
			t.Fatalf("ListGc: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListGc: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/gc")

		var nilCtx context.Context
		if _, err := svc.ListGc(nilCtx, &admin.ListGcParams{}); err == nil {
			t.Errorf("ListGc: expected error for nil context, got nil")
		}
	})
	t.Run("GetGc", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.GetGc(ctx, "sample-store")
		if err != nil {
			t.Fatalf("GetGc: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("GetGc: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/gc/sample-store")

		var nilCtx context.Context
		if _, err := svc.GetGc(nilCtx, "sample-store"); err == nil {
			t.Errorf("GetGc: expected error for nil context, got nil")
		}
	})
	t.Run("ListMetrics", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListMetrics(ctx)
		if err != nil {
			t.Fatalf("ListMetrics: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListMetrics: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/metrics")

		var nilCtx context.Context
		if _, err := svc.ListMetrics(nilCtx); err == nil {
			t.Errorf("ListMetrics: expected error for nil context, got nil")
		}
	})
	t.Run("ListPrune", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListPrune(ctx, &admin.ListPruneParams{})
		if err != nil {
			t.Fatalf("ListPrune: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListPrune: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/prune")

		var nilCtx context.Context
		if _, err := svc.ListPrune(nilCtx, &admin.ListPruneParams{}); err == nil {
			t.Errorf("ListPrune: expected error for nil context, got nil")
		}
	})
	t.Run("GetPrune", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.GetPrune(ctx, "sample-id")
		if err != nil {
			t.Fatalf("GetPrune: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/prune/sample-id")

		var nilCtx context.Context
		if err := svc.GetPrune(nilCtx, "sample-id"); err == nil {
			t.Errorf("GetPrune: expected error for nil context, got nil")
		}
	})
	t.Run("CreatePruneRun", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreatePruneRun(ctx, "sample-id")
		if err != nil {
			t.Fatalf("CreatePruneRun: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/admin/prune/sample-id/run")

		var nilCtx context.Context
		if err := svc.CreatePruneRun(nilCtx, "sample-id"); err == nil {
			t.Errorf("CreatePruneRun: expected error for nil context, got nil")
		}
	})
	t.Run("GetS3", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.GetS3(ctx, "sample-s3-endpoint-id")
		if err != nil {
			t.Fatalf("GetS3: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/s3/sample-s3-endpoint-id")

		var nilCtx context.Context
		if err := svc.GetS3(nilCtx, "sample-s3-endpoint-id"); err == nil {
			t.Errorf("GetS3: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateS3Check", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateS3Check(ctx, "sample-s3-endpoint-id", &admin.UpdateS3CheckParams{Bucket: "sample-bucket"})
		if err != nil {
			t.Fatalf("UpdateS3Check: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/admin/s3/sample-s3-endpoint-id/check")
		assertParamValue(t, got.form, "bucket", "sample-bucket")

		var nilCtx context.Context
		if err := svc.UpdateS3Check(nilCtx, "sample-s3-endpoint-id", &admin.UpdateS3CheckParams{Bucket: "sample-bucket"}); err == nil {
			t.Errorf("UpdateS3Check: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateS3ResetCounters", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateS3ResetCounters(ctx, "sample-s3-endpoint-id", &admin.UpdateS3ResetCountersParams{Bucket: "sample-bucket"})
		if err != nil {
			t.Fatalf("UpdateS3ResetCounters: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/admin/s3/sample-s3-endpoint-id/reset-counters")
		assertParamValue(t, got.form, "bucket", "sample-bucket")

		var nilCtx context.Context
		if err := svc.UpdateS3ResetCounters(nilCtx, "sample-s3-endpoint-id", &admin.UpdateS3ResetCountersParams{Bucket: "sample-bucket"}); err == nil {
			t.Errorf("UpdateS3ResetCounters: expected error for nil context, got nil")
		}
	})
	t.Run("ListSync", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListSync(ctx, &admin.ListSyncParams{})
		if err != nil {
			t.Fatalf("ListSync: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListSync: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/sync")

		var nilCtx context.Context
		if _, err := svc.ListSync(nilCtx, &admin.ListSyncParams{}); err == nil {
			t.Errorf("ListSync: expected error for nil context, got nil")
		}
	})
	t.Run("GetSync", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.GetSync(ctx, "sample-id")
		if err != nil {
			t.Fatalf("GetSync: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/sync/sample-id")

		var nilCtx context.Context
		if err := svc.GetSync(nilCtx, "sample-id"); err == nil {
			t.Errorf("GetSync: expected error for nil context, got nil")
		}
	})
	t.Run("CreateSyncRun", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateSyncRun(ctx, "sample-id")
		if err != nil {
			t.Fatalf("CreateSyncRun: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/admin/sync/sample-id/run")

		var nilCtx context.Context
		if err := svc.CreateSyncRun(nilCtx, "sample-id"); err == nil {
			t.Errorf("CreateSyncRun: expected error for nil context, got nil")
		}
	})
	t.Run("ListTrafficControl", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListTrafficControl(ctx)
		if err != nil {
			t.Fatalf("ListTrafficControl: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListTrafficControl: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/traffic-control")

		var nilCtx context.Context
		if _, err := svc.ListTrafficControl(nilCtx); err == nil {
			t.Errorf("ListTrafficControl: expected error for nil context, got nil")
		}
	})
	t.Run("ListVerify", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListVerify(ctx, &admin.ListVerifyParams{})
		if err != nil {
			t.Fatalf("ListVerify: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListVerify: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/verify")

		var nilCtx context.Context
		if _, err := svc.ListVerify(nilCtx, &admin.ListVerifyParams{}); err == nil {
			t.Errorf("ListVerify: expected error for nil context, got nil")
		}
	})
	t.Run("GetVerify", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.GetVerify(ctx, "sample-id")
		if err != nil {
			t.Fatalf("GetVerify: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/admin/verify/sample-id")

		var nilCtx context.Context
		if err := svc.GetVerify(nilCtx, "sample-id"); err == nil {
			t.Errorf("GetVerify: expected error for nil context, got nil")
		}
	})
	t.Run("CreateVerifyRun", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateVerifyRun(ctx, "sample-id")
		if err != nil {
			t.Fatalf("CreateVerifyRun: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/admin/verify/sample-id/run")

		var nilCtx context.Context
		if err := svc.CreateVerifyRun(nilCtx, "sample-id"); err == nil {
			t.Errorf("CreateVerifyRun: expected error for nil context, got nil")
		}
	})
	t.Run("ErrorPath_GET", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.ListAdmin(ctx)
		if err == nil {
			t.Fatalf("ListAdmin: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_POST", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.CreateDatastoreChangeOwner(ctx, "sample-store", &admin.CreateDatastoreChangeOwnerParams{BackupId: "sample-backup-id", BackupType: "sample-backup-type", NewOwner: "sample-new-owner"})
		if err == nil {
			t.Fatalf("CreateDatastoreChangeOwner: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_PUT", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.UpdateDatastoreGroupNotes(ctx, "sample-store", &admin.UpdateDatastoreGroupNotesParams{BackupId: "sample-backup-id", BackupType: "sample-backup-type", Notes: "sample-notes"})
		if err == nil {
			t.Fatalf("UpdateDatastoreGroupNotes: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_DELETE", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		_, err := svc.DeleteDatastoreGroups(ctx, "sample-store", &admin.DeleteDatastoreGroupsParams{BackupId: "sample-backup-id", BackupType: "sample-backup-type"})
		if err == nil {
			t.Fatalf("DeleteDatastoreGroups: expected error on 500 response, got nil")
		}
	})
}
