// Code generated by cmd/pvegen. DO NOT EDIT.

package access_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strconv"
	"sync"
	"testing"

	pveclient "github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/client"
	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/pdm/access"
)

var _ = json.RawMessage(nil)

func smokeOptsFromServerURL(u string) pveclient.Options {
	parsed, err := url.Parse(u)
	if err != nil {
		panic("test setup: invalid server URL: " + err.Error())
	}

	host := parsed.Hostname()

	port := 0
	if p := parsed.Port(); p != "" {
		port, _ = strconv.Atoi(p)
	}

	return pveclient.Options{
		Host:     host,
		Port:     port,
		Protocol: "http",
		APIToken: "user@pam!tok=sec",
	}
}

// recordedRequest captures what the mock server observed for the most
// recently dispatched request.
type recordedRequest struct {
	method string
	path   string
	query  url.Values
	form   url.Values
}

// testHarness runs a single httptest.Server shared by every subtest in this
// file. Subtests are never run in parallel (each sets the desired response
// immediately before invoking the method under test, then reads back the
// recorded request), so the mutex below only guards against the harness
// goroutine and the test goroutine overlapping on a single in-flight
// request, never against concurrent subtests.
type testHarness struct {
	mu       sync.Mutex
	last     recordedRequest
	nextCode int
	nextBody string
}

// newTestHarness starts the mock server and returns it alongside the harness
// used to configure responses and inspect recorded requests.
func newTestHarness() (*httptest.Server, *testHarness) {
	h := &testHarness{nextCode: http.StatusOK}

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		h.mu.Lock()
		defer h.mu.Unlock()

		_ = r.ParseForm()
		h.last = recordedRequest{
			method: r.Method,
			path:   r.URL.Path,
			query:  r.URL.Query(),
			form:   r.PostForm,
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(h.nextCode)
		_, _ = w.Write([]byte(h.nextBody))
	}))

	return srv, h
}

// set configures the status code and body the next request will receive.
func (h *testHarness) set(code int, body string) {
	h.mu.Lock()
	defer h.mu.Unlock()

	h.nextCode = code
	h.nextBody = body
}

// snapshot returns a copy of the most recently recorded request.
func (h *testHarness) snapshot() recordedRequest {
	h.mu.Lock()
	defer h.mu.Unlock()

	return h.last
}

// assertRequestLine fails the test when the recorded method or resolved
// path does not exactly match what the endpoint's spec entry declares.
func assertRequestLine(t *testing.T, got recordedRequest, wantMethod, wantPath string) {
	t.Helper()

	if got.method != wantMethod {
		t.Errorf("method = %q, want %q", got.method, wantMethod)
	}

	if got.path != wantPath {
		t.Errorf("path = %q, want %q", got.path, wantPath)
	}
}

// assertParamValue fails the test when the wire-encoded value of key does
// not exactly equal want.
func assertParamValue(t *testing.T, values url.Values, key, want string) {
	t.Helper()

	if got := values.Get(key); got != want {
		t.Errorf("param %q = %q, want %q", key, got, want)
	}
}

// assertParamPresent fails the test when key is absent from values. Used for
// required parameters whose wire encoding is not a simple comparable string
// (e.g. json.RawMessage-typed fields).
func assertParamPresent(t *testing.T, values url.Values, key string) {
	t.Helper()

	if _, ok := values[key]; !ok {
		t.Errorf("param %q missing from request", key)
	}
}

func TestGenerated_Access_Methods(t *testing.T) {
	srv, harness := newTestHarness()
	defer srv.Close()

	c, err := pveclient.NewClient(smokeOptsFromServerURL(srv.URL))
	if err != nil {
		t.Fatalf("NewClient: %v", err)
	}

	svc := access.New(c)
	ctx := context.Background()

	t.Run("ListAccess", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListAccess(ctx)
		if err != nil {
			t.Fatalf("ListAccess: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/access")

		var nilCtx context.Context
		if err := svc.ListAccess(nilCtx); err == nil {
			t.Errorf("ListAccess: expected error for nil context, got nil")
		}
	})
	t.Run("ListAcl", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListAcl(ctx, &access.ListAclParams{})
		if err != nil {
			t.Fatalf("ListAcl: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListAcl: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/access/acl")

		var nilCtx context.Context
		if _, err := svc.ListAcl(nilCtx, &access.ListAclParams{}); err == nil {
			t.Errorf("ListAcl: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateAcl", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateAcl(ctx, &access.UpdateAclParams{Path: "sample-path", Role: "sample-role"})
		if err != nil {
			t.Fatalf("UpdateAcl: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/access/acl")
		assertParamValue(t, got.form, "path", "sample-path")
		assertParamValue(t, got.form, "role", "sample-role")

		var nilCtx context.Context
		if err := svc.UpdateAcl(nilCtx, &access.UpdateAclParams{Path: "sample-path", Role: "sample-role"}); err == nil {
			t.Errorf("UpdateAcl: expected error for nil context, got nil")
		}
	})
	t.Run("ListDomains", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListDomains(ctx)
		if err != nil {
			t.Fatalf("ListDomains: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListDomains: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/access/domains")

		var nilCtx context.Context
		if _, err := svc.ListDomains(nilCtx); err == nil {
			t.Errorf("ListDomains: expected error for nil context, got nil")
		}
	})
	t.Run("CreateDomainsSync", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateDomainsSync(ctx, "sample-realm", &access.CreateDomainsSyncParams{})
		if err != nil {
			t.Fatalf("CreateDomainsSync: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateDomainsSync: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/access/domains/sample-realm/sync")

		var nilCtx context.Context
		if _, err := svc.CreateDomainsSync(nilCtx, "sample-realm", &access.CreateDomainsSyncParams{}); err == nil {
			t.Errorf("CreateDomainsSync: expected error for nil context, got nil")
		}
	})
	t.Run("ListOpenid", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.ListOpenid(ctx)
		if err != nil {
			t.Fatalf("ListOpenid: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/access/openid")

		var nilCtx context.Context
		if err := svc.ListOpenid(nilCtx); err == nil {
			t.Errorf("ListOpenid: expected error for nil context, got nil")
		}
	})
	t.Run("CreateOpenidAuthUrl", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateOpenidAuthUrl(ctx, &access.CreateOpenidAuthUrlParams{Realm: "sample-realm", RedirectUrl: "sample-redirect-url"})
		if err != nil {
			t.Fatalf("CreateOpenidAuthUrl: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateOpenidAuthUrl: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/access/openid/auth-url")
		assertParamValue(t, got.form, "realm", "sample-realm")
		assertParamValue(t, got.form, "redirect-url", "sample-redirect-url")

		var nilCtx context.Context
		if _, err := svc.CreateOpenidAuthUrl(nilCtx, &access.CreateOpenidAuthUrlParams{Realm: "sample-realm", RedirectUrl: "sample-redirect-url"}); err == nil {
			t.Errorf("CreateOpenidAuthUrl: expected error for nil context, got nil")
		}
	})
	t.Run("CreateOpenidLogin", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateOpenidLogin(ctx, &access.CreateOpenidLoginParams{Code: "sample-code", RedirectUrl: "sample-redirect-url", State: "sample-state"})
		if err != nil {
			t.Fatalf("CreateOpenidLogin: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateOpenidLogin: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/access/openid/login")
		assertParamValue(t, got.form, "code", "sample-code")
		assertParamValue(t, got.form, "redirect-url", "sample-redirect-url")
		assertParamValue(t, got.form, "state", "sample-state")

		var nilCtx context.Context
		if _, err := svc.CreateOpenidLogin(nilCtx, &access.CreateOpenidLoginParams{Code: "sample-code", RedirectUrl: "sample-redirect-url", State: "sample-state"}); err == nil {
			t.Errorf("CreateOpenidLogin: expected error for nil context, got nil")
		}
	})
	t.Run("ListPermissions", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.ListPermissions(ctx, &access.ListPermissionsParams{})
		if err != nil {
			t.Fatalf("ListPermissions: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListPermissions: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/access/permissions")

		var nilCtx context.Context
		if _, err := svc.ListPermissions(nilCtx, &access.ListPermissionsParams{}); err == nil {
			t.Errorf("ListPermissions: expected error for nil context, got nil")
		}
	})
	t.Run("ListRoles", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListRoles(ctx)
		if err != nil {
			t.Fatalf("ListRoles: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListRoles: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/access/roles")

		var nilCtx context.Context
		if _, err := svc.ListRoles(nilCtx); err == nil {
			t.Errorf("ListRoles: expected error for nil context, got nil")
		}
	})
	t.Run("ListTfa", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListTfa(ctx)
		if err != nil {
			t.Fatalf("ListTfa: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListTfa: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/access/tfa")

		var nilCtx context.Context
		if _, err := svc.ListTfa(nilCtx); err == nil {
			t.Errorf("ListTfa: expected error for nil context, got nil")
		}
	})
	t.Run("GetTfa", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.GetTfa(ctx, "sample-userid")
		if err != nil {
			t.Fatalf("GetTfa: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("GetTfa: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/access/tfa/sample-userid")

		var nilCtx context.Context
		if _, err := svc.GetTfa(nilCtx, "sample-userid"); err == nil {
			t.Errorf("GetTfa: expected error for nil context, got nil")
		}
	})
	t.Run("CreateTfa", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateTfa(ctx, "sample-userid", &access.CreateTfaParams{Type: "sample-type"})
		if err != nil {
			t.Fatalf("CreateTfa: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateTfa: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/access/tfa/sample-userid")
		assertParamValue(t, got.form, "type", "sample-type")

		var nilCtx context.Context
		if _, err := svc.CreateTfa(nilCtx, "sample-userid", &access.CreateTfaParams{Type: "sample-type"}); err == nil {
			t.Errorf("CreateTfa: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteTfa", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.DeleteTfa(ctx, "sample-userid", "sample-id", &access.DeleteTfaParams{})
		if err != nil {
			t.Fatalf("DeleteTfa: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/access/tfa/sample-userid/sample-id")

		var nilCtx context.Context
		if err := svc.DeleteTfa(nilCtx, "sample-userid", "sample-id", &access.DeleteTfaParams{}); err == nil {
			t.Errorf("DeleteTfa: expected error for nil context, got nil")
		}
	})
	t.Run("GetTfa2", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.GetTfa2(ctx, "sample-userid", "sample-id")
		if err != nil {
			t.Fatalf("GetTfa2: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("GetTfa2: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/access/tfa/sample-userid/sample-id")

		var nilCtx context.Context
		if _, err := svc.GetTfa2(nilCtx, "sample-userid", "sample-id"); err == nil {
			t.Errorf("GetTfa2: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateTfa", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateTfa(ctx, "sample-userid", "sample-id", &access.UpdateTfaParams{})
		if err != nil {
			t.Fatalf("UpdateTfa: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/access/tfa/sample-userid/sample-id")

		var nilCtx context.Context
		if err := svc.UpdateTfa(nilCtx, "sample-userid", "sample-id", &access.UpdateTfaParams{}); err == nil {
			t.Errorf("UpdateTfa: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteTicket", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.DeleteTicket(ctx)
		if err != nil {
			t.Fatalf("DeleteTicket: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/access/ticket")

		var nilCtx context.Context
		if err := svc.DeleteTicket(nilCtx); err == nil {
			t.Errorf("DeleteTicket: expected error for nil context, got nil")
		}
	})
	t.Run("CreateTicket", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateTicket(ctx, &access.CreateTicketParams{Username: "sample-username"})
		if err != nil {
			t.Fatalf("CreateTicket: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateTicket: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/access/ticket")
		assertParamValue(t, got.form, "username", "sample-username")

		var nilCtx context.Context
		if _, err := svc.CreateTicket(nilCtx, &access.CreateTicketParams{Username: "sample-username"}); err == nil {
			t.Errorf("CreateTicket: expected error for nil context, got nil")
		}
	})
	t.Run("ListUsers", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListUsers(ctx, &access.ListUsersParams{})
		if err != nil {
			t.Fatalf("ListUsers: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListUsers: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/access/users")

		var nilCtx context.Context
		if _, err := svc.ListUsers(nilCtx, &access.ListUsersParams{}); err == nil {
			t.Errorf("ListUsers: expected error for nil context, got nil")
		}
	})
	t.Run("CreateUsers", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.CreateUsers(ctx, &access.CreateUsersParams{Userid: "sample-userid"})
		if err != nil {
			t.Fatalf("CreateUsers: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/access/users")
		assertParamValue(t, got.form, "userid", "sample-userid")

		var nilCtx context.Context
		if err := svc.CreateUsers(nilCtx, &access.CreateUsersParams{Userid: "sample-userid"}); err == nil {
			t.Errorf("CreateUsers: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteUsers", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.DeleteUsers(ctx, "sample-userid", &access.DeleteUsersParams{})
		if err != nil {
			t.Fatalf("DeleteUsers: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/access/users/sample-userid")

		var nilCtx context.Context
		if err := svc.DeleteUsers(nilCtx, "sample-userid", &access.DeleteUsersParams{}); err == nil {
			t.Errorf("DeleteUsers: expected error for nil context, got nil")
		}
	})
	t.Run("GetUsers", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.GetUsers(ctx, "sample-userid")
		if err != nil {
			t.Fatalf("GetUsers: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("GetUsers: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/access/users/sample-userid")

		var nilCtx context.Context
		if _, err := svc.GetUsers(nilCtx, "sample-userid"); err == nil {
			t.Errorf("GetUsers: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateUsers", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.UpdateUsers(ctx, "sample-userid", &access.UpdateUsersParams{})
		if err != nil {
			t.Fatalf("UpdateUsers: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/access/users/sample-userid")

		var nilCtx context.Context
		if err := svc.UpdateUsers(nilCtx, "sample-userid", &access.UpdateUsersParams{}); err == nil {
			t.Errorf("UpdateUsers: expected error for nil context, got nil")
		}
	})
	t.Run("ListUsersToken", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":[],"success":1}`)

		resp, err := svc.ListUsersToken(ctx, "sample-userid")
		if err != nil {
			t.Fatalf("ListUsersToken: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("ListUsersToken: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/access/users/sample-userid/token")

		var nilCtx context.Context
		if _, err := svc.ListUsersToken(nilCtx, "sample-userid"); err == nil {
			t.Errorf("ListUsersToken: expected error for nil context, got nil")
		}
	})
	t.Run("DeleteUsersToken", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		err := svc.DeleteUsersToken(ctx, "sample-userid", "sample-token-name", &access.DeleteUsersTokenParams{})
		if err != nil {
			t.Fatalf("DeleteUsersToken: unexpected error: %v", err)
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "DELETE", "/api2/json/access/users/sample-userid/token/sample-token-name")

		var nilCtx context.Context
		if err := svc.DeleteUsersToken(nilCtx, "sample-userid", "sample-token-name", &access.DeleteUsersTokenParams{}); err == nil {
			t.Errorf("DeleteUsersToken: expected error for nil context, got nil")
		}
	})
	t.Run("GetUsersToken", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.GetUsersToken(ctx, "sample-userid", "sample-token-name")
		if err != nil {
			t.Fatalf("GetUsersToken: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("GetUsersToken: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "GET", "/api2/json/access/users/sample-userid/token/sample-token-name")

		var nilCtx context.Context
		if _, err := svc.GetUsersToken(nilCtx, "sample-userid", "sample-token-name"); err == nil {
			t.Errorf("GetUsersToken: expected error for nil context, got nil")
		}
	})
	t.Run("CreateUsersToken", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.CreateUsersToken(ctx, "sample-userid", "sample-token-name", &access.CreateUsersTokenParams{})
		if err != nil {
			t.Fatalf("CreateUsersToken: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("CreateUsersToken: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "POST", "/api2/json/access/users/sample-userid/token/sample-token-name")

		var nilCtx context.Context
		if _, err := svc.CreateUsersToken(nilCtx, "sample-userid", "sample-token-name", &access.CreateUsersTokenParams{}); err == nil {
			t.Errorf("CreateUsersToken: expected error for nil context, got nil")
		}
	})
	t.Run("UpdateUsersToken", func(t *testing.T) {
		harness.set(http.StatusOK, `{"data":{},"success":1}`)

		resp, err := svc.UpdateUsersToken(ctx, "sample-userid", "sample-token-name", &access.UpdateUsersTokenParams{})
		if err != nil {
			t.Fatalf("UpdateUsersToken: unexpected error: %v", err)
		}
		if resp == nil {
			t.Fatal("UpdateUsersToken: response is nil")
		}

		got := harness.snapshot()
		assertRequestLine(t, got, "PUT", "/api2/json/access/users/sample-userid/token/sample-token-name")

		var nilCtx context.Context
		if _, err := svc.UpdateUsersToken(nilCtx, "sample-userid", "sample-token-name", &access.UpdateUsersTokenParams{}); err == nil {
			t.Errorf("UpdateUsersToken: expected error for nil context, got nil")
		}
	})
	t.Run("ErrorPath_GET", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.ListAccess(ctx)
		if err == nil {
			t.Fatalf("ListAccess: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_PUT", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.UpdateAcl(ctx, &access.UpdateAclParams{Path: "sample-path", Role: "sample-role"})
		if err == nil {
			t.Fatalf("UpdateAcl: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_POST", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		_, err := svc.CreateDomainsSync(ctx, "sample-realm", &access.CreateDomainsSyncParams{})
		if err == nil {
			t.Fatalf("CreateDomainsSync: expected error on 500 response, got nil")
		}
	})
	t.Run("ErrorPath_DELETE", func(t *testing.T) {
		harness.set(http.StatusInternalServerError, `{"data":null,"success":0,"message":"boom"}`)

		err := svc.DeleteTfa(ctx, "sample-userid", "sample-id", &access.DeleteTfaParams{})
		if err == nil {
			t.Fatalf("DeleteTfa: expected error on 500 response, got nil")
		}
	})
}
